SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/verification:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkSystolic.v /tools/inst/lib/Verilog/FIFO2.v

EXTRA_ARGS = --trace --trace-structs -DBSV_NO_INITIAL_BLOCKS

TOPLEVEL = mkSystolic
MODULE   := test_systolic

include $(shell cocotb-config --makefiles)/Makefile.sim
