//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Sun Nov 17 07:29:34 IST 2024
//
//
// Ports:
// Name                         I/O  size props
// RDY_set_A_matrix               O     1
// RDY_set_B_matrix               O     1
// RDY_set_C_row1                 O     1
// RDY_set_s1_or_s2_row1          O     1
// RDY_initialise_systolic        O     1
// RDY_set_state_systolic         O     1 const
// get_result                     O   128
// RDY_get_result                 O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// set_A_matrix_a_matrix          I    64 reg
// set_B_matrix_b_matrix          I    64 reg
// set_C_row1_c_val               I    32
// set_s1_or_s2_row1_s1_or_s2_in  I     1
// initialise_systolic_s1_or_s2_in  I     1
// set_state_systolic_state_in    I     1 reg
// EN_set_A_matrix                I     1
// EN_set_B_matrix                I     1
// EN_set_C_row1                  I     1
// EN_set_s1_or_s2_row1           I     1
// EN_initialise_systolic         I     1
// EN_set_state_systolic          I     1
// EN_get_result                  I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSystolic(CLK,
		  RST_N,

		  set_A_matrix_a_matrix,
		  EN_set_A_matrix,
		  RDY_set_A_matrix,

		  set_B_matrix_b_matrix,
		  EN_set_B_matrix,
		  RDY_set_B_matrix,

		  set_C_row1_c_val,
		  EN_set_C_row1,
		  RDY_set_C_row1,

		  set_s1_or_s2_row1_s1_or_s2_in,
		  EN_set_s1_or_s2_row1,
		  RDY_set_s1_or_s2_row1,

		  initialise_systolic_s1_or_s2_in,
		  EN_initialise_systolic,
		  RDY_initialise_systolic,

		  set_state_systolic_state_in,
		  EN_set_state_systolic,
		  RDY_set_state_systolic,

		  EN_get_result,
		  get_result,
		  RDY_get_result);
  input  CLK;
  input  RST_N;

  // action method set_A_matrix
  input  [63 : 0] set_A_matrix_a_matrix;
  input  EN_set_A_matrix;
  output RDY_set_A_matrix;

  // action method set_B_matrix
  input  [63 : 0] set_B_matrix_b_matrix;
  input  EN_set_B_matrix;
  output RDY_set_B_matrix;

  // action method set_C_row1
  input  [31 : 0] set_C_row1_c_val;
  input  EN_set_C_row1;
  output RDY_set_C_row1;

  // action method set_s1_or_s2_row1
  input  set_s1_or_s2_row1_s1_or_s2_in;
  input  EN_set_s1_or_s2_row1;
  output RDY_set_s1_or_s2_row1;

  // action method initialise_systolic
  input  initialise_systolic_s1_or_s2_in;
  input  EN_initialise_systolic;
  output RDY_initialise_systolic;

  // action method set_state_systolic
  input  set_state_systolic_state_in;
  input  EN_set_state_systolic;
  output RDY_set_state_systolic;

  // actionvalue method get_result
  input  EN_get_result;
  output [127 : 0] get_result;
  output RDY_get_result;

  // signals for module outputs
  wire [127 : 0] get_result;
  wire RDY_get_result,
       RDY_initialise_systolic,
       RDY_set_A_matrix,
       RDY_set_B_matrix,
       RDY_set_C_row1,
       RDY_set_s1_or_s2_row1,
       RDY_set_state_systolic;

  // register counter
  reg [31 : 0] counter;
  wire [31 : 0] counter_D_IN;
  wire counter_EN;

  // ports of submodule systolic_array_0_0
  wire [31 : 0] systolic_array_0_0_get_result, systolic_array_0_0_set_c_c_in;
  wire [15 : 0] systolic_array_0_0_get_a,
		systolic_array_0_0_get_b,
		systolic_array_0_0_set_a_a_in,
		systolic_array_0_0_set_b_b_in;
  wire systolic_array_0_0_EN_set_a,
       systolic_array_0_0_EN_set_b,
       systolic_array_0_0_EN_set_c,
       systolic_array_0_0_EN_set_s1_or_s2,
       systolic_array_0_0_EN_set_state,
       systolic_array_0_0_RDY_get_a,
       systolic_array_0_0_RDY_get_b,
       systolic_array_0_0_RDY_get_result,
       systolic_array_0_0_RDY_get_s1_or_s2,
       systolic_array_0_0_RDY_set_a,
       systolic_array_0_0_RDY_set_b,
       systolic_array_0_0_RDY_set_c,
       systolic_array_0_0_RDY_set_s1_or_s2,
       systolic_array_0_0_get_s1_or_s2,
       systolic_array_0_0_set_s1_or_s2_s1_or_s2_in,
       systolic_array_0_0_set_state_transfer_b_state;

  // ports of submodule systolic_array_0_1
  wire [31 : 0] systolic_array_0_1_get_result, systolic_array_0_1_set_c_c_in;
  wire [15 : 0] systolic_array_0_1_get_a,
		systolic_array_0_1_get_b,
		systolic_array_0_1_set_a_a_in,
		systolic_array_0_1_set_b_b_in;
  wire systolic_array_0_1_EN_set_a,
       systolic_array_0_1_EN_set_b,
       systolic_array_0_1_EN_set_c,
       systolic_array_0_1_EN_set_s1_or_s2,
       systolic_array_0_1_EN_set_state,
       systolic_array_0_1_RDY_get_a,
       systolic_array_0_1_RDY_get_b,
       systolic_array_0_1_RDY_get_result,
       systolic_array_0_1_RDY_get_s1_or_s2,
       systolic_array_0_1_RDY_set_a,
       systolic_array_0_1_RDY_set_b,
       systolic_array_0_1_RDY_set_c,
       systolic_array_0_1_RDY_set_s1_or_s2,
       systolic_array_0_1_get_s1_or_s2,
       systolic_array_0_1_set_s1_or_s2_s1_or_s2_in,
       systolic_array_0_1_set_state_transfer_b_state;

  // ports of submodule systolic_array_0_2
  wire [31 : 0] systolic_array_0_2_get_result, systolic_array_0_2_set_c_c_in;
  wire [15 : 0] systolic_array_0_2_get_a,
		systolic_array_0_2_get_b,
		systolic_array_0_2_set_a_a_in,
		systolic_array_0_2_set_b_b_in;
  wire systolic_array_0_2_EN_set_a,
       systolic_array_0_2_EN_set_b,
       systolic_array_0_2_EN_set_c,
       systolic_array_0_2_EN_set_s1_or_s2,
       systolic_array_0_2_EN_set_state,
       systolic_array_0_2_RDY_get_a,
       systolic_array_0_2_RDY_get_b,
       systolic_array_0_2_RDY_get_result,
       systolic_array_0_2_RDY_get_s1_or_s2,
       systolic_array_0_2_RDY_set_a,
       systolic_array_0_2_RDY_set_b,
       systolic_array_0_2_RDY_set_c,
       systolic_array_0_2_RDY_set_s1_or_s2,
       systolic_array_0_2_get_s1_or_s2,
       systolic_array_0_2_set_s1_or_s2_s1_or_s2_in,
       systolic_array_0_2_set_state_transfer_b_state;

  // ports of submodule systolic_array_0_3
  wire [31 : 0] systolic_array_0_3_get_result, systolic_array_0_3_set_c_c_in;
  wire [15 : 0] systolic_array_0_3_get_b,
		systolic_array_0_3_set_a_a_in,
		systolic_array_0_3_set_b_b_in;
  wire systolic_array_0_3_EN_set_a,
       systolic_array_0_3_EN_set_b,
       systolic_array_0_3_EN_set_c,
       systolic_array_0_3_EN_set_s1_or_s2,
       systolic_array_0_3_EN_set_state,
       systolic_array_0_3_RDY_get_b,
       systolic_array_0_3_RDY_get_result,
       systolic_array_0_3_RDY_get_s1_or_s2,
       systolic_array_0_3_RDY_set_a,
       systolic_array_0_3_RDY_set_b,
       systolic_array_0_3_RDY_set_c,
       systolic_array_0_3_RDY_set_s1_or_s2,
       systolic_array_0_3_get_s1_or_s2,
       systolic_array_0_3_set_s1_or_s2_s1_or_s2_in,
       systolic_array_0_3_set_state_transfer_b_state;

  // ports of submodule systolic_array_1_0
  wire [31 : 0] systolic_array_1_0_get_result, systolic_array_1_0_set_c_c_in;
  wire [15 : 0] systolic_array_1_0_get_a,
		systolic_array_1_0_get_b,
		systolic_array_1_0_set_a_a_in,
		systolic_array_1_0_set_b_b_in;
  wire systolic_array_1_0_EN_set_a,
       systolic_array_1_0_EN_set_b,
       systolic_array_1_0_EN_set_c,
       systolic_array_1_0_EN_set_s1_or_s2,
       systolic_array_1_0_EN_set_state,
       systolic_array_1_0_RDY_get_a,
       systolic_array_1_0_RDY_get_b,
       systolic_array_1_0_RDY_get_result,
       systolic_array_1_0_RDY_get_s1_or_s2,
       systolic_array_1_0_RDY_set_a,
       systolic_array_1_0_RDY_set_b,
       systolic_array_1_0_RDY_set_c,
       systolic_array_1_0_RDY_set_s1_or_s2,
       systolic_array_1_0_get_s1_or_s2,
       systolic_array_1_0_set_s1_or_s2_s1_or_s2_in,
       systolic_array_1_0_set_state_transfer_b_state;

  // ports of submodule systolic_array_1_1
  wire [31 : 0] systolic_array_1_1_get_result, systolic_array_1_1_set_c_c_in;
  wire [15 : 0] systolic_array_1_1_get_a,
		systolic_array_1_1_get_b,
		systolic_array_1_1_set_a_a_in,
		systolic_array_1_1_set_b_b_in;
  wire systolic_array_1_1_EN_set_a,
       systolic_array_1_1_EN_set_b,
       systolic_array_1_1_EN_set_c,
       systolic_array_1_1_EN_set_s1_or_s2,
       systolic_array_1_1_EN_set_state,
       systolic_array_1_1_RDY_get_a,
       systolic_array_1_1_RDY_get_b,
       systolic_array_1_1_RDY_get_result,
       systolic_array_1_1_RDY_get_s1_or_s2,
       systolic_array_1_1_RDY_set_a,
       systolic_array_1_1_RDY_set_b,
       systolic_array_1_1_RDY_set_c,
       systolic_array_1_1_RDY_set_s1_or_s2,
       systolic_array_1_1_get_s1_or_s2,
       systolic_array_1_1_set_s1_or_s2_s1_or_s2_in,
       systolic_array_1_1_set_state_transfer_b_state;

  // ports of submodule systolic_array_1_2
  wire [31 : 0] systolic_array_1_2_get_result, systolic_array_1_2_set_c_c_in;
  wire [15 : 0] systolic_array_1_2_get_a,
		systolic_array_1_2_get_b,
		systolic_array_1_2_set_a_a_in,
		systolic_array_1_2_set_b_b_in;
  wire systolic_array_1_2_EN_set_a,
       systolic_array_1_2_EN_set_b,
       systolic_array_1_2_EN_set_c,
       systolic_array_1_2_EN_set_s1_or_s2,
       systolic_array_1_2_EN_set_state,
       systolic_array_1_2_RDY_get_a,
       systolic_array_1_2_RDY_get_b,
       systolic_array_1_2_RDY_get_result,
       systolic_array_1_2_RDY_get_s1_or_s2,
       systolic_array_1_2_RDY_set_a,
       systolic_array_1_2_RDY_set_b,
       systolic_array_1_2_RDY_set_c,
       systolic_array_1_2_RDY_set_s1_or_s2,
       systolic_array_1_2_get_s1_or_s2,
       systolic_array_1_2_set_s1_or_s2_s1_or_s2_in,
       systolic_array_1_2_set_state_transfer_b_state;

  // ports of submodule systolic_array_1_3
  wire [31 : 0] systolic_array_1_3_get_result, systolic_array_1_3_set_c_c_in;
  wire [15 : 0] systolic_array_1_3_get_b,
		systolic_array_1_3_set_a_a_in,
		systolic_array_1_3_set_b_b_in;
  wire systolic_array_1_3_EN_set_a,
       systolic_array_1_3_EN_set_b,
       systolic_array_1_3_EN_set_c,
       systolic_array_1_3_EN_set_s1_or_s2,
       systolic_array_1_3_EN_set_state,
       systolic_array_1_3_RDY_get_b,
       systolic_array_1_3_RDY_get_result,
       systolic_array_1_3_RDY_get_s1_or_s2,
       systolic_array_1_3_RDY_set_a,
       systolic_array_1_3_RDY_set_b,
       systolic_array_1_3_RDY_set_c,
       systolic_array_1_3_RDY_set_s1_or_s2,
       systolic_array_1_3_get_s1_or_s2,
       systolic_array_1_3_set_s1_or_s2_s1_or_s2_in,
       systolic_array_1_3_set_state_transfer_b_state;

  // ports of submodule systolic_array_2_0
  wire [31 : 0] systolic_array_2_0_get_result, systolic_array_2_0_set_c_c_in;
  wire [15 : 0] systolic_array_2_0_get_a,
		systolic_array_2_0_get_b,
		systolic_array_2_0_set_a_a_in,
		systolic_array_2_0_set_b_b_in;
  wire systolic_array_2_0_EN_set_a,
       systolic_array_2_0_EN_set_b,
       systolic_array_2_0_EN_set_c,
       systolic_array_2_0_EN_set_s1_or_s2,
       systolic_array_2_0_EN_set_state,
       systolic_array_2_0_RDY_get_a,
       systolic_array_2_0_RDY_get_b,
       systolic_array_2_0_RDY_get_result,
       systolic_array_2_0_RDY_get_s1_or_s2,
       systolic_array_2_0_RDY_set_a,
       systolic_array_2_0_RDY_set_b,
       systolic_array_2_0_RDY_set_c,
       systolic_array_2_0_RDY_set_s1_or_s2,
       systolic_array_2_0_get_s1_or_s2,
       systolic_array_2_0_set_s1_or_s2_s1_or_s2_in,
       systolic_array_2_0_set_state_transfer_b_state;

  // ports of submodule systolic_array_2_1
  wire [31 : 0] systolic_array_2_1_get_result, systolic_array_2_1_set_c_c_in;
  wire [15 : 0] systolic_array_2_1_get_a,
		systolic_array_2_1_get_b,
		systolic_array_2_1_set_a_a_in,
		systolic_array_2_1_set_b_b_in;
  wire systolic_array_2_1_EN_set_a,
       systolic_array_2_1_EN_set_b,
       systolic_array_2_1_EN_set_c,
       systolic_array_2_1_EN_set_s1_or_s2,
       systolic_array_2_1_EN_set_state,
       systolic_array_2_1_RDY_get_a,
       systolic_array_2_1_RDY_get_b,
       systolic_array_2_1_RDY_get_result,
       systolic_array_2_1_RDY_get_s1_or_s2,
       systolic_array_2_1_RDY_set_a,
       systolic_array_2_1_RDY_set_b,
       systolic_array_2_1_RDY_set_c,
       systolic_array_2_1_RDY_set_s1_or_s2,
       systolic_array_2_1_get_s1_or_s2,
       systolic_array_2_1_set_s1_or_s2_s1_or_s2_in,
       systolic_array_2_1_set_state_transfer_b_state;

  // ports of submodule systolic_array_2_2
  wire [31 : 0] systolic_array_2_2_get_result, systolic_array_2_2_set_c_c_in;
  wire [15 : 0] systolic_array_2_2_get_a,
		systolic_array_2_2_get_b,
		systolic_array_2_2_set_a_a_in,
		systolic_array_2_2_set_b_b_in;
  wire systolic_array_2_2_EN_set_a,
       systolic_array_2_2_EN_set_b,
       systolic_array_2_2_EN_set_c,
       systolic_array_2_2_EN_set_s1_or_s2,
       systolic_array_2_2_EN_set_state,
       systolic_array_2_2_RDY_get_a,
       systolic_array_2_2_RDY_get_b,
       systolic_array_2_2_RDY_get_result,
       systolic_array_2_2_RDY_get_s1_or_s2,
       systolic_array_2_2_RDY_set_a,
       systolic_array_2_2_RDY_set_b,
       systolic_array_2_2_RDY_set_c,
       systolic_array_2_2_RDY_set_s1_or_s2,
       systolic_array_2_2_get_s1_or_s2,
       systolic_array_2_2_set_s1_or_s2_s1_or_s2_in,
       systolic_array_2_2_set_state_transfer_b_state;

  // ports of submodule systolic_array_2_3
  wire [31 : 0] systolic_array_2_3_get_result, systolic_array_2_3_set_c_c_in;
  wire [15 : 0] systolic_array_2_3_get_b,
		systolic_array_2_3_set_a_a_in,
		systolic_array_2_3_set_b_b_in;
  wire systolic_array_2_3_EN_set_a,
       systolic_array_2_3_EN_set_b,
       systolic_array_2_3_EN_set_c,
       systolic_array_2_3_EN_set_s1_or_s2,
       systolic_array_2_3_EN_set_state,
       systolic_array_2_3_RDY_get_b,
       systolic_array_2_3_RDY_get_result,
       systolic_array_2_3_RDY_get_s1_or_s2,
       systolic_array_2_3_RDY_set_a,
       systolic_array_2_3_RDY_set_b,
       systolic_array_2_3_RDY_set_c,
       systolic_array_2_3_RDY_set_s1_or_s2,
       systolic_array_2_3_get_s1_or_s2,
       systolic_array_2_3_set_s1_or_s2_s1_or_s2_in,
       systolic_array_2_3_set_state_transfer_b_state;

  // ports of submodule systolic_array_3_0
  wire [31 : 0] systolic_array_3_0_get_result, systolic_array_3_0_set_c_c_in;
  wire [15 : 0] systolic_array_3_0_get_a,
		systolic_array_3_0_set_a_a_in,
		systolic_array_3_0_set_b_b_in;
  wire systolic_array_3_0_EN_set_a,
       systolic_array_3_0_EN_set_b,
       systolic_array_3_0_EN_set_c,
       systolic_array_3_0_EN_set_s1_or_s2,
       systolic_array_3_0_EN_set_state,
       systolic_array_3_0_RDY_get_a,
       systolic_array_3_0_RDY_get_result,
       systolic_array_3_0_RDY_set_a,
       systolic_array_3_0_RDY_set_b,
       systolic_array_3_0_RDY_set_c,
       systolic_array_3_0_RDY_set_s1_or_s2,
       systolic_array_3_0_set_s1_or_s2_s1_or_s2_in,
       systolic_array_3_0_set_state_transfer_b_state;

  // ports of submodule systolic_array_3_1
  wire [31 : 0] systolic_array_3_1_get_result, systolic_array_3_1_set_c_c_in;
  wire [15 : 0] systolic_array_3_1_get_a,
		systolic_array_3_1_set_a_a_in,
		systolic_array_3_1_set_b_b_in;
  wire systolic_array_3_1_EN_set_a,
       systolic_array_3_1_EN_set_b,
       systolic_array_3_1_EN_set_c,
       systolic_array_3_1_EN_set_s1_or_s2,
       systolic_array_3_1_EN_set_state,
       systolic_array_3_1_RDY_get_a,
       systolic_array_3_1_RDY_get_result,
       systolic_array_3_1_RDY_set_a,
       systolic_array_3_1_RDY_set_b,
       systolic_array_3_1_RDY_set_c,
       systolic_array_3_1_RDY_set_s1_or_s2,
       systolic_array_3_1_set_s1_or_s2_s1_or_s2_in,
       systolic_array_3_1_set_state_transfer_b_state;

  // ports of submodule systolic_array_3_2
  wire [31 : 0] systolic_array_3_2_get_result, systolic_array_3_2_set_c_c_in;
  wire [15 : 0] systolic_array_3_2_get_a,
		systolic_array_3_2_set_a_a_in,
		systolic_array_3_2_set_b_b_in;
  wire systolic_array_3_2_EN_set_a,
       systolic_array_3_2_EN_set_b,
       systolic_array_3_2_EN_set_c,
       systolic_array_3_2_EN_set_s1_or_s2,
       systolic_array_3_2_EN_set_state,
       systolic_array_3_2_RDY_get_a,
       systolic_array_3_2_RDY_get_result,
       systolic_array_3_2_RDY_set_a,
       systolic_array_3_2_RDY_set_b,
       systolic_array_3_2_RDY_set_c,
       systolic_array_3_2_RDY_set_s1_or_s2,
       systolic_array_3_2_set_s1_or_s2_s1_or_s2_in,
       systolic_array_3_2_set_state_transfer_b_state;

  // ports of submodule systolic_array_3_3
  wire [31 : 0] systolic_array_3_3_get_result, systolic_array_3_3_set_c_c_in;
  wire [15 : 0] systolic_array_3_3_set_a_a_in, systolic_array_3_3_set_b_b_in;
  wire systolic_array_3_3_EN_set_a,
       systolic_array_3_3_EN_set_b,
       systolic_array_3_3_EN_set_c,
       systolic_array_3_3_EN_set_s1_or_s2,
       systolic_array_3_3_EN_set_state,
       systolic_array_3_3_RDY_get_result,
       systolic_array_3_3_RDY_set_a,
       systolic_array_3_3_RDY_set_b,
       systolic_array_3_3_RDY_set_c,
       systolic_array_3_3_RDY_set_s1_or_s2,
       systolic_array_3_3_set_s1_or_s2_s1_or_s2_in,
       systolic_array_3_3_set_state_transfer_b_state;

  // rule scheduling signals
  wire CAN_FIRE_RL_count_up,
       CAN_FIRE_RL_shift_a_column1,
       CAN_FIRE_RL_shift_a_column2,
       CAN_FIRE_RL_shift_a_column3,
       CAN_FIRE_RL_shift_b_row1,
       CAN_FIRE_RL_shift_b_row2,
       CAN_FIRE_RL_shift_b_row3,
       CAN_FIRE_RL_shift_c_row1,
       CAN_FIRE_RL_shift_c_row2,
       CAN_FIRE_RL_shift_c_row3,
       CAN_FIRE_get_result,
       CAN_FIRE_initialise_systolic,
       CAN_FIRE_set_A_matrix,
       CAN_FIRE_set_B_matrix,
       CAN_FIRE_set_C_row1,
       CAN_FIRE_set_s1_or_s2_row1,
       CAN_FIRE_set_state_systolic,
       WILL_FIRE_RL_count_up,
       WILL_FIRE_RL_shift_a_column1,
       WILL_FIRE_RL_shift_a_column2,
       WILL_FIRE_RL_shift_a_column3,
       WILL_FIRE_RL_shift_b_row1,
       WILL_FIRE_RL_shift_b_row2,
       WILL_FIRE_RL_shift_b_row3,
       WILL_FIRE_RL_shift_c_row1,
       WILL_FIRE_RL_shift_c_row2,
       WILL_FIRE_RL_shift_c_row3,
       WILL_FIRE_get_result,
       WILL_FIRE_initialise_systolic,
       WILL_FIRE_set_A_matrix,
       WILL_FIRE_set_B_matrix,
       WILL_FIRE_set_C_row1,
       WILL_FIRE_set_s1_or_s2_row1,
       WILL_FIRE_set_state_systolic;

  // remaining internal signals
  wire systolic_array_0_1_RDY_get_b_AND_systolic_arra_ETC___d16,
       systolic_array_0_1_RDY_set_s1_or_s2__61_AND_sy_ETC___d307,
       systolic_array_0_3_RDY_get_s1_or_s2__3_AND_sys_ETC___d87,
       systolic_array_0_3_RDY_set_c__57_AND_systolic__ETC___d289,
       systolic_array_1_0_RDY_get_a__78_AND_systolic__ETC___d190,
       systolic_array_1_1_RDY_get_a__97_AND_systolic__ETC___d209,
       systolic_array_1_1_RDY_get_b__3_AND_systolic_a_ETC___d35,
       systolic_array_1_1_RDY_set_s1_or_s2__9_AND_sys_ETC___d81,
       systolic_array_1_2_RDY_get_a__16_AND_systolic__ETC___d228,
       systolic_array_1_3_RDY_get_s1_or_s2__02_AND_sy_ETC___d126,
       systolic_array_1_3_RDY_set_a__20_AND_systolic__ETC___d271,
       systolic_array_1_3_RDY_set_s1_or_s2__1_AND_sys_ETC___d301,
       systolic_array_2_1_RDY_get_b__2_AND_systolic_a_ETC___d54,
       systolic_array_2_1_RDY_set_c__12_AND_systolic__ETC___d283,
       systolic_array_2_1_RDY_set_s1_or_s2__08_AND_sy_ETC___d120,
       systolic_array_2_3_RDY_get_s1_or_s2__41_AND_sy_ETC___d165,
       systolic_array_3_1_RDY_set_s1_or_s2__47_AND_sy_ETC___d159,
       systolic_array_3_1_RDY_set_s1_or_s2__47_AND_sy_ETC___d295,
       systolic_array_3_3_RDY_set_c__53_AND_systolic__ETC___d277;

  // action method set_A_matrix
  assign RDY_set_A_matrix =
	     systolic_array_0_0_RDY_set_a && systolic_array_1_0_RDY_set_a &&
	     systolic_array_2_0_RDY_set_a &&
	     systolic_array_3_0_RDY_set_a ;
  assign CAN_FIRE_set_A_matrix =
	     systolic_array_0_0_RDY_set_a && systolic_array_1_0_RDY_set_a &&
	     systolic_array_2_0_RDY_set_a &&
	     systolic_array_3_0_RDY_set_a ;
  assign WILL_FIRE_set_A_matrix = EN_set_A_matrix ;

  // action method set_B_matrix
  assign RDY_set_B_matrix =
	     systolic_array_0_0_RDY_set_b && systolic_array_0_1_RDY_set_b &&
	     systolic_array_0_2_RDY_set_b &&
	     systolic_array_0_3_RDY_set_b ;
  assign CAN_FIRE_set_B_matrix =
	     systolic_array_0_0_RDY_set_b && systolic_array_0_1_RDY_set_b &&
	     systolic_array_0_2_RDY_set_b &&
	     systolic_array_0_3_RDY_set_b ;
  assign WILL_FIRE_set_B_matrix = EN_set_B_matrix ;

  // action method set_C_row1
  assign RDY_set_C_row1 =
	     systolic_array_0_0_RDY_set_c && systolic_array_0_1_RDY_set_c &&
	     systolic_array_0_2_RDY_set_c &&
	     systolic_array_0_3_RDY_set_c ;
  assign CAN_FIRE_set_C_row1 =
	     systolic_array_0_0_RDY_set_c && systolic_array_0_1_RDY_set_c &&
	     systolic_array_0_2_RDY_set_c &&
	     systolic_array_0_3_RDY_set_c ;
  assign WILL_FIRE_set_C_row1 = EN_set_C_row1 ;

  // action method set_s1_or_s2_row1
  assign RDY_set_s1_or_s2_row1 =
	     systolic_array_0_0_RDY_set_s1_or_s2 &&
	     systolic_array_0_1_RDY_set_s1_or_s2 &&
	     systolic_array_0_2_RDY_set_s1_or_s2 &&
	     systolic_array_0_3_RDY_set_s1_or_s2 ;
  assign CAN_FIRE_set_s1_or_s2_row1 =
	     systolic_array_0_0_RDY_set_s1_or_s2 &&
	     systolic_array_0_1_RDY_set_s1_or_s2 &&
	     systolic_array_0_2_RDY_set_s1_or_s2 &&
	     systolic_array_0_3_RDY_set_s1_or_s2 ;
  assign WILL_FIRE_set_s1_or_s2_row1 = EN_set_s1_or_s2_row1 ;

  // action method initialise_systolic
  assign RDY_initialise_systolic =
	     systolic_array_0_0_RDY_set_s1_or_s2 &&
	     systolic_array_0_1_RDY_set_s1_or_s2__61_AND_sy_ETC___d307 ;
  assign CAN_FIRE_initialise_systolic =
	     systolic_array_0_0_RDY_set_s1_or_s2 &&
	     systolic_array_0_1_RDY_set_s1_or_s2__61_AND_sy_ETC___d307 ;
  assign WILL_FIRE_initialise_systolic = EN_initialise_systolic ;

  // action method set_state_systolic
  assign RDY_set_state_systolic = 1'd1 ;
  assign CAN_FIRE_set_state_systolic = 1'd1 ;
  assign WILL_FIRE_set_state_systolic = EN_set_state_systolic ;

  // actionvalue method get_result
  assign get_result =
	     { systolic_array_3_3_get_result,
	       systolic_array_3_2_get_result,
	       systolic_array_3_1_get_result,
	       systolic_array_3_0_get_result } ;
  assign RDY_get_result =
	     systolic_array_3_0_RDY_get_result &&
	     systolic_array_3_1_RDY_get_result &&
	     systolic_array_3_2_RDY_get_result &&
	     systolic_array_3_3_RDY_get_result ;
  assign CAN_FIRE_get_result =
	     systolic_array_3_0_RDY_get_result &&
	     systolic_array_3_1_RDY_get_result &&
	     systolic_array_3_2_RDY_get_result &&
	     systolic_array_3_3_RDY_get_result ;
  assign WILL_FIRE_get_result = EN_get_result ;

  // submodule systolic_array_0_0
  mkMacSystolic systolic_array_0_0(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_0_0_set_a_a_in),
				   .set_b_b_in(systolic_array_0_0_set_b_b_in),
				   .set_c_c_in(systolic_array_0_0_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_0_0_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_0_0_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_0_0_EN_set_state),
				   .EN_set_a(systolic_array_0_0_EN_set_a),
				   .EN_set_b(systolic_array_0_0_EN_set_b),
				   .EN_set_c(systolic_array_0_0_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_0_0_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_0_0_RDY_set_a),
				   .RDY_set_b(systolic_array_0_0_RDY_set_b),
				   .RDY_set_c(systolic_array_0_0_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_0_0_RDY_set_s1_or_s2),
				   .get_result(systolic_array_0_0_get_result),
				   .RDY_get_result(systolic_array_0_0_RDY_get_result),
				   .get_a(systolic_array_0_0_get_a),
				   .RDY_get_a(systolic_array_0_0_RDY_get_a),
				   .get_b(systolic_array_0_0_get_b),
				   .RDY_get_b(systolic_array_0_0_RDY_get_b),
				   .get_s1_or_s2(systolic_array_0_0_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_0_0_RDY_get_s1_or_s2));

  // submodule systolic_array_0_1
  mkMacSystolic systolic_array_0_1(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_0_1_set_a_a_in),
				   .set_b_b_in(systolic_array_0_1_set_b_b_in),
				   .set_c_c_in(systolic_array_0_1_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_0_1_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_0_1_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_0_1_EN_set_state),
				   .EN_set_a(systolic_array_0_1_EN_set_a),
				   .EN_set_b(systolic_array_0_1_EN_set_b),
				   .EN_set_c(systolic_array_0_1_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_0_1_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_0_1_RDY_set_a),
				   .RDY_set_b(systolic_array_0_1_RDY_set_b),
				   .RDY_set_c(systolic_array_0_1_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_0_1_RDY_set_s1_or_s2),
				   .get_result(systolic_array_0_1_get_result),
				   .RDY_get_result(systolic_array_0_1_RDY_get_result),
				   .get_a(systolic_array_0_1_get_a),
				   .RDY_get_a(systolic_array_0_1_RDY_get_a),
				   .get_b(systolic_array_0_1_get_b),
				   .RDY_get_b(systolic_array_0_1_RDY_get_b),
				   .get_s1_or_s2(systolic_array_0_1_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_0_1_RDY_get_s1_or_s2));

  // submodule systolic_array_0_2
  mkMacSystolic systolic_array_0_2(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_0_2_set_a_a_in),
				   .set_b_b_in(systolic_array_0_2_set_b_b_in),
				   .set_c_c_in(systolic_array_0_2_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_0_2_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_0_2_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_0_2_EN_set_state),
				   .EN_set_a(systolic_array_0_2_EN_set_a),
				   .EN_set_b(systolic_array_0_2_EN_set_b),
				   .EN_set_c(systolic_array_0_2_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_0_2_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_0_2_RDY_set_a),
				   .RDY_set_b(systolic_array_0_2_RDY_set_b),
				   .RDY_set_c(systolic_array_0_2_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_0_2_RDY_set_s1_or_s2),
				   .get_result(systolic_array_0_2_get_result),
				   .RDY_get_result(systolic_array_0_2_RDY_get_result),
				   .get_a(systolic_array_0_2_get_a),
				   .RDY_get_a(systolic_array_0_2_RDY_get_a),
				   .get_b(systolic_array_0_2_get_b),
				   .RDY_get_b(systolic_array_0_2_RDY_get_b),
				   .get_s1_or_s2(systolic_array_0_2_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_0_2_RDY_get_s1_or_s2));

  // submodule systolic_array_0_3
  mkMacSystolic systolic_array_0_3(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_0_3_set_a_a_in),
				   .set_b_b_in(systolic_array_0_3_set_b_b_in),
				   .set_c_c_in(systolic_array_0_3_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_0_3_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_0_3_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_0_3_EN_set_state),
				   .EN_set_a(systolic_array_0_3_EN_set_a),
				   .EN_set_b(systolic_array_0_3_EN_set_b),
				   .EN_set_c(systolic_array_0_3_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_0_3_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_0_3_RDY_set_a),
				   .RDY_set_b(systolic_array_0_3_RDY_set_b),
				   .RDY_set_c(systolic_array_0_3_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_0_3_RDY_set_s1_or_s2),
				   .get_result(systolic_array_0_3_get_result),
				   .RDY_get_result(systolic_array_0_3_RDY_get_result),
				   .get_a(),
				   .RDY_get_a(),
				   .get_b(systolic_array_0_3_get_b),
				   .RDY_get_b(systolic_array_0_3_RDY_get_b),
				   .get_s1_or_s2(systolic_array_0_3_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_0_3_RDY_get_s1_or_s2));

  // submodule systolic_array_1_0
  mkMacSystolic systolic_array_1_0(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_1_0_set_a_a_in),
				   .set_b_b_in(systolic_array_1_0_set_b_b_in),
				   .set_c_c_in(systolic_array_1_0_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_1_0_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_1_0_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_1_0_EN_set_state),
				   .EN_set_a(systolic_array_1_0_EN_set_a),
				   .EN_set_b(systolic_array_1_0_EN_set_b),
				   .EN_set_c(systolic_array_1_0_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_1_0_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_1_0_RDY_set_a),
				   .RDY_set_b(systolic_array_1_0_RDY_set_b),
				   .RDY_set_c(systolic_array_1_0_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_1_0_RDY_set_s1_or_s2),
				   .get_result(systolic_array_1_0_get_result),
				   .RDY_get_result(systolic_array_1_0_RDY_get_result),
				   .get_a(systolic_array_1_0_get_a),
				   .RDY_get_a(systolic_array_1_0_RDY_get_a),
				   .get_b(systolic_array_1_0_get_b),
				   .RDY_get_b(systolic_array_1_0_RDY_get_b),
				   .get_s1_or_s2(systolic_array_1_0_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_1_0_RDY_get_s1_or_s2));

  // submodule systolic_array_1_1
  mkMacSystolic systolic_array_1_1(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_1_1_set_a_a_in),
				   .set_b_b_in(systolic_array_1_1_set_b_b_in),
				   .set_c_c_in(systolic_array_1_1_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_1_1_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_1_1_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_1_1_EN_set_state),
				   .EN_set_a(systolic_array_1_1_EN_set_a),
				   .EN_set_b(systolic_array_1_1_EN_set_b),
				   .EN_set_c(systolic_array_1_1_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_1_1_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_1_1_RDY_set_a),
				   .RDY_set_b(systolic_array_1_1_RDY_set_b),
				   .RDY_set_c(systolic_array_1_1_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_1_1_RDY_set_s1_or_s2),
				   .get_result(systolic_array_1_1_get_result),
				   .RDY_get_result(systolic_array_1_1_RDY_get_result),
				   .get_a(systolic_array_1_1_get_a),
				   .RDY_get_a(systolic_array_1_1_RDY_get_a),
				   .get_b(systolic_array_1_1_get_b),
				   .RDY_get_b(systolic_array_1_1_RDY_get_b),
				   .get_s1_or_s2(systolic_array_1_1_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_1_1_RDY_get_s1_or_s2));

  // submodule systolic_array_1_2
  mkMacSystolic systolic_array_1_2(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_1_2_set_a_a_in),
				   .set_b_b_in(systolic_array_1_2_set_b_b_in),
				   .set_c_c_in(systolic_array_1_2_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_1_2_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_1_2_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_1_2_EN_set_state),
				   .EN_set_a(systolic_array_1_2_EN_set_a),
				   .EN_set_b(systolic_array_1_2_EN_set_b),
				   .EN_set_c(systolic_array_1_2_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_1_2_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_1_2_RDY_set_a),
				   .RDY_set_b(systolic_array_1_2_RDY_set_b),
				   .RDY_set_c(systolic_array_1_2_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_1_2_RDY_set_s1_or_s2),
				   .get_result(systolic_array_1_2_get_result),
				   .RDY_get_result(systolic_array_1_2_RDY_get_result),
				   .get_a(systolic_array_1_2_get_a),
				   .RDY_get_a(systolic_array_1_2_RDY_get_a),
				   .get_b(systolic_array_1_2_get_b),
				   .RDY_get_b(systolic_array_1_2_RDY_get_b),
				   .get_s1_or_s2(systolic_array_1_2_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_1_2_RDY_get_s1_or_s2));

  // submodule systolic_array_1_3
  mkMacSystolic systolic_array_1_3(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_1_3_set_a_a_in),
				   .set_b_b_in(systolic_array_1_3_set_b_b_in),
				   .set_c_c_in(systolic_array_1_3_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_1_3_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_1_3_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_1_3_EN_set_state),
				   .EN_set_a(systolic_array_1_3_EN_set_a),
				   .EN_set_b(systolic_array_1_3_EN_set_b),
				   .EN_set_c(systolic_array_1_3_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_1_3_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_1_3_RDY_set_a),
				   .RDY_set_b(systolic_array_1_3_RDY_set_b),
				   .RDY_set_c(systolic_array_1_3_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_1_3_RDY_set_s1_or_s2),
				   .get_result(systolic_array_1_3_get_result),
				   .RDY_get_result(systolic_array_1_3_RDY_get_result),
				   .get_a(),
				   .RDY_get_a(),
				   .get_b(systolic_array_1_3_get_b),
				   .RDY_get_b(systolic_array_1_3_RDY_get_b),
				   .get_s1_or_s2(systolic_array_1_3_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_1_3_RDY_get_s1_or_s2));

  // submodule systolic_array_2_0
  mkMacSystolic systolic_array_2_0(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_2_0_set_a_a_in),
				   .set_b_b_in(systolic_array_2_0_set_b_b_in),
				   .set_c_c_in(systolic_array_2_0_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_2_0_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_2_0_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_2_0_EN_set_state),
				   .EN_set_a(systolic_array_2_0_EN_set_a),
				   .EN_set_b(systolic_array_2_0_EN_set_b),
				   .EN_set_c(systolic_array_2_0_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_2_0_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_2_0_RDY_set_a),
				   .RDY_set_b(systolic_array_2_0_RDY_set_b),
				   .RDY_set_c(systolic_array_2_0_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_2_0_RDY_set_s1_or_s2),
				   .get_result(systolic_array_2_0_get_result),
				   .RDY_get_result(systolic_array_2_0_RDY_get_result),
				   .get_a(systolic_array_2_0_get_a),
				   .RDY_get_a(systolic_array_2_0_RDY_get_a),
				   .get_b(systolic_array_2_0_get_b),
				   .RDY_get_b(systolic_array_2_0_RDY_get_b),
				   .get_s1_or_s2(systolic_array_2_0_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_2_0_RDY_get_s1_or_s2));

  // submodule systolic_array_2_1
  mkMacSystolic systolic_array_2_1(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_2_1_set_a_a_in),
				   .set_b_b_in(systolic_array_2_1_set_b_b_in),
				   .set_c_c_in(systolic_array_2_1_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_2_1_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_2_1_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_2_1_EN_set_state),
				   .EN_set_a(systolic_array_2_1_EN_set_a),
				   .EN_set_b(systolic_array_2_1_EN_set_b),
				   .EN_set_c(systolic_array_2_1_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_2_1_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_2_1_RDY_set_a),
				   .RDY_set_b(systolic_array_2_1_RDY_set_b),
				   .RDY_set_c(systolic_array_2_1_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_2_1_RDY_set_s1_or_s2),
				   .get_result(systolic_array_2_1_get_result),
				   .RDY_get_result(systolic_array_2_1_RDY_get_result),
				   .get_a(systolic_array_2_1_get_a),
				   .RDY_get_a(systolic_array_2_1_RDY_get_a),
				   .get_b(systolic_array_2_1_get_b),
				   .RDY_get_b(systolic_array_2_1_RDY_get_b),
				   .get_s1_or_s2(systolic_array_2_1_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_2_1_RDY_get_s1_or_s2));

  // submodule systolic_array_2_2
  mkMacSystolic systolic_array_2_2(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_2_2_set_a_a_in),
				   .set_b_b_in(systolic_array_2_2_set_b_b_in),
				   .set_c_c_in(systolic_array_2_2_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_2_2_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_2_2_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_2_2_EN_set_state),
				   .EN_set_a(systolic_array_2_2_EN_set_a),
				   .EN_set_b(systolic_array_2_2_EN_set_b),
				   .EN_set_c(systolic_array_2_2_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_2_2_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_2_2_RDY_set_a),
				   .RDY_set_b(systolic_array_2_2_RDY_set_b),
				   .RDY_set_c(systolic_array_2_2_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_2_2_RDY_set_s1_or_s2),
				   .get_result(systolic_array_2_2_get_result),
				   .RDY_get_result(systolic_array_2_2_RDY_get_result),
				   .get_a(systolic_array_2_2_get_a),
				   .RDY_get_a(systolic_array_2_2_RDY_get_a),
				   .get_b(systolic_array_2_2_get_b),
				   .RDY_get_b(systolic_array_2_2_RDY_get_b),
				   .get_s1_or_s2(systolic_array_2_2_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_2_2_RDY_get_s1_or_s2));

  // submodule systolic_array_2_3
  mkMacSystolic systolic_array_2_3(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_2_3_set_a_a_in),
				   .set_b_b_in(systolic_array_2_3_set_b_b_in),
				   .set_c_c_in(systolic_array_2_3_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_2_3_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_2_3_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_2_3_EN_set_state),
				   .EN_set_a(systolic_array_2_3_EN_set_a),
				   .EN_set_b(systolic_array_2_3_EN_set_b),
				   .EN_set_c(systolic_array_2_3_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_2_3_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_2_3_RDY_set_a),
				   .RDY_set_b(systolic_array_2_3_RDY_set_b),
				   .RDY_set_c(systolic_array_2_3_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_2_3_RDY_set_s1_or_s2),
				   .get_result(systolic_array_2_3_get_result),
				   .RDY_get_result(systolic_array_2_3_RDY_get_result),
				   .get_a(),
				   .RDY_get_a(),
				   .get_b(systolic_array_2_3_get_b),
				   .RDY_get_b(systolic_array_2_3_RDY_get_b),
				   .get_s1_or_s2(systolic_array_2_3_get_s1_or_s2),
				   .RDY_get_s1_or_s2(systolic_array_2_3_RDY_get_s1_or_s2));

  // submodule systolic_array_3_0
  mkMacSystolic systolic_array_3_0(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_3_0_set_a_a_in),
				   .set_b_b_in(systolic_array_3_0_set_b_b_in),
				   .set_c_c_in(systolic_array_3_0_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_3_0_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_3_0_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_3_0_EN_set_state),
				   .EN_set_a(systolic_array_3_0_EN_set_a),
				   .EN_set_b(systolic_array_3_0_EN_set_b),
				   .EN_set_c(systolic_array_3_0_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_3_0_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_3_0_RDY_set_a),
				   .RDY_set_b(systolic_array_3_0_RDY_set_b),
				   .RDY_set_c(systolic_array_3_0_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_3_0_RDY_set_s1_or_s2),
				   .get_result(systolic_array_3_0_get_result),
				   .RDY_get_result(systolic_array_3_0_RDY_get_result),
				   .get_a(systolic_array_3_0_get_a),
				   .RDY_get_a(systolic_array_3_0_RDY_get_a),
				   .get_b(),
				   .RDY_get_b(),
				   .get_s1_or_s2(),
				   .RDY_get_s1_or_s2());

  // submodule systolic_array_3_1
  mkMacSystolic systolic_array_3_1(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_3_1_set_a_a_in),
				   .set_b_b_in(systolic_array_3_1_set_b_b_in),
				   .set_c_c_in(systolic_array_3_1_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_3_1_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_3_1_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_3_1_EN_set_state),
				   .EN_set_a(systolic_array_3_1_EN_set_a),
				   .EN_set_b(systolic_array_3_1_EN_set_b),
				   .EN_set_c(systolic_array_3_1_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_3_1_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_3_1_RDY_set_a),
				   .RDY_set_b(systolic_array_3_1_RDY_set_b),
				   .RDY_set_c(systolic_array_3_1_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_3_1_RDY_set_s1_or_s2),
				   .get_result(systolic_array_3_1_get_result),
				   .RDY_get_result(systolic_array_3_1_RDY_get_result),
				   .get_a(systolic_array_3_1_get_a),
				   .RDY_get_a(systolic_array_3_1_RDY_get_a),
				   .get_b(),
				   .RDY_get_b(),
				   .get_s1_or_s2(),
				   .RDY_get_s1_or_s2());

  // submodule systolic_array_3_2
  mkMacSystolic systolic_array_3_2(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_3_2_set_a_a_in),
				   .set_b_b_in(systolic_array_3_2_set_b_b_in),
				   .set_c_c_in(systolic_array_3_2_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_3_2_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_3_2_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_3_2_EN_set_state),
				   .EN_set_a(systolic_array_3_2_EN_set_a),
				   .EN_set_b(systolic_array_3_2_EN_set_b),
				   .EN_set_c(systolic_array_3_2_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_3_2_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_3_2_RDY_set_a),
				   .RDY_set_b(systolic_array_3_2_RDY_set_b),
				   .RDY_set_c(systolic_array_3_2_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_3_2_RDY_set_s1_or_s2),
				   .get_result(systolic_array_3_2_get_result),
				   .RDY_get_result(systolic_array_3_2_RDY_get_result),
				   .get_a(systolic_array_3_2_get_a),
				   .RDY_get_a(systolic_array_3_2_RDY_get_a),
				   .get_b(),
				   .RDY_get_b(),
				   .get_s1_or_s2(),
				   .RDY_get_s1_or_s2());

  // submodule systolic_array_3_3
  mkMacSystolic systolic_array_3_3(.CLK(CLK),
				   .RST_N(RST_N),
				   .set_a_a_in(systolic_array_3_3_set_a_a_in),
				   .set_b_b_in(systolic_array_3_3_set_b_b_in),
				   .set_c_c_in(systolic_array_3_3_set_c_c_in),
				   .set_s1_or_s2_s1_or_s2_in(systolic_array_3_3_set_s1_or_s2_s1_or_s2_in),
				   .set_state_transfer_b_state(systolic_array_3_3_set_state_transfer_b_state),
				   .EN_set_state(systolic_array_3_3_EN_set_state),
				   .EN_set_a(systolic_array_3_3_EN_set_a),
				   .EN_set_b(systolic_array_3_3_EN_set_b),
				   .EN_set_c(systolic_array_3_3_EN_set_c),
				   .EN_set_s1_or_s2(systolic_array_3_3_EN_set_s1_or_s2),
				   .RDY_set_state(),
				   .RDY_set_a(systolic_array_3_3_RDY_set_a),
				   .RDY_set_b(systolic_array_3_3_RDY_set_b),
				   .RDY_set_c(systolic_array_3_3_RDY_set_c),
				   .RDY_set_s1_or_s2(systolic_array_3_3_RDY_set_s1_or_s2),
				   .get_result(systolic_array_3_3_get_result),
				   .RDY_get_result(systolic_array_3_3_RDY_get_result),
				   .get_a(),
				   .RDY_get_a(),
				   .get_b(),
				   .RDY_get_b(),
				   .get_s1_or_s2(),
				   .RDY_get_s1_or_s2());

  // rule RL_count_up
  assign CAN_FIRE_RL_count_up = 1'd1 ;
  assign WILL_FIRE_RL_count_up = 1'd1 ;

  // rule RL_shift_b_row1
  assign CAN_FIRE_RL_shift_b_row1 =
	     systolic_array_0_0_RDY_get_b &&
	     systolic_array_0_1_RDY_get_b_AND_systolic_arra_ETC___d16 ;
  assign WILL_FIRE_RL_shift_b_row1 = CAN_FIRE_RL_shift_b_row1 ;

  // rule RL_shift_b_row2
  assign CAN_FIRE_RL_shift_b_row2 =
	     systolic_array_1_0_RDY_get_b &&
	     systolic_array_1_1_RDY_get_b__3_AND_systolic_a_ETC___d35 ;
  assign WILL_FIRE_RL_shift_b_row2 = CAN_FIRE_RL_shift_b_row2 ;

  // rule RL_shift_b_row3
  assign CAN_FIRE_RL_shift_b_row3 =
	     systolic_array_2_0_RDY_get_b &&
	     systolic_array_2_1_RDY_get_b__2_AND_systolic_a_ETC___d54 ;
  assign WILL_FIRE_RL_shift_b_row3 = CAN_FIRE_RL_shift_b_row3 ;

  // rule RL_shift_c_row1
  assign CAN_FIRE_RL_shift_c_row1 =
	     systolic_array_0_0_RDY_get_s1_or_s2 &&
	     systolic_array_0_1_RDY_get_s1_or_s2 &&
	     systolic_array_0_2_RDY_get_s1_or_s2 &&
	     systolic_array_0_3_RDY_get_s1_or_s2__3_AND_sys_ETC___d87 ;
  assign WILL_FIRE_RL_shift_c_row1 =
	     CAN_FIRE_RL_shift_c_row1 && !EN_initialise_systolic ;

  // rule RL_shift_c_row2
  assign CAN_FIRE_RL_shift_c_row2 =
	     systolic_array_1_0_RDY_get_s1_or_s2 &&
	     systolic_array_1_1_RDY_get_s1_or_s2 &&
	     systolic_array_1_2_RDY_get_s1_or_s2 &&
	     systolic_array_1_3_RDY_get_s1_or_s2__02_AND_sy_ETC___d126 ;
  assign WILL_FIRE_RL_shift_c_row2 =
	     CAN_FIRE_RL_shift_c_row2 && !EN_initialise_systolic ;

  // rule RL_shift_c_row3
  assign CAN_FIRE_RL_shift_c_row3 =
	     systolic_array_2_0_RDY_get_s1_or_s2 &&
	     systolic_array_2_1_RDY_get_s1_or_s2 &&
	     systolic_array_2_2_RDY_get_s1_or_s2 &&
	     systolic_array_2_3_RDY_get_s1_or_s2__41_AND_sy_ETC___d165 ;
  assign WILL_FIRE_RL_shift_c_row3 =
	     CAN_FIRE_RL_shift_c_row3 && !EN_initialise_systolic ;

  // rule RL_shift_a_column1
  assign CAN_FIRE_RL_shift_a_column1 =
	     systolic_array_0_0_RDY_get_a &&
	     systolic_array_1_0_RDY_get_a__78_AND_systolic__ETC___d190 ;
  assign WILL_FIRE_RL_shift_a_column1 =
	     CAN_FIRE_RL_shift_a_column1 && !EN_initialise_systolic ;

  // rule RL_shift_a_column2
  assign CAN_FIRE_RL_shift_a_column2 =
	     systolic_array_0_1_RDY_get_a &&
	     systolic_array_1_1_RDY_get_a__97_AND_systolic__ETC___d209 ;
  assign WILL_FIRE_RL_shift_a_column2 =
	     CAN_FIRE_RL_shift_a_column2 && !EN_initialise_systolic ;

  // rule RL_shift_a_column3
  assign CAN_FIRE_RL_shift_a_column3 =
	     systolic_array_0_2_RDY_get_a &&
	     systolic_array_1_2_RDY_get_a__16_AND_systolic__ETC___d228 ;
  assign WILL_FIRE_RL_shift_a_column3 =
	     CAN_FIRE_RL_shift_a_column3 && !EN_initialise_systolic ;

  // register counter
  assign counter_D_IN = counter + 32'd1 ;
  assign counter_EN = 1'd1 ;

  // submodule systolic_array_0_0
  assign systolic_array_0_0_set_a_a_in = set_A_matrix_a_matrix[15:0] ;
  assign systolic_array_0_0_set_b_b_in = set_B_matrix_b_matrix[15:0] ;
  assign systolic_array_0_0_set_c_c_in =
	     EN_set_C_row1 ? set_C_row1_c_val : 32'b0 ;
  assign systolic_array_0_0_set_s1_or_s2_s1_or_s2_in =
	     EN_set_s1_or_s2_row1 ?
	       set_s1_or_s2_row1_s1_or_s2_in :
	       initialise_systolic_s1_or_s2_in ;
  assign systolic_array_0_0_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_0_0_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_0_0_EN_set_a = EN_set_A_matrix ;
  assign systolic_array_0_0_EN_set_b = EN_set_B_matrix ;
  assign systolic_array_0_0_EN_set_c =
	     EN_set_C_row1 || EN_initialise_systolic ;
  assign systolic_array_0_0_EN_set_s1_or_s2 =
	     EN_set_s1_or_s2_row1 || EN_initialise_systolic ;

  // submodule systolic_array_0_1
  assign systolic_array_0_1_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column1 ? systolic_array_0_0_get_a : 16'b0 ;
  assign systolic_array_0_1_set_b_b_in = set_B_matrix_b_matrix[31:16] ;
  assign systolic_array_0_1_set_c_c_in =
	     EN_set_C_row1 ? set_C_row1_c_val : 32'b0 ;
  assign systolic_array_0_1_set_s1_or_s2_s1_or_s2_in =
	     systolic_array_0_0_set_s1_or_s2_s1_or_s2_in ;
  assign systolic_array_0_1_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_0_1_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_0_1_EN_set_a =
	     WILL_FIRE_RL_shift_a_column1 || EN_initialise_systolic ;
  assign systolic_array_0_1_EN_set_b = EN_set_B_matrix ;
  assign systolic_array_0_1_EN_set_c =
	     EN_set_C_row1 || EN_initialise_systolic ;
  assign systolic_array_0_1_EN_set_s1_or_s2 =
	     EN_set_s1_or_s2_row1 || EN_initialise_systolic ;

  // submodule systolic_array_0_2
  assign systolic_array_0_2_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column2 ? systolic_array_0_1_get_a : 16'b0 ;
  assign systolic_array_0_2_set_b_b_in = set_B_matrix_b_matrix[47:32] ;
  assign systolic_array_0_2_set_c_c_in =
	     EN_set_C_row1 ? set_C_row1_c_val : 32'b0 ;
  assign systolic_array_0_2_set_s1_or_s2_s1_or_s2_in =
	     systolic_array_0_0_set_s1_or_s2_s1_or_s2_in ;
  assign systolic_array_0_2_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_0_2_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_0_2_EN_set_a =
	     WILL_FIRE_RL_shift_a_column2 || EN_initialise_systolic ;
  assign systolic_array_0_2_EN_set_b = EN_set_B_matrix ;
  assign systolic_array_0_2_EN_set_c =
	     EN_set_C_row1 || EN_initialise_systolic ;
  assign systolic_array_0_2_EN_set_s1_or_s2 =
	     EN_set_s1_or_s2_row1 || EN_initialise_systolic ;

  // submodule systolic_array_0_3
  assign systolic_array_0_3_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column3 ? systolic_array_0_2_get_a : 16'b0 ;
  assign systolic_array_0_3_set_b_b_in = set_B_matrix_b_matrix[63:48] ;
  assign systolic_array_0_3_set_c_c_in =
	     EN_set_C_row1 ? set_C_row1_c_val : 32'b0 ;
  assign systolic_array_0_3_set_s1_or_s2_s1_or_s2_in =
	     systolic_array_0_0_set_s1_or_s2_s1_or_s2_in ;
  assign systolic_array_0_3_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_0_3_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_0_3_EN_set_a =
	     WILL_FIRE_RL_shift_a_column3 || EN_initialise_systolic ;
  assign systolic_array_0_3_EN_set_b = EN_set_B_matrix ;
  assign systolic_array_0_3_EN_set_c =
	     EN_set_C_row1 || EN_initialise_systolic ;
  assign systolic_array_0_3_EN_set_s1_or_s2 =
	     EN_set_s1_or_s2_row1 || EN_initialise_systolic ;

  // submodule systolic_array_1_0
  assign systolic_array_1_0_set_a_a_in = set_A_matrix_a_matrix[31:16] ;
  assign systolic_array_1_0_set_b_b_in = systolic_array_0_0_get_b ;
  assign systolic_array_1_0_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row1 ?
	       systolic_array_0_0_get_result :
	       32'b0 ;
  assign systolic_array_1_0_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_0_0_get_s1_or_s2 ;
  assign systolic_array_1_0_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_1_0_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_1_0_EN_set_a = EN_set_A_matrix ;
  assign systolic_array_1_0_EN_set_b = CAN_FIRE_RL_shift_b_row1 ;
  assign systolic_array_1_0_EN_set_c =
	     WILL_FIRE_RL_shift_c_row1 || EN_initialise_systolic ;
  assign systolic_array_1_0_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row1 ;

  // submodule systolic_array_1_1
  assign systolic_array_1_1_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column1 ? systolic_array_1_0_get_a : 16'b0 ;
  assign systolic_array_1_1_set_b_b_in = systolic_array_0_1_get_b ;
  assign systolic_array_1_1_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row1 ?
	       systolic_array_0_1_get_result :
	       32'b0 ;
  assign systolic_array_1_1_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_0_1_get_s1_or_s2 ;
  assign systolic_array_1_1_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_1_1_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_1_1_EN_set_a =
	     WILL_FIRE_RL_shift_a_column1 || EN_initialise_systolic ;
  assign systolic_array_1_1_EN_set_b = CAN_FIRE_RL_shift_b_row1 ;
  assign systolic_array_1_1_EN_set_c =
	     WILL_FIRE_RL_shift_c_row1 || EN_initialise_systolic ;
  assign systolic_array_1_1_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row1 ;

  // submodule systolic_array_1_2
  assign systolic_array_1_2_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column2 ? systolic_array_1_1_get_a : 16'b0 ;
  assign systolic_array_1_2_set_b_b_in = systolic_array_0_2_get_b ;
  assign systolic_array_1_2_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row1 ?
	       systolic_array_0_2_get_result :
	       32'b0 ;
  assign systolic_array_1_2_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_0_2_get_s1_or_s2 ;
  assign systolic_array_1_2_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_1_2_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_1_2_EN_set_a =
	     WILL_FIRE_RL_shift_a_column2 || EN_initialise_systolic ;
  assign systolic_array_1_2_EN_set_b = CAN_FIRE_RL_shift_b_row1 ;
  assign systolic_array_1_2_EN_set_c =
	     WILL_FIRE_RL_shift_c_row1 || EN_initialise_systolic ;
  assign systolic_array_1_2_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row1 ;

  // submodule systolic_array_1_3
  assign systolic_array_1_3_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column3 ? systolic_array_1_2_get_a : 16'b0 ;
  assign systolic_array_1_3_set_b_b_in = systolic_array_0_3_get_b ;
  assign systolic_array_1_3_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row1 ?
	       systolic_array_0_3_get_result :
	       32'b0 ;
  assign systolic_array_1_3_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_0_3_get_s1_or_s2 ;
  assign systolic_array_1_3_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_1_3_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_1_3_EN_set_a =
	     WILL_FIRE_RL_shift_a_column3 || EN_initialise_systolic ;
  assign systolic_array_1_3_EN_set_b = CAN_FIRE_RL_shift_b_row1 ;
  assign systolic_array_1_3_EN_set_c =
	     WILL_FIRE_RL_shift_c_row1 || EN_initialise_systolic ;
  assign systolic_array_1_3_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row1 ;

  // submodule systolic_array_2_0
  assign systolic_array_2_0_set_a_a_in = set_A_matrix_a_matrix[47:32] ;
  assign systolic_array_2_0_set_b_b_in = systolic_array_1_0_get_b ;
  assign systolic_array_2_0_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row2 ?
	       systolic_array_1_0_get_result :
	       32'b0 ;
  assign systolic_array_2_0_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_1_0_get_s1_or_s2 ;
  assign systolic_array_2_0_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_2_0_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_2_0_EN_set_a = EN_set_A_matrix ;
  assign systolic_array_2_0_EN_set_b = CAN_FIRE_RL_shift_b_row2 ;
  assign systolic_array_2_0_EN_set_c =
	     WILL_FIRE_RL_shift_c_row2 || EN_initialise_systolic ;
  assign systolic_array_2_0_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row2 ;

  // submodule systolic_array_2_1
  assign systolic_array_2_1_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column1 ? systolic_array_2_0_get_a : 16'b0 ;
  assign systolic_array_2_1_set_b_b_in = systolic_array_1_1_get_b ;
  assign systolic_array_2_1_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row2 ?
	       systolic_array_1_1_get_result :
	       32'b0 ;
  assign systolic_array_2_1_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_1_1_get_s1_or_s2 ;
  assign systolic_array_2_1_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_2_1_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_2_1_EN_set_a =
	     WILL_FIRE_RL_shift_a_column1 || EN_initialise_systolic ;
  assign systolic_array_2_1_EN_set_b = CAN_FIRE_RL_shift_b_row2 ;
  assign systolic_array_2_1_EN_set_c =
	     WILL_FIRE_RL_shift_c_row2 || EN_initialise_systolic ;
  assign systolic_array_2_1_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row2 ;

  // submodule systolic_array_2_2
  assign systolic_array_2_2_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column2 ? systolic_array_2_1_get_a : 16'b0 ;
  assign systolic_array_2_2_set_b_b_in = systolic_array_1_2_get_b ;
  assign systolic_array_2_2_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row2 ?
	       systolic_array_1_2_get_result :
	       32'b0 ;
  assign systolic_array_2_2_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_1_2_get_s1_or_s2 ;
  assign systolic_array_2_2_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_2_2_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_2_2_EN_set_a =
	     WILL_FIRE_RL_shift_a_column2 || EN_initialise_systolic ;
  assign systolic_array_2_2_EN_set_b = CAN_FIRE_RL_shift_b_row2 ;
  assign systolic_array_2_2_EN_set_c =
	     WILL_FIRE_RL_shift_c_row2 || EN_initialise_systolic ;
  assign systolic_array_2_2_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row2 ;

  // submodule systolic_array_2_3
  assign systolic_array_2_3_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column3 ? systolic_array_2_2_get_a : 16'b0 ;
  assign systolic_array_2_3_set_b_b_in = systolic_array_1_3_get_b ;
  assign systolic_array_2_3_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row2 ?
	       systolic_array_1_3_get_result :
	       32'b0 ;
  assign systolic_array_2_3_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_1_3_get_s1_or_s2 ;
  assign systolic_array_2_3_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_2_3_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_2_3_EN_set_a =
	     WILL_FIRE_RL_shift_a_column3 || EN_initialise_systolic ;
  assign systolic_array_2_3_EN_set_b = CAN_FIRE_RL_shift_b_row2 ;
  assign systolic_array_2_3_EN_set_c =
	     WILL_FIRE_RL_shift_c_row2 || EN_initialise_systolic ;
  assign systolic_array_2_3_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row2 ;

  // submodule systolic_array_3_0
  assign systolic_array_3_0_set_a_a_in = set_A_matrix_a_matrix[63:48] ;
  assign systolic_array_3_0_set_b_b_in = systolic_array_2_0_get_b ;
  assign systolic_array_3_0_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row3 ?
	       systolic_array_2_0_get_result :
	       32'b0 ;
  assign systolic_array_3_0_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_2_0_get_s1_or_s2 ;
  assign systolic_array_3_0_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_3_0_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_3_0_EN_set_a = EN_set_A_matrix ;
  assign systolic_array_3_0_EN_set_b = CAN_FIRE_RL_shift_b_row3 ;
  assign systolic_array_3_0_EN_set_c =
	     WILL_FIRE_RL_shift_c_row3 || EN_initialise_systolic ;
  assign systolic_array_3_0_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row3 ;

  // submodule systolic_array_3_1
  assign systolic_array_3_1_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column1 ? systolic_array_3_0_get_a : 16'b0 ;
  assign systolic_array_3_1_set_b_b_in = systolic_array_2_1_get_b ;
  assign systolic_array_3_1_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row3 ?
	       systolic_array_2_1_get_result :
	       32'b0 ;
  assign systolic_array_3_1_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_2_1_get_s1_or_s2 ;
  assign systolic_array_3_1_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_3_1_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_3_1_EN_set_a =
	     WILL_FIRE_RL_shift_a_column1 || EN_initialise_systolic ;
  assign systolic_array_3_1_EN_set_b = CAN_FIRE_RL_shift_b_row3 ;
  assign systolic_array_3_1_EN_set_c =
	     WILL_FIRE_RL_shift_c_row3 || EN_initialise_systolic ;
  assign systolic_array_3_1_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row3 ;

  // submodule systolic_array_3_2
  assign systolic_array_3_2_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column2 ? systolic_array_3_1_get_a : 16'b0 ;
  assign systolic_array_3_2_set_b_b_in = systolic_array_2_2_get_b ;
  assign systolic_array_3_2_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row3 ?
	       systolic_array_2_2_get_result :
	       32'b0 ;
  assign systolic_array_3_2_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_2_2_get_s1_or_s2 ;
  assign systolic_array_3_2_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_3_2_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_3_2_EN_set_a =
	     WILL_FIRE_RL_shift_a_column2 || EN_initialise_systolic ;
  assign systolic_array_3_2_EN_set_b = CAN_FIRE_RL_shift_b_row3 ;
  assign systolic_array_3_2_EN_set_c =
	     WILL_FIRE_RL_shift_c_row3 || EN_initialise_systolic ;
  assign systolic_array_3_2_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row3 ;

  // submodule systolic_array_3_3
  assign systolic_array_3_3_set_a_a_in =
	     WILL_FIRE_RL_shift_a_column3 ? systolic_array_3_2_get_a : 16'b0 ;
  assign systolic_array_3_3_set_b_b_in = systolic_array_2_3_get_b ;
  assign systolic_array_3_3_set_c_c_in =
	     WILL_FIRE_RL_shift_c_row3 ?
	       systolic_array_2_3_get_result :
	       32'b0 ;
  assign systolic_array_3_3_set_s1_or_s2_s1_or_s2_in =
	     EN_initialise_systolic ?
	       initialise_systolic_s1_or_s2_in :
	       systolic_array_2_3_get_s1_or_s2 ;
  assign systolic_array_3_3_set_state_transfer_b_state =
	     set_state_systolic_state_in ;
  assign systolic_array_3_3_EN_set_state = EN_set_state_systolic ;
  assign systolic_array_3_3_EN_set_a =
	     WILL_FIRE_RL_shift_a_column3 || EN_initialise_systolic ;
  assign systolic_array_3_3_EN_set_b = CAN_FIRE_RL_shift_b_row3 ;
  assign systolic_array_3_3_EN_set_c =
	     WILL_FIRE_RL_shift_c_row3 || EN_initialise_systolic ;
  assign systolic_array_3_3_EN_set_s1_or_s2 =
	     EN_initialise_systolic || WILL_FIRE_RL_shift_c_row3 ;

  // remaining internal signals
  assign systolic_array_0_1_RDY_get_b_AND_systolic_arra_ETC___d16 =
	     systolic_array_0_1_RDY_get_b && systolic_array_0_2_RDY_get_b &&
	     systolic_array_0_3_RDY_get_b &&
	     systolic_array_1_0_RDY_set_b &&
	     systolic_array_1_1_RDY_set_b &&
	     systolic_array_1_2_RDY_set_b &&
	     systolic_array_1_3_RDY_set_b ;
  assign systolic_array_0_1_RDY_set_s1_or_s2__61_AND_sy_ETC___d307 =
	     systolic_array_0_1_RDY_set_s1_or_s2 &&
	     systolic_array_0_2_RDY_set_s1_or_s2 &&
	     systolic_array_0_3_RDY_set_s1_or_s2 &&
	     systolic_array_1_0_RDY_set_s1_or_s2 &&
	     systolic_array_1_1_RDY_set_s1_or_s2 &&
	     systolic_array_1_2_RDY_set_s1_or_s2 &&
	     systolic_array_1_3_RDY_set_s1_or_s2__1_AND_sys_ETC___d301 ;
  assign systolic_array_0_3_RDY_get_s1_or_s2__3_AND_sys_ETC___d87 =
	     systolic_array_0_3_RDY_get_s1_or_s2 &&
	     systolic_array_0_0_RDY_get_result &&
	     systolic_array_0_1_RDY_get_result &&
	     systolic_array_0_2_RDY_get_result &&
	     systolic_array_0_3_RDY_get_result &&
	     systolic_array_1_0_RDY_set_s1_or_s2 &&
	     systolic_array_1_1_RDY_set_s1_or_s2__9_AND_sys_ETC___d81 ;
  assign systolic_array_0_3_RDY_set_c__57_AND_systolic__ETC___d289 =
	     systolic_array_0_3_RDY_set_c && systolic_array_1_0_RDY_set_c &&
	     systolic_array_1_1_RDY_set_c &&
	     systolic_array_1_2_RDY_set_c &&
	     systolic_array_1_3_RDY_set_c &&
	     systolic_array_2_0_RDY_set_c &&
	     systolic_array_2_1_RDY_set_c__12_AND_systolic__ETC___d283 ;
  assign systolic_array_1_0_RDY_get_a__78_AND_systolic__ETC___d190 =
	     systolic_array_1_0_RDY_get_a && systolic_array_2_0_RDY_get_a &&
	     systolic_array_3_0_RDY_get_a &&
	     systolic_array_0_1_RDY_set_a &&
	     systolic_array_1_1_RDY_set_a &&
	     systolic_array_2_1_RDY_set_a &&
	     systolic_array_3_1_RDY_set_a ;
  assign systolic_array_1_1_RDY_get_a__97_AND_systolic__ETC___d209 =
	     systolic_array_1_1_RDY_get_a && systolic_array_2_1_RDY_get_a &&
	     systolic_array_3_1_RDY_get_a &&
	     systolic_array_0_2_RDY_set_a &&
	     systolic_array_1_2_RDY_set_a &&
	     systolic_array_2_2_RDY_set_a &&
	     systolic_array_3_2_RDY_set_a ;
  assign systolic_array_1_1_RDY_get_b__3_AND_systolic_a_ETC___d35 =
	     systolic_array_1_1_RDY_get_b && systolic_array_1_2_RDY_get_b &&
	     systolic_array_1_3_RDY_get_b &&
	     systolic_array_2_0_RDY_set_b &&
	     systolic_array_2_1_RDY_set_b &&
	     systolic_array_2_2_RDY_set_b &&
	     systolic_array_2_3_RDY_set_b ;
  assign systolic_array_1_1_RDY_set_s1_or_s2__9_AND_sys_ETC___d81 =
	     systolic_array_1_1_RDY_set_s1_or_s2 &&
	     systolic_array_1_2_RDY_set_s1_or_s2 &&
	     systolic_array_1_3_RDY_set_s1_or_s2 &&
	     systolic_array_1_0_RDY_set_c &&
	     systolic_array_1_1_RDY_set_c &&
	     systolic_array_1_2_RDY_set_c &&
	     systolic_array_1_3_RDY_set_c ;
  assign systolic_array_1_2_RDY_get_a__16_AND_systolic__ETC___d228 =
	     systolic_array_1_2_RDY_get_a && systolic_array_2_2_RDY_get_a &&
	     systolic_array_3_2_RDY_get_a &&
	     systolic_array_0_3_RDY_set_a &&
	     systolic_array_1_3_RDY_set_a &&
	     systolic_array_2_3_RDY_set_a &&
	     systolic_array_3_3_RDY_set_a ;
  assign systolic_array_1_3_RDY_get_s1_or_s2__02_AND_sy_ETC___d126 =
	     systolic_array_1_3_RDY_get_s1_or_s2 &&
	     systolic_array_1_0_RDY_get_result &&
	     systolic_array_1_1_RDY_get_result &&
	     systolic_array_1_2_RDY_get_result &&
	     systolic_array_1_3_RDY_get_result &&
	     systolic_array_2_0_RDY_set_s1_or_s2 &&
	     systolic_array_2_1_RDY_set_s1_or_s2__08_AND_sy_ETC___d120 ;
  assign systolic_array_1_3_RDY_set_a__20_AND_systolic__ETC___d271 =
	     systolic_array_1_3_RDY_set_a && systolic_array_2_1_RDY_set_a &&
	     systolic_array_2_2_RDY_set_a &&
	     systolic_array_2_3_RDY_set_a &&
	     systolic_array_3_1_RDY_set_a &&
	     systolic_array_3_2_RDY_set_a &&
	     systolic_array_3_3_RDY_set_a ;
  assign systolic_array_1_3_RDY_set_s1_or_s2__1_AND_sys_ETC___d301 =
	     systolic_array_1_3_RDY_set_s1_or_s2 &&
	     systolic_array_2_0_RDY_set_s1_or_s2 &&
	     systolic_array_2_1_RDY_set_s1_or_s2 &&
	     systolic_array_2_2_RDY_set_s1_or_s2 &&
	     systolic_array_2_3_RDY_set_s1_or_s2 &&
	     systolic_array_3_0_RDY_set_s1_or_s2 &&
	     systolic_array_3_1_RDY_set_s1_or_s2__47_AND_sy_ETC___d295 ;
  assign systolic_array_2_1_RDY_get_b__2_AND_systolic_a_ETC___d54 =
	     systolic_array_2_1_RDY_get_b && systolic_array_2_2_RDY_get_b &&
	     systolic_array_2_3_RDY_get_b &&
	     systolic_array_3_0_RDY_set_b &&
	     systolic_array_3_1_RDY_set_b &&
	     systolic_array_3_2_RDY_set_b &&
	     systolic_array_3_3_RDY_set_b ;
  assign systolic_array_2_1_RDY_set_c__12_AND_systolic__ETC___d283 =
	     systolic_array_2_1_RDY_set_c && systolic_array_2_2_RDY_set_c &&
	     systolic_array_2_3_RDY_set_c &&
	     systolic_array_3_0_RDY_set_c &&
	     systolic_array_3_1_RDY_set_c &&
	     systolic_array_3_2_RDY_set_c &&
	     systolic_array_3_3_RDY_set_c__53_AND_systolic__ETC___d277 ;
  assign systolic_array_2_1_RDY_set_s1_or_s2__08_AND_sy_ETC___d120 =
	     systolic_array_2_1_RDY_set_s1_or_s2 &&
	     systolic_array_2_2_RDY_set_s1_or_s2 &&
	     systolic_array_2_3_RDY_set_s1_or_s2 &&
	     systolic_array_2_0_RDY_set_c &&
	     systolic_array_2_1_RDY_set_c &&
	     systolic_array_2_2_RDY_set_c &&
	     systolic_array_2_3_RDY_set_c ;
  assign systolic_array_2_3_RDY_get_s1_or_s2__41_AND_sy_ETC___d165 =
	     systolic_array_2_3_RDY_get_s1_or_s2 &&
	     systolic_array_2_0_RDY_get_result &&
	     systolic_array_2_1_RDY_get_result &&
	     systolic_array_2_2_RDY_get_result &&
	     systolic_array_2_3_RDY_get_result &&
	     systolic_array_3_0_RDY_set_s1_or_s2 &&
	     systolic_array_3_1_RDY_set_s1_or_s2__47_AND_sy_ETC___d159 ;
  assign systolic_array_3_1_RDY_set_s1_or_s2__47_AND_sy_ETC___d159 =
	     systolic_array_3_1_RDY_set_s1_or_s2 &&
	     systolic_array_3_2_RDY_set_s1_or_s2 &&
	     systolic_array_3_3_RDY_set_s1_or_s2 &&
	     systolic_array_3_0_RDY_set_c &&
	     systolic_array_3_1_RDY_set_c &&
	     systolic_array_3_2_RDY_set_c &&
	     systolic_array_3_3_RDY_set_c ;
  assign systolic_array_3_1_RDY_set_s1_or_s2__47_AND_sy_ETC___d295 =
	     systolic_array_3_1_RDY_set_s1_or_s2 &&
	     systolic_array_3_2_RDY_set_s1_or_s2 &&
	     systolic_array_3_3_RDY_set_s1_or_s2 &&
	     systolic_array_0_0_RDY_set_c &&
	     systolic_array_0_1_RDY_set_c &&
	     systolic_array_0_2_RDY_set_c &&
	     systolic_array_0_3_RDY_set_c__57_AND_systolic__ETC___d289 ;
  assign systolic_array_3_3_RDY_set_c__53_AND_systolic__ETC___d277 =
	     systolic_array_3_3_RDY_set_c && systolic_array_0_1_RDY_set_a &&
	     systolic_array_0_2_RDY_set_a &&
	     systolic_array_0_3_RDY_set_a &&
	     systolic_array_1_1_RDY_set_a &&
	     systolic_array_1_2_RDY_set_a &&
	     systolic_array_1_3_RDY_set_a__20_AND_systolic__ETC___d271 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        counter <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (counter_EN) counter <= `BSV_ASSIGNMENT_DELAY counter_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    counter = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkSystolic

