/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Tue Oct 22 11:39:18 IST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "mkAdder20Bit.h"


/* Constructor */
MOD_mkAdder20Bit::MOD_mkAdder20Bit(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent), __clk_handle_0(BAD_CLOCK_HANDLE), PORT_RST_N((tUInt8)1u)
{
  symbol_count = 0u;
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkAdder20Bit::init_symbols_0()
{
}


/* Rule actions */


/* Methods */

tUInt32 MOD_mkAdder20Bit::METH_add(tUInt32 ARG_add_x, tUInt32 ARG_add_y, tUInt8 ARG_add_add_or_sub)
{
  tUInt32 DEF__theResult___snd_fst__h3670;
  tUInt8 DEF_y__h797;
  tUInt8 DEF_x__h796;
  tUInt8 DEF_y__h795;
  tUInt8 DEF_x__h794;
  tUInt8 DEF_y__h920;
  tUInt8 DEF_x__h919;
  tUInt8 DEF_y__h918;
  tUInt8 DEF_x__h917;
  tUInt8 DEF_y__h1068;
  tUInt8 DEF_x__h1067;
  tUInt8 DEF_y__h1066;
  tUInt8 DEF_x__h1065;
  tUInt8 DEF_y__h1215;
  tUInt8 DEF_x__h1214;
  tUInt8 DEF_y__h1213;
  tUInt8 DEF_x__h1212;
  tUInt8 DEF_y__h1362;
  tUInt8 DEF_x__h1361;
  tUInt8 DEF_y__h1360;
  tUInt8 DEF_x__h1359;
  tUInt8 DEF_y__h1509;
  tUInt8 DEF_x__h1508;
  tUInt8 DEF_y__h1507;
  tUInt8 DEF_x__h1506;
  tUInt8 DEF_y__h1656;
  tUInt8 DEF_x__h1655;
  tUInt8 DEF_y__h1654;
  tUInt8 DEF_x__h1653;
  tUInt8 DEF_y__h1803;
  tUInt8 DEF_x__h1802;
  tUInt8 DEF_y__h1801;
  tUInt8 DEF_x__h1800;
  tUInt8 DEF_y__h1950;
  tUInt8 DEF_x__h1949;
  tUInt8 DEF_y__h1948;
  tUInt8 DEF_x__h1947;
  tUInt8 DEF_y__h2097;
  tUInt8 DEF_x__h2096;
  tUInt8 DEF_y__h2095;
  tUInt8 DEF_x__h2094;
  tUInt8 DEF_y__h2244;
  tUInt8 DEF_x__h2243;
  tUInt8 DEF_y__h2242;
  tUInt8 DEF_x__h2241;
  tUInt8 DEF_y__h2391;
  tUInt8 DEF_x__h2390;
  tUInt8 DEF_y__h2389;
  tUInt8 DEF_x__h2388;
  tUInt8 DEF_y__h2538;
  tUInt8 DEF_x__h2537;
  tUInt8 DEF_y__h2536;
  tUInt8 DEF_x__h2535;
  tUInt8 DEF_y__h2685;
  tUInt8 DEF_x__h2684;
  tUInt8 DEF_y__h2683;
  tUInt8 DEF_x__h2682;
  tUInt8 DEF_y__h2832;
  tUInt8 DEF_x__h2831;
  tUInt8 DEF_y__h2830;
  tUInt8 DEF_x__h2829;
  tUInt8 DEF_y__h2979;
  tUInt8 DEF_x__h2978;
  tUInt8 DEF_y__h2977;
  tUInt8 DEF_x__h2976;
  tUInt8 DEF_y__h3126;
  tUInt8 DEF_x__h3125;
  tUInt8 DEF_y__h3124;
  tUInt8 DEF_x__h3123;
  tUInt8 DEF_y__h3273;
  tUInt8 DEF_x__h3272;
  tUInt8 DEF_y__h3271;
  tUInt8 DEF_x__h3270;
  tUInt8 DEF_y__h3420;
  tUInt8 DEF_x__h3419;
  tUInt8 DEF_y__h3418;
  tUInt8 DEF_x__h3417;
  tUInt8 DEF_y__h3567;
  tUInt8 DEF_x__h3566;
  tUInt8 DEF_y__h3565;
  tUInt8 DEF_x__h3564;
  tUInt8 DEF_carry_out__h43;
  tUInt8 DEF_c_in__h3548;
  tUInt8 DEF_x__h3642;
  tUInt8 DEF_c_in__h3401;
  tUInt8 DEF_x__h3495;
  tUInt8 DEF_c_in__h3254;
  tUInt8 DEF_x__h3348;
  tUInt8 DEF_c_in__h3107;
  tUInt8 DEF_x__h3201;
  tUInt8 DEF_c_in__h2960;
  tUInt8 DEF_x__h3054;
  tUInt8 DEF_c_in__h2813;
  tUInt8 DEF_x__h2907;
  tUInt8 DEF_c_in__h2666;
  tUInt8 DEF_x__h2760;
  tUInt8 DEF_c_in__h2519;
  tUInt8 DEF_x__h2613;
  tUInt8 DEF_c_in__h2372;
  tUInt8 DEF_x__h2466;
  tUInt8 DEF_c_in__h2225;
  tUInt8 DEF_x__h2319;
  tUInt8 DEF_c_in__h2078;
  tUInt8 DEF_x__h2172;
  tUInt8 DEF_c_in__h1931;
  tUInt8 DEF_x__h2025;
  tUInt8 DEF_c_in__h1784;
  tUInt8 DEF_x__h1878;
  tUInt8 DEF_c_in__h1637;
  tUInt8 DEF_x__h1731;
  tUInt8 DEF_c_in__h1490;
  tUInt8 DEF_x__h1584;
  tUInt8 DEF_c_in__h1343;
  tUInt8 DEF_x__h1437;
  tUInt8 DEF_c_in__h1196;
  tUInt8 DEF_x__h1290;
  tUInt8 DEF_c_in__h1049;
  tUInt8 DEF_x__h1143;
  tUInt8 DEF_x__h996;
  tUInt8 DEF_x__h852;
  tUInt8 DEF_x__h777;
  tUInt8 DEF_x__h899;
  tUInt8 DEF_x__h1047;
  tUInt8 DEF_x__h1194;
  tUInt8 DEF_x__h1341;
  tUInt8 DEF_x__h1488;
  tUInt8 DEF_x__h1635;
  tUInt8 DEF_x__h1782;
  tUInt8 DEF_x__h1929;
  tUInt8 DEF_x__h2076;
  tUInt8 DEF_x__h2223;
  tUInt8 DEF_x__h2370;
  tUInt8 DEF_x__h2517;
  tUInt8 DEF_x__h2664;
  tUInt8 DEF_x__h2811;
  tUInt8 DEF_x__h2958;
  tUInt8 DEF_x__h3105;
  tUInt8 DEF_x__h3252;
  tUInt8 DEF_x__h3399;
  tUInt8 DEF_x__h3546;
  tUInt8 DEF_y__h778;
  tUInt8 DEF_y__h900;
  tUInt8 DEF_y__h1048;
  tUInt8 DEF_y__h1195;
  tUInt8 DEF_y__h1342;
  tUInt8 DEF_y__h1489;
  tUInt8 DEF_y__h1636;
  tUInt8 DEF_y__h1783;
  tUInt8 DEF_y__h1930;
  tUInt8 DEF_y__h2077;
  tUInt8 DEF_y__h2224;
  tUInt8 DEF_y__h2371;
  tUInt8 DEF_y__h2518;
  tUInt8 DEF_y__h2665;
  tUInt8 DEF_y__h2812;
  tUInt8 DEF_y__h2959;
  tUInt8 DEF_y__h3106;
  tUInt8 DEF_y__h3253;
  tUInt8 DEF_y__h3400;
  tUInt32 DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2;
  tUInt8 DEF_y__h3547;
  tUInt8 DEF_c_in__h901;
  tUInt32 PORT_add;
  DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 = ARG_add_add_or_sub ? 1048575u & ~ARG_add_y : ARG_add_y;
  DEF_y__h3547 = (tUInt8)(DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 19u);
  DEF_y__h3400 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 18u));
  DEF_y__h3253 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 17u));
  DEF_y__h3106 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 16u));
  DEF_y__h2959 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 15u));
  DEF_y__h2665 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 13u));
  DEF_y__h2812 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 14u));
  DEF_y__h2518 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 12u));
  DEF_y__h2371 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 11u));
  DEF_y__h2224 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 10u));
  DEF_y__h2077 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 9u));
  DEF_y__h1930 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 8u));
  DEF_y__h1783 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 7u));
  DEF_y__h1636 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 6u));
  DEF_y__h1489 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 5u));
  DEF_y__h1195 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 3u));
  DEF_y__h1342 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 4u));
  DEF_y__h1048 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 2u));
  DEF_y__h900 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 1u));
  DEF_y__h778 = (tUInt8)((tUInt8)1u & DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2);
  DEF_x__h3399 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 18u));
  DEF_x__h3546 = (tUInt8)(ARG_add_x >> 19u);
  DEF_x__h3252 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 17u));
  DEF_x__h3105 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 16u));
  DEF_x__h2958 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 15u));
  DEF_x__h2664 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 13u));
  DEF_x__h2811 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 14u));
  DEF_x__h2517 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 12u));
  DEF_x__h2370 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 11u));
  DEF_x__h2223 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 10u));
  DEF_x__h2076 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 9u));
  DEF_x__h1929 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 8u));
  DEF_x__h1782 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 7u));
  DEF_x__h1635 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 6u));
  DEF_x__h1488 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 5u));
  DEF_x__h1194 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 3u));
  DEF_x__h1341 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 4u));
  DEF_x__h1047 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 2u));
  DEF_x__h899 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 1u));
  DEF_x__h777 = (tUInt8)((tUInt8)1u & ARG_add_x);
  DEF_x__h852 = DEF_x__h777 ^ DEF_y__h778;
  DEF_x__h996 = DEF_x__h899 ^ DEF_y__h900;
  DEF_x__h1143 = DEF_x__h1047 ^ DEF_y__h1048;
  DEF_x__h1290 = DEF_x__h1194 ^ DEF_y__h1195;
  DEF_x__h1437 = DEF_x__h1341 ^ DEF_y__h1342;
  DEF_x__h1584 = DEF_x__h1488 ^ DEF_y__h1489;
  DEF_x__h1731 = DEF_x__h1635 ^ DEF_y__h1636;
  DEF_x__h1878 = DEF_x__h1782 ^ DEF_y__h1783;
  DEF_x__h2025 = DEF_x__h1929 ^ DEF_y__h1930;
  DEF_x__h2172 = DEF_x__h2076 ^ DEF_y__h2077;
  DEF_x__h2319 = DEF_x__h2223 ^ DEF_y__h2224;
  DEF_x__h2466 = DEF_x__h2370 ^ DEF_y__h2371;
  DEF_x__h2613 = DEF_x__h2517 ^ DEF_y__h2518;
  DEF_x__h2760 = DEF_x__h2664 ^ DEF_y__h2665;
  DEF_x__h2907 = DEF_x__h2811 ^ DEF_y__h2812;
  DEF_x__h3054 = DEF_x__h2958 ^ DEF_y__h2959;
  DEF_x__h3201 = DEF_x__h3105 ^ DEF_y__h3106;
  DEF_x__h3348 = DEF_x__h3252 ^ DEF_y__h3253;
  DEF_x__h3495 = DEF_x__h3399 ^ DEF_y__h3400;
  DEF_x__h3642 = DEF_x__h3546 ^ DEF_y__h3547;
  DEF_y__h3567 = DEF_x__h3546 & DEF_y__h3547;
  DEF_y__h3420 = DEF_x__h3399 & DEF_y__h3400;
  DEF_y__h3273 = DEF_x__h3252 & DEF_y__h3253;
  DEF_y__h3126 = DEF_x__h3105 & DEF_y__h3106;
  DEF_y__h2979 = DEF_x__h2958 & DEF_y__h2959;
  DEF_y__h2832 = DEF_x__h2811 & DEF_y__h2812;
  DEF_y__h2685 = DEF_x__h2664 & DEF_y__h2665;
  DEF_y__h2538 = DEF_x__h2517 & DEF_y__h2518;
  DEF_y__h2391 = DEF_x__h2370 & DEF_y__h2371;
  DEF_y__h2244 = DEF_x__h2223 & DEF_y__h2224;
  DEF_y__h2097 = DEF_x__h2076 & DEF_y__h2077;
  DEF_y__h1950 = DEF_x__h1929 & DEF_y__h1930;
  DEF_y__h1803 = DEF_x__h1782 & DEF_y__h1783;
  DEF_y__h1656 = DEF_x__h1635 & DEF_y__h1636;
  DEF_y__h1509 = DEF_x__h1488 & DEF_y__h1489;
  DEF_y__h1362 = DEF_x__h1341 & DEF_y__h1342;
  DEF_y__h1215 = DEF_x__h1194 & DEF_y__h1195;
  DEF_y__h1068 = DEF_x__h1047 & DEF_y__h1048;
  DEF_y__h920 = DEF_x__h899 & DEF_y__h900;
  DEF_y__h795 = DEF_x__h777 & ARG_add_add_or_sub;
  DEF_x__h796 = DEF_y__h778 & ARG_add_add_or_sub;
  DEF_y__h797 = DEF_x__h777 & DEF_y__h778;
  DEF_x__h794 = DEF_x__h796 | DEF_y__h797;
  DEF_c_in__h901 = (tUInt8)((tUInt8)1u & (DEF_x__h794 | DEF_y__h795 ? 1u : 0u));
  DEF_y__h918 = DEF_x__h899 & DEF_c_in__h901;
  DEF_x__h919 = DEF_y__h900 & DEF_c_in__h901;
  DEF_x__h917 = DEF_x__h919 | DEF_y__h920;
  DEF_c_in__h1049 = DEF_x__h917 | DEF_y__h918;
  DEF_y__h1066 = DEF_x__h1047 & DEF_c_in__h1049;
  DEF_x__h1067 = DEF_y__h1048 & DEF_c_in__h1049;
  DEF_x__h1065 = DEF_x__h1067 | DEF_y__h1068;
  DEF_c_in__h1196 = DEF_x__h1065 | DEF_y__h1066;
  DEF_y__h1213 = DEF_x__h1194 & DEF_c_in__h1196;
  DEF_x__h1214 = DEF_y__h1195 & DEF_c_in__h1196;
  DEF_x__h1212 = DEF_x__h1214 | DEF_y__h1215;
  DEF_c_in__h1343 = DEF_x__h1212 | DEF_y__h1213;
  DEF_y__h1360 = DEF_x__h1341 & DEF_c_in__h1343;
  DEF_x__h1361 = DEF_y__h1342 & DEF_c_in__h1343;
  DEF_x__h1359 = DEF_x__h1361 | DEF_y__h1362;
  DEF_c_in__h1490 = DEF_x__h1359 | DEF_y__h1360;
  DEF_y__h1507 = DEF_x__h1488 & DEF_c_in__h1490;
  DEF_x__h1508 = DEF_y__h1489 & DEF_c_in__h1490;
  DEF_x__h1506 = DEF_x__h1508 | DEF_y__h1509;
  DEF_c_in__h1637 = DEF_x__h1506 | DEF_y__h1507;
  DEF_y__h1654 = DEF_x__h1635 & DEF_c_in__h1637;
  DEF_x__h1655 = DEF_y__h1636 & DEF_c_in__h1637;
  DEF_x__h1653 = DEF_x__h1655 | DEF_y__h1656;
  DEF_c_in__h1784 = DEF_x__h1653 | DEF_y__h1654;
  DEF_y__h1801 = DEF_x__h1782 & DEF_c_in__h1784;
  DEF_x__h1802 = DEF_y__h1783 & DEF_c_in__h1784;
  DEF_x__h1800 = DEF_x__h1802 | DEF_y__h1803;
  DEF_c_in__h1931 = DEF_x__h1800 | DEF_y__h1801;
  DEF_y__h1948 = DEF_x__h1929 & DEF_c_in__h1931;
  DEF_x__h1949 = DEF_y__h1930 & DEF_c_in__h1931;
  DEF_x__h1947 = DEF_x__h1949 | DEF_y__h1950;
  DEF_c_in__h2078 = DEF_x__h1947 | DEF_y__h1948;
  DEF_y__h2095 = DEF_x__h2076 & DEF_c_in__h2078;
  DEF_x__h2096 = DEF_y__h2077 & DEF_c_in__h2078;
  DEF_x__h2094 = DEF_x__h2096 | DEF_y__h2097;
  DEF_c_in__h2225 = DEF_x__h2094 | DEF_y__h2095;
  DEF_y__h2242 = DEF_x__h2223 & DEF_c_in__h2225;
  DEF_x__h2243 = DEF_y__h2224 & DEF_c_in__h2225;
  DEF_x__h2241 = DEF_x__h2243 | DEF_y__h2244;
  DEF_c_in__h2372 = DEF_x__h2241 | DEF_y__h2242;
  DEF_y__h2389 = DEF_x__h2370 & DEF_c_in__h2372;
  DEF_x__h2390 = DEF_y__h2371 & DEF_c_in__h2372;
  DEF_x__h2388 = DEF_x__h2390 | DEF_y__h2391;
  DEF_c_in__h2519 = DEF_x__h2388 | DEF_y__h2389;
  DEF_y__h2536 = DEF_x__h2517 & DEF_c_in__h2519;
  DEF_x__h2537 = DEF_y__h2518 & DEF_c_in__h2519;
  DEF_x__h2535 = DEF_x__h2537 | DEF_y__h2538;
  DEF_c_in__h2666 = DEF_x__h2535 | DEF_y__h2536;
  DEF_y__h2683 = DEF_x__h2664 & DEF_c_in__h2666;
  DEF_x__h2684 = DEF_y__h2665 & DEF_c_in__h2666;
  DEF_x__h2682 = DEF_x__h2684 | DEF_y__h2685;
  DEF_c_in__h2813 = DEF_x__h2682 | DEF_y__h2683;
  DEF_y__h2830 = DEF_x__h2811 & DEF_c_in__h2813;
  DEF_x__h2831 = DEF_y__h2812 & DEF_c_in__h2813;
  DEF_x__h2829 = DEF_x__h2831 | DEF_y__h2832;
  DEF_c_in__h2960 = DEF_x__h2829 | DEF_y__h2830;
  DEF_y__h2977 = DEF_x__h2958 & DEF_c_in__h2960;
  DEF_x__h2978 = DEF_y__h2959 & DEF_c_in__h2960;
  DEF_x__h2976 = DEF_x__h2978 | DEF_y__h2979;
  DEF_c_in__h3107 = DEF_x__h2976 | DEF_y__h2977;
  DEF_y__h3124 = DEF_x__h3105 & DEF_c_in__h3107;
  DEF_x__h3125 = DEF_y__h3106 & DEF_c_in__h3107;
  DEF_x__h3123 = DEF_x__h3125 | DEF_y__h3126;
  DEF_c_in__h3254 = DEF_x__h3123 | DEF_y__h3124;
  DEF_y__h3271 = DEF_x__h3252 & DEF_c_in__h3254;
  DEF_x__h3272 = DEF_y__h3253 & DEF_c_in__h3254;
  DEF_x__h3270 = DEF_x__h3272 | DEF_y__h3273;
  DEF_c_in__h3401 = DEF_x__h3270 | DEF_y__h3271;
  DEF_y__h3418 = DEF_x__h3399 & DEF_c_in__h3401;
  DEF_x__h3419 = DEF_y__h3400 & DEF_c_in__h3401;
  DEF_x__h3417 = DEF_x__h3419 | DEF_y__h3420;
  DEF_c_in__h3548 = DEF_x__h3417 | DEF_y__h3418;
  DEF_y__h3565 = DEF_x__h3546 & DEF_c_in__h3548;
  DEF_x__h3566 = DEF_y__h3547 & DEF_c_in__h3548;
  DEF_x__h3564 = DEF_x__h3566 | DEF_y__h3567;
  DEF_carry_out__h43 = DEF_x__h3564 | DEF_y__h3565;
  DEF__theResult___snd_fst__h3670 = 1048575u & ((((((((((((((((((((((tUInt32)(DEF_x__h3642 ^ DEF_c_in__h3548)) << 19u) | (((tUInt32)(DEF_x__h3495 ^ DEF_c_in__h3401)) << 18u)) | (((tUInt32)(DEF_x__h3348 ^ DEF_c_in__h3254)) << 17u)) | (((tUInt32)(DEF_x__h3201 ^ DEF_c_in__h3107)) << 16u)) | (((tUInt32)(DEF_x__h3054 ^ DEF_c_in__h2960)) << 15u)) | (((tUInt32)(DEF_x__h2907 ^ DEF_c_in__h2813)) << 14u)) | (((tUInt32)(DEF_x__h2760 ^ DEF_c_in__h2666)) << 13u)) | (((tUInt32)(DEF_x__h2613 ^ DEF_c_in__h2519)) << 12u)) | (((tUInt32)(DEF_x__h2466 ^ DEF_c_in__h2372)) << 11u)) | (((tUInt32)(DEF_x__h2319 ^ DEF_c_in__h2225)) << 10u)) | (((tUInt32)(DEF_x__h2172 ^ DEF_c_in__h2078)) << 9u)) | (((tUInt32)(DEF_x__h2025 ^ DEF_c_in__h1931)) << 8u)) | (((tUInt32)(DEF_x__h1878 ^ DEF_c_in__h1784)) << 7u)) | (((tUInt32)(DEF_x__h1731 ^ DEF_c_in__h1637)) << 6u)) | (((tUInt32)(DEF_x__h1584 ^ DEF_c_in__h1490)) << 5u)) | (((tUInt32)(DEF_x__h1437 ^ DEF_c_in__h1343)) << 4u)) | (((tUInt32)(DEF_x__h1290 ^ DEF_c_in__h1196)) << 3u)) | (((tUInt32)(DEF_x__h1143 ^ DEF_c_in__h1049)) << 2u)) | (((tUInt32)(DEF_x__h996 ^ DEF_c_in__h901)) << 1u)) | (tUInt32)((tUInt8)((tUInt8)1u & (DEF_x__h852 ^ ARG_add_add_or_sub ? 1u : 0u))));
  PORT_add = 2097151u & ((((tUInt32)(DEF_carry_out__h43)) << 20u) | DEF__theResult___snd_fst__h3670);
  return PORT_add;
}

tUInt8 MOD_mkAdder20Bit::METH_RDY_add()
{
  tUInt8 DEF_CAN_FIRE_add;
  tUInt8 PORT_RDY_add;
  DEF_CAN_FIRE_add = (tUInt8)1u;
  PORT_RDY_add = DEF_CAN_FIRE_add;
  return PORT_RDY_add;
}


/* Reset routines */

void MOD_mkAdder20Bit::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkAdder20Bit::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkAdder20Bit::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_mkAdder20Bit::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 1u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkAdder20Bit::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkAdder20Bit &backing)
{
  vcd_defs(dt, backing);
}

void MOD_mkAdder20Bit::vcd_defs(tVCDDumpType dt, MOD_mkAdder20Bit &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
    }
}
