/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Tue Oct 22 19:27:12 IST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "mkAdder24Bit.h"


/* Constructor */
MOD_mkAdder24Bit::MOD_mkAdder24Bit(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent), __clk_handle_0(BAD_CLOCK_HANDLE), PORT_RST_N((tUInt8)1u)
{
  symbol_count = 0u;
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkAdder24Bit::init_symbols_0()
{
}


/* Rule actions */


/* Methods */

tUInt32 MOD_mkAdder24Bit::METH_add(tUInt32 ARG_add_x, tUInt32 ARG_add_y, tUInt8 ARG_add_add_or_sub)
{
  tUInt32 DEF_add_x_BIT_23_68_XOR_IF_add_add_or_sub_THEN_INV_ETC___d234;
  tUInt8 DEF_y__h884;
  tUInt8 DEF_x__h883;
  tUInt8 DEF_y__h882;
  tUInt8 DEF_y__h1007;
  tUInt8 DEF_x__h1006;
  tUInt8 DEF_y__h1005;
  tUInt8 DEF_x__h1004;
  tUInt8 DEF_y__h1155;
  tUInt8 DEF_x__h1154;
  tUInt8 DEF_y__h1153;
  tUInt8 DEF_x__h1152;
  tUInt8 DEF_y__h1302;
  tUInt8 DEF_x__h1301;
  tUInt8 DEF_y__h1300;
  tUInt8 DEF_x__h1299;
  tUInt8 DEF_y__h1449;
  tUInt8 DEF_x__h1448;
  tUInt8 DEF_y__h1447;
  tUInt8 DEF_x__h1446;
  tUInt8 DEF_y__h1596;
  tUInt8 DEF_x__h1595;
  tUInt8 DEF_y__h1594;
  tUInt8 DEF_x__h1593;
  tUInt8 DEF_y__h1743;
  tUInt8 DEF_x__h1742;
  tUInt8 DEF_y__h1741;
  tUInt8 DEF_x__h1740;
  tUInt8 DEF_y__h1890;
  tUInt8 DEF_x__h1889;
  tUInt8 DEF_y__h1888;
  tUInt8 DEF_x__h1887;
  tUInt8 DEF_y__h2037;
  tUInt8 DEF_x__h2036;
  tUInt8 DEF_y__h2035;
  tUInt8 DEF_x__h2034;
  tUInt8 DEF_y__h2184;
  tUInt8 DEF_x__h2183;
  tUInt8 DEF_y__h2182;
  tUInt8 DEF_x__h2181;
  tUInt8 DEF_y__h2331;
  tUInt8 DEF_x__h2330;
  tUInt8 DEF_y__h2329;
  tUInt8 DEF_x__h2328;
  tUInt8 DEF_y__h2478;
  tUInt8 DEF_x__h2477;
  tUInt8 DEF_y__h2476;
  tUInt8 DEF_x__h2475;
  tUInt8 DEF_y__h2625;
  tUInt8 DEF_x__h2624;
  tUInt8 DEF_y__h2623;
  tUInt8 DEF_x__h2622;
  tUInt8 DEF_y__h2772;
  tUInt8 DEF_x__h2771;
  tUInt8 DEF_y__h2770;
  tUInt8 DEF_x__h2769;
  tUInt8 DEF_y__h2919;
  tUInt8 DEF_x__h2918;
  tUInt8 DEF_y__h2917;
  tUInt8 DEF_x__h2916;
  tUInt8 DEF_y__h3066;
  tUInt8 DEF_x__h3065;
  tUInt8 DEF_y__h3064;
  tUInt8 DEF_x__h3063;
  tUInt8 DEF_y__h3213;
  tUInt8 DEF_x__h3212;
  tUInt8 DEF_y__h3211;
  tUInt8 DEF_x__h3210;
  tUInt8 DEF_y__h3360;
  tUInt8 DEF_x__h3359;
  tUInt8 DEF_y__h3358;
  tUInt8 DEF_x__h3357;
  tUInt8 DEF_y__h3507;
  tUInt8 DEF_x__h3506;
  tUInt8 DEF_y__h3505;
  tUInt8 DEF_x__h3504;
  tUInt8 DEF_y__h3654;
  tUInt8 DEF_x__h3653;
  tUInt8 DEF_y__h3652;
  tUInt8 DEF_x__h3651;
  tUInt8 DEF_y__h3801;
  tUInt8 DEF_x__h3800;
  tUInt8 DEF_y__h3799;
  tUInt8 DEF_x__h3798;
  tUInt8 DEF_y__h3948;
  tUInt8 DEF_x__h3947;
  tUInt8 DEF_y__h3946;
  tUInt8 DEF_x__h3945;
  tUInt8 DEF_y__h4095;
  tUInt8 DEF_x__h4094;
  tUInt8 DEF_y__h4093;
  tUInt8 DEF_x__h4092;
  tUInt8 DEF_y__h4242;
  tUInt8 DEF_x__h4241;
  tUInt8 DEF_y__h4240;
  tUInt8 DEF_x__h4239;
  tUInt8 DEF_c_in__h4223;
  tUInt8 DEF_x__h4317;
  tUInt8 DEF_c_in__h4076;
  tUInt8 DEF_x__h4170;
  tUInt8 DEF_c_in__h3929;
  tUInt8 DEF_x__h4023;
  tUInt8 DEF_c_in__h3782;
  tUInt8 DEF_x__h3876;
  tUInt8 DEF_c_in__h3635;
  tUInt8 DEF_x__h3729;
  tUInt8 DEF_c_in__h3488;
  tUInt8 DEF_x__h3582;
  tUInt8 DEF_c_in__h3341;
  tUInt8 DEF_x__h3435;
  tUInt8 DEF_c_in__h3194;
  tUInt8 DEF_x__h3288;
  tUInt8 DEF_c_in__h3047;
  tUInt8 DEF_x__h3141;
  tUInt8 DEF_c_in__h2900;
  tUInt8 DEF_x__h2994;
  tUInt8 DEF_c_in__h2753;
  tUInt8 DEF_x__h2847;
  tUInt8 DEF_c_in__h2606;
  tUInt8 DEF_x__h2700;
  tUInt8 DEF_c_in__h2459;
  tUInt8 DEF_x__h2553;
  tUInt8 DEF_c_in__h2312;
  tUInt8 DEF_x__h2406;
  tUInt8 DEF_c_in__h2165;
  tUInt8 DEF_x__h2259;
  tUInt8 DEF_c_in__h2018;
  tUInt8 DEF_x__h2112;
  tUInt8 DEF_c_in__h1871;
  tUInt8 DEF_x__h1965;
  tUInt8 DEF_c_in__h1724;
  tUInt8 DEF_x__h1818;
  tUInt8 DEF_c_in__h1577;
  tUInt8 DEF_x__h1671;
  tUInt8 DEF_c_in__h1430;
  tUInt8 DEF_x__h1524;
  tUInt8 DEF_c_in__h1283;
  tUInt8 DEF_x__h1377;
  tUInt8 DEF_c_in__h1136;
  tUInt8 DEF_x__h1230;
  tUInt8 DEF_x__h1083;
  tUInt8 DEF_x__h939;
  tUInt8 DEF_x__h864;
  tUInt8 DEF_x__h986;
  tUInt8 DEF_x__h1134;
  tUInt8 DEF_x__h1281;
  tUInt8 DEF_x__h1428;
  tUInt8 DEF_x__h1575;
  tUInt8 DEF_x__h1722;
  tUInt8 DEF_x__h1869;
  tUInt8 DEF_x__h2016;
  tUInt8 DEF_x__h2163;
  tUInt8 DEF_x__h2310;
  tUInt8 DEF_x__h2457;
  tUInt8 DEF_x__h2604;
  tUInt8 DEF_x__h2751;
  tUInt8 DEF_x__h2898;
  tUInt8 DEF_x__h3045;
  tUInt8 DEF_x__h3192;
  tUInt8 DEF_x__h3339;
  tUInt8 DEF_x__h3486;
  tUInt8 DEF_x__h3633;
  tUInt8 DEF_x__h3780;
  tUInt8 DEF_x__h3927;
  tUInt8 DEF_x__h4074;
  tUInt8 DEF_x__h4221;
  tUInt8 DEF_y__h865;
  tUInt8 DEF_y__h987;
  tUInt8 DEF_y__h1135;
  tUInt8 DEF_y__h1282;
  tUInt8 DEF_y__h1429;
  tUInt8 DEF_y__h1576;
  tUInt8 DEF_y__h1723;
  tUInt8 DEF_y__h1870;
  tUInt8 DEF_y__h2017;
  tUInt8 DEF_y__h2164;
  tUInt8 DEF_y__h2311;
  tUInt8 DEF_y__h2458;
  tUInt8 DEF_y__h2605;
  tUInt8 DEF_y__h2752;
  tUInt8 DEF_y__h2899;
  tUInt8 DEF_y__h3046;
  tUInt8 DEF_y__h3193;
  tUInt8 DEF_y__h3340;
  tUInt8 DEF_y__h3487;
  tUInt8 DEF_y__h3634;
  tUInt8 DEF_y__h3781;
  tUInt8 DEF_y__h3928;
  tUInt8 DEF_y__h4075;
  tUInt8 DEF_y__h4222;
  tUInt8 DEF_c_in__h988;
  tUInt8 DEF_x__h881;
  tUInt8 DEF_carry_out__h43;
  tUInt32 DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2;
  tUInt32 PORT_add;
  DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 = ARG_add_add_or_sub ? 16777215u & ~ARG_add_y : ARG_add_y;
  DEF_y__h4222 = (tUInt8)(DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 23u);
  DEF_y__h4075 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 22u));
  DEF_y__h3928 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 21u));
  DEF_y__h3781 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 20u));
  DEF_y__h3634 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 19u));
  DEF_y__h3487 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 18u));
  DEF_y__h3193 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 16u));
  DEF_y__h3340 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 17u));
  DEF_y__h3046 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 15u));
  DEF_y__h2899 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 14u));
  DEF_y__h2752 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 13u));
  DEF_y__h2164 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 9u));
  DEF_y__h2605 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 12u));
  DEF_y__h2458 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 11u));
  DEF_y__h2311 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 10u));
  DEF_y__h2017 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 8u));
  DEF_y__h1870 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 7u));
  DEF_y__h1723 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 6u));
  DEF_y__h1429 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 4u));
  DEF_y__h1576 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 5u));
  DEF_y__h1282 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 3u));
  DEF_y__h1135 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 2u));
  DEF_y__h987 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 1u));
  DEF_y__h865 = (tUInt8)((tUInt8)1u & DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2);
  DEF_x__h4074 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 22u));
  DEF_x__h4221 = (tUInt8)(ARG_add_x >> 23u);
  DEF_x__h3927 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 21u));
  DEF_x__h3780 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 20u));
  DEF_x__h3633 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 19u));
  DEF_x__h3486 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 18u));
  DEF_x__h3192 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 16u));
  DEF_x__h3339 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 17u));
  DEF_x__h3045 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 15u));
  DEF_x__h2898 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 14u));
  DEF_x__h2751 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 13u));
  DEF_x__h2163 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 9u));
  DEF_x__h2604 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 12u));
  DEF_x__h2457 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 11u));
  DEF_x__h2310 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 10u));
  DEF_x__h2016 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 8u));
  DEF_x__h1869 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 7u));
  DEF_x__h1722 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 6u));
  DEF_x__h1428 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 4u));
  DEF_x__h1575 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 5u));
  DEF_x__h1281 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 3u));
  DEF_x__h1134 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 2u));
  DEF_x__h986 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 1u));
  DEF_x__h864 = (tUInt8)((tUInt8)1u & ARG_add_x);
  DEF_x__h939 = DEF_x__h864 ^ DEF_y__h865;
  DEF_x__h1083 = DEF_x__h986 ^ DEF_y__h987;
  DEF_x__h1230 = DEF_x__h1134 ^ DEF_y__h1135;
  DEF_x__h1377 = DEF_x__h1281 ^ DEF_y__h1282;
  DEF_x__h1524 = DEF_x__h1428 ^ DEF_y__h1429;
  DEF_x__h1671 = DEF_x__h1575 ^ DEF_y__h1576;
  DEF_x__h2112 = DEF_x__h2016 ^ DEF_y__h2017;
  DEF_x__h1818 = DEF_x__h1722 ^ DEF_y__h1723;
  DEF_x__h1965 = DEF_x__h1869 ^ DEF_y__h1870;
  DEF_x__h2259 = DEF_x__h2163 ^ DEF_y__h2164;
  DEF_x__h2406 = DEF_x__h2310 ^ DEF_y__h2311;
  DEF_x__h2553 = DEF_x__h2457 ^ DEF_y__h2458;
  DEF_x__h2700 = DEF_x__h2604 ^ DEF_y__h2605;
  DEF_x__h2847 = DEF_x__h2751 ^ DEF_y__h2752;
  DEF_x__h2994 = DEF_x__h2898 ^ DEF_y__h2899;
  DEF_x__h3141 = DEF_x__h3045 ^ DEF_y__h3046;
  DEF_x__h3288 = DEF_x__h3192 ^ DEF_y__h3193;
  DEF_x__h3435 = DEF_x__h3339 ^ DEF_y__h3340;
  DEF_x__h3582 = DEF_x__h3486 ^ DEF_y__h3487;
  DEF_x__h3729 = DEF_x__h3633 ^ DEF_y__h3634;
  DEF_x__h3876 = DEF_x__h3780 ^ DEF_y__h3781;
  DEF_x__h4023 = DEF_x__h3927 ^ DEF_y__h3928;
  DEF_x__h4170 = DEF_x__h4074 ^ DEF_y__h4075;
  DEF_x__h4317 = DEF_x__h4221 ^ DEF_y__h4222;
  DEF_y__h4242 = DEF_x__h4221 & DEF_y__h4222;
  DEF_y__h4095 = DEF_x__h4074 & DEF_y__h4075;
  DEF_y__h3948 = DEF_x__h3927 & DEF_y__h3928;
  DEF_y__h3801 = DEF_x__h3780 & DEF_y__h3781;
  DEF_y__h3654 = DEF_x__h3633 & DEF_y__h3634;
  DEF_y__h3507 = DEF_x__h3486 & DEF_y__h3487;
  DEF_y__h3360 = DEF_x__h3339 & DEF_y__h3340;
  DEF_y__h3213 = DEF_x__h3192 & DEF_y__h3193;
  DEF_y__h3066 = DEF_x__h3045 & DEF_y__h3046;
  DEF_y__h2919 = DEF_x__h2898 & DEF_y__h2899;
  DEF_y__h2772 = DEF_x__h2751 & DEF_y__h2752;
  DEF_y__h2625 = DEF_x__h2604 & DEF_y__h2605;
  DEF_y__h2478 = DEF_x__h2457 & DEF_y__h2458;
  DEF_y__h2331 = DEF_x__h2310 & DEF_y__h2311;
  DEF_y__h2184 = DEF_x__h2163 & DEF_y__h2164;
  DEF_y__h2037 = DEF_x__h2016 & DEF_y__h2017;
  DEF_y__h1890 = DEF_x__h1869 & DEF_y__h1870;
  DEF_y__h1743 = DEF_x__h1722 & DEF_y__h1723;
  DEF_y__h1596 = DEF_x__h1575 & DEF_y__h1576;
  DEF_y__h1449 = DEF_x__h1428 & DEF_y__h1429;
  DEF_y__h1302 = DEF_x__h1281 & DEF_y__h1282;
  DEF_y__h1155 = DEF_x__h1134 & DEF_y__h1135;
  DEF_y__h1007 = DEF_x__h986 & DEF_y__h987;
  DEF_y__h882 = DEF_x__h864 & ARG_add_add_or_sub;
  DEF_x__h883 = DEF_y__h865 & ARG_add_add_or_sub;
  DEF_y__h884 = DEF_x__h864 & DEF_y__h865;
  DEF_x__h881 = DEF_x__h883 | DEF_y__h884;
  DEF_c_in__h988 = (tUInt8)((tUInt8)1u & (DEF_x__h881 | DEF_y__h882 ? 1u : 0u));
  DEF_y__h1005 = DEF_x__h986 & DEF_c_in__h988;
  DEF_x__h1006 = DEF_y__h987 & DEF_c_in__h988;
  DEF_x__h1004 = DEF_x__h1006 | DEF_y__h1007;
  DEF_c_in__h1136 = DEF_x__h1004 | DEF_y__h1005;
  DEF_y__h1153 = DEF_x__h1134 & DEF_c_in__h1136;
  DEF_x__h1154 = DEF_y__h1135 & DEF_c_in__h1136;
  DEF_x__h1152 = DEF_x__h1154 | DEF_y__h1155;
  DEF_c_in__h1283 = DEF_x__h1152 | DEF_y__h1153;
  DEF_y__h1300 = DEF_x__h1281 & DEF_c_in__h1283;
  DEF_x__h1301 = DEF_y__h1282 & DEF_c_in__h1283;
  DEF_x__h1299 = DEF_x__h1301 | DEF_y__h1302;
  DEF_c_in__h1430 = DEF_x__h1299 | DEF_y__h1300;
  DEF_y__h1447 = DEF_x__h1428 & DEF_c_in__h1430;
  DEF_x__h1448 = DEF_y__h1429 & DEF_c_in__h1430;
  DEF_x__h1446 = DEF_x__h1448 | DEF_y__h1449;
  DEF_c_in__h1577 = DEF_x__h1446 | DEF_y__h1447;
  DEF_y__h1594 = DEF_x__h1575 & DEF_c_in__h1577;
  DEF_x__h1595 = DEF_y__h1576 & DEF_c_in__h1577;
  DEF_x__h1593 = DEF_x__h1595 | DEF_y__h1596;
  DEF_c_in__h1724 = DEF_x__h1593 | DEF_y__h1594;
  DEF_y__h1741 = DEF_x__h1722 & DEF_c_in__h1724;
  DEF_x__h1742 = DEF_y__h1723 & DEF_c_in__h1724;
  DEF_x__h1740 = DEF_x__h1742 | DEF_y__h1743;
  DEF_c_in__h1871 = DEF_x__h1740 | DEF_y__h1741;
  DEF_y__h1888 = DEF_x__h1869 & DEF_c_in__h1871;
  DEF_x__h1889 = DEF_y__h1870 & DEF_c_in__h1871;
  DEF_x__h1887 = DEF_x__h1889 | DEF_y__h1890;
  DEF_c_in__h2018 = DEF_x__h1887 | DEF_y__h1888;
  DEF_y__h2035 = DEF_x__h2016 & DEF_c_in__h2018;
  DEF_x__h2036 = DEF_y__h2017 & DEF_c_in__h2018;
  DEF_x__h2034 = DEF_x__h2036 | DEF_y__h2037;
  DEF_c_in__h2165 = DEF_x__h2034 | DEF_y__h2035;
  DEF_y__h2182 = DEF_x__h2163 & DEF_c_in__h2165;
  DEF_x__h2183 = DEF_y__h2164 & DEF_c_in__h2165;
  DEF_x__h2181 = DEF_x__h2183 | DEF_y__h2184;
  DEF_c_in__h2312 = DEF_x__h2181 | DEF_y__h2182;
  DEF_y__h2329 = DEF_x__h2310 & DEF_c_in__h2312;
  DEF_x__h2330 = DEF_y__h2311 & DEF_c_in__h2312;
  DEF_x__h2328 = DEF_x__h2330 | DEF_y__h2331;
  DEF_c_in__h2459 = DEF_x__h2328 | DEF_y__h2329;
  DEF_y__h2476 = DEF_x__h2457 & DEF_c_in__h2459;
  DEF_x__h2477 = DEF_y__h2458 & DEF_c_in__h2459;
  DEF_x__h2475 = DEF_x__h2477 | DEF_y__h2478;
  DEF_c_in__h2606 = DEF_x__h2475 | DEF_y__h2476;
  DEF_y__h2623 = DEF_x__h2604 & DEF_c_in__h2606;
  DEF_x__h2624 = DEF_y__h2605 & DEF_c_in__h2606;
  DEF_x__h2622 = DEF_x__h2624 | DEF_y__h2625;
  DEF_c_in__h2753 = DEF_x__h2622 | DEF_y__h2623;
  DEF_y__h2770 = DEF_x__h2751 & DEF_c_in__h2753;
  DEF_x__h2771 = DEF_y__h2752 & DEF_c_in__h2753;
  DEF_x__h2769 = DEF_x__h2771 | DEF_y__h2772;
  DEF_c_in__h2900 = DEF_x__h2769 | DEF_y__h2770;
  DEF_y__h2917 = DEF_x__h2898 & DEF_c_in__h2900;
  DEF_x__h2918 = DEF_y__h2899 & DEF_c_in__h2900;
  DEF_x__h2916 = DEF_x__h2918 | DEF_y__h2919;
  DEF_c_in__h3047 = DEF_x__h2916 | DEF_y__h2917;
  DEF_y__h3064 = DEF_x__h3045 & DEF_c_in__h3047;
  DEF_x__h3065 = DEF_y__h3046 & DEF_c_in__h3047;
  DEF_x__h3063 = DEF_x__h3065 | DEF_y__h3066;
  DEF_c_in__h3194 = DEF_x__h3063 | DEF_y__h3064;
  DEF_y__h3211 = DEF_x__h3192 & DEF_c_in__h3194;
  DEF_x__h3212 = DEF_y__h3193 & DEF_c_in__h3194;
  DEF_x__h3210 = DEF_x__h3212 | DEF_y__h3213;
  DEF_c_in__h3341 = DEF_x__h3210 | DEF_y__h3211;
  DEF_y__h3358 = DEF_x__h3339 & DEF_c_in__h3341;
  DEF_x__h3359 = DEF_y__h3340 & DEF_c_in__h3341;
  DEF_x__h3357 = DEF_x__h3359 | DEF_y__h3360;
  DEF_c_in__h3488 = DEF_x__h3357 | DEF_y__h3358;
  DEF_y__h3505 = DEF_x__h3486 & DEF_c_in__h3488;
  DEF_x__h3506 = DEF_y__h3487 & DEF_c_in__h3488;
  DEF_x__h3504 = DEF_x__h3506 | DEF_y__h3507;
  DEF_c_in__h3635 = DEF_x__h3504 | DEF_y__h3505;
  DEF_y__h3652 = DEF_x__h3633 & DEF_c_in__h3635;
  DEF_x__h3653 = DEF_y__h3634 & DEF_c_in__h3635;
  DEF_x__h3651 = DEF_x__h3653 | DEF_y__h3654;
  DEF_c_in__h3782 = DEF_x__h3651 | DEF_y__h3652;
  DEF_y__h3799 = DEF_x__h3780 & DEF_c_in__h3782;
  DEF_x__h3800 = DEF_y__h3781 & DEF_c_in__h3782;
  DEF_x__h3798 = DEF_x__h3800 | DEF_y__h3801;
  DEF_c_in__h3929 = DEF_x__h3798 | DEF_y__h3799;
  DEF_y__h3946 = DEF_x__h3927 & DEF_c_in__h3929;
  DEF_x__h3947 = DEF_y__h3928 & DEF_c_in__h3929;
  DEF_x__h3945 = DEF_x__h3947 | DEF_y__h3948;
  DEF_c_in__h4076 = DEF_x__h3945 | DEF_y__h3946;
  DEF_y__h4093 = DEF_x__h4074 & DEF_c_in__h4076;
  DEF_x__h4094 = DEF_y__h4075 & DEF_c_in__h4076;
  DEF_x__h4092 = DEF_x__h4094 | DEF_y__h4095;
  DEF_c_in__h4223 = DEF_x__h4092 | DEF_y__h4093;
  DEF_y__h4240 = DEF_x__h4221 & DEF_c_in__h4223;
  DEF_x__h4241 = DEF_y__h4222 & DEF_c_in__h4223;
  DEF_x__h4239 = DEF_x__h4241 | DEF_y__h4242;
  DEF_carry_out__h43 = DEF_x__h4239 | DEF_y__h4240;
  DEF_add_x_BIT_23_68_XOR_IF_add_add_or_sub_THEN_INV_ETC___d234 = 16777215u & ((((((((((((((((((((((((((tUInt32)(DEF_x__h4317 ^ DEF_c_in__h4223)) << 23u) | (((tUInt32)(DEF_x__h4170 ^ DEF_c_in__h4076)) << 22u)) | (((tUInt32)(DEF_x__h4023 ^ DEF_c_in__h3929)) << 21u)) | (((tUInt32)(DEF_x__h3876 ^ DEF_c_in__h3782)) << 20u)) | (((tUInt32)(DEF_x__h3729 ^ DEF_c_in__h3635)) << 19u)) | (((tUInt32)(DEF_x__h3582 ^ DEF_c_in__h3488)) << 18u)) | (((tUInt32)(DEF_x__h3435 ^ DEF_c_in__h3341)) << 17u)) | (((tUInt32)(DEF_x__h3288 ^ DEF_c_in__h3194)) << 16u)) | (((tUInt32)(DEF_x__h3141 ^ DEF_c_in__h3047)) << 15u)) | (((tUInt32)(DEF_x__h2994 ^ DEF_c_in__h2900)) << 14u)) | (((tUInt32)(DEF_x__h2847 ^ DEF_c_in__h2753)) << 13u)) | (((tUInt32)(DEF_x__h2700 ^ DEF_c_in__h2606)) << 12u)) | (((tUInt32)(DEF_x__h2553 ^ DEF_c_in__h2459)) << 11u)) | (((tUInt32)(DEF_x__h2406 ^ DEF_c_in__h2312)) << 10u)) | (((tUInt32)(DEF_x__h2259 ^ DEF_c_in__h2165)) << 9u)) | (((tUInt32)(DEF_x__h2112 ^ DEF_c_in__h2018)) << 8u)) | (((tUInt32)(DEF_x__h1965 ^ DEF_c_in__h1871)) << 7u)) | (((tUInt32)(DEF_x__h1818 ^ DEF_c_in__h1724)) << 6u)) | (((tUInt32)(DEF_x__h1671 ^ DEF_c_in__h1577)) << 5u)) | (((tUInt32)(DEF_x__h1524 ^ DEF_c_in__h1430)) << 4u)) | (((tUInt32)(DEF_x__h1377 ^ DEF_c_in__h1283)) << 3u)) | (((tUInt32)(DEF_x__h1230 ^ DEF_c_in__h1136)) << 2u)) | (((tUInt32)(DEF_x__h1083 ^ DEF_c_in__h988)) << 1u)) | (tUInt32)((tUInt8)((tUInt8)1u & (DEF_x__h939 ^ ARG_add_add_or_sub ? 1u : 0u))));
  PORT_add = 33554431u & ((((tUInt32)(DEF_carry_out__h43)) << 24u) | DEF_add_x_BIT_23_68_XOR_IF_add_add_or_sub_THEN_INV_ETC___d234);
  return PORT_add;
}

tUInt8 MOD_mkAdder24Bit::METH_RDY_add()
{
  tUInt8 DEF_CAN_FIRE_add;
  tUInt8 PORT_RDY_add;
  DEF_CAN_FIRE_add = (tUInt8)1u;
  PORT_RDY_add = DEF_CAN_FIRE_add;
  return PORT_RDY_add;
}


/* Reset routines */

void MOD_mkAdder24Bit::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkAdder24Bit::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkAdder24Bit::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_mkAdder24Bit::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 1u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkAdder24Bit::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkAdder24Bit &backing)
{
  vcd_defs(dt, backing);
}

void MOD_mkAdder24Bit::vcd_defs(tVCDDumpType dt, MOD_mkAdder24Bit &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
    }
}
