/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Tue Oct 22 19:30:12 IST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "mkAdder32Bit.h"


/* Constructor */
MOD_mkAdder32Bit::MOD_mkAdder32Bit(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent), __clk_handle_0(BAD_CLOCK_HANDLE), PORT_RST_N((tUInt8)1u)
{
  symbol_count = 0u;
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkAdder32Bit::init_symbols_0()
{
}


/* Rule actions */


/* Methods */

tUInt64 MOD_mkAdder32Bit::METH_add(tUInt32 ARG_add_x, tUInt32 ARG_add_y, tUInt8 ARG_add_add_or_sub)
{
  tUInt32 DEF_add_x_BIT_31_24_XOR_IF_add_add_or_sub_THEN_INV_ETC___d310;
  tUInt8 DEF_y__h1132;
  tUInt8 DEF_x__h1131;
  tUInt8 DEF_y__h1130;
  tUInt8 DEF_x__h1129;
  tUInt8 DEF_y__h1255;
  tUInt8 DEF_x__h1254;
  tUInt8 DEF_y__h1253;
  tUInt8 DEF_x__h1252;
  tUInt8 DEF_y__h1403;
  tUInt8 DEF_x__h1402;
  tUInt8 DEF_y__h1401;
  tUInt8 DEF_x__h1400;
  tUInt8 DEF_y__h1550;
  tUInt8 DEF_x__h1549;
  tUInt8 DEF_y__h1548;
  tUInt8 DEF_x__h1547;
  tUInt8 DEF_y__h1697;
  tUInt8 DEF_x__h1696;
  tUInt8 DEF_y__h1695;
  tUInt8 DEF_x__h1694;
  tUInt8 DEF_y__h1844;
  tUInt8 DEF_x__h1843;
  tUInt8 DEF_y__h1842;
  tUInt8 DEF_x__h1841;
  tUInt8 DEF_y__h1991;
  tUInt8 DEF_x__h1990;
  tUInt8 DEF_y__h1989;
  tUInt8 DEF_x__h1988;
  tUInt8 DEF_y__h2138;
  tUInt8 DEF_x__h2137;
  tUInt8 DEF_y__h2136;
  tUInt8 DEF_x__h2135;
  tUInt8 DEF_y__h2285;
  tUInt8 DEF_x__h2284;
  tUInt8 DEF_y__h2283;
  tUInt8 DEF_x__h2282;
  tUInt8 DEF_y__h2432;
  tUInt8 DEF_x__h2431;
  tUInt8 DEF_y__h2430;
  tUInt8 DEF_x__h2429;
  tUInt8 DEF_y__h2579;
  tUInt8 DEF_x__h2578;
  tUInt8 DEF_y__h2577;
  tUInt8 DEF_x__h2576;
  tUInt8 DEF_y__h2726;
  tUInt8 DEF_x__h2725;
  tUInt8 DEF_y__h2724;
  tUInt8 DEF_x__h2723;
  tUInt8 DEF_y__h2873;
  tUInt8 DEF_x__h2872;
  tUInt8 DEF_y__h2871;
  tUInt8 DEF_x__h2870;
  tUInt8 DEF_y__h3020;
  tUInt8 DEF_x__h3019;
  tUInt8 DEF_y__h3018;
  tUInt8 DEF_x__h3017;
  tUInt8 DEF_y__h3167;
  tUInt8 DEF_x__h3166;
  tUInt8 DEF_y__h3165;
  tUInt8 DEF_x__h3164;
  tUInt8 DEF_y__h3314;
  tUInt8 DEF_x__h3313;
  tUInt8 DEF_y__h3312;
  tUInt8 DEF_x__h3311;
  tUInt8 DEF_y__h3461;
  tUInt8 DEF_x__h3460;
  tUInt8 DEF_y__h3459;
  tUInt8 DEF_x__h3458;
  tUInt8 DEF_y__h3608;
  tUInt8 DEF_x__h3607;
  tUInt8 DEF_y__h3606;
  tUInt8 DEF_x__h3605;
  tUInt8 DEF_y__h3755;
  tUInt8 DEF_x__h3754;
  tUInt8 DEF_y__h3753;
  tUInt8 DEF_x__h3752;
  tUInt8 DEF_y__h3902;
  tUInt8 DEF_x__h3901;
  tUInt8 DEF_y__h3900;
  tUInt8 DEF_x__h3899;
  tUInt8 DEF_y__h4049;
  tUInt8 DEF_x__h4048;
  tUInt8 DEF_y__h4047;
  tUInt8 DEF_x__h4046;
  tUInt8 DEF_y__h4196;
  tUInt8 DEF_x__h4195;
  tUInt8 DEF_y__h4194;
  tUInt8 DEF_x__h4193;
  tUInt8 DEF_y__h4343;
  tUInt8 DEF_x__h4342;
  tUInt8 DEF_y__h4341;
  tUInt8 DEF_x__h4340;
  tUInt8 DEF_y__h4490;
  tUInt8 DEF_x__h4489;
  tUInt8 DEF_y__h4488;
  tUInt8 DEF_x__h4487;
  tUInt8 DEF_y__h4637;
  tUInt8 DEF_x__h4636;
  tUInt8 DEF_y__h4635;
  tUInt8 DEF_x__h4634;
  tUInt8 DEF_y__h4784;
  tUInt8 DEF_x__h4783;
  tUInt8 DEF_y__h4782;
  tUInt8 DEF_x__h4781;
  tUInt8 DEF_y__h4931;
  tUInt8 DEF_x__h4930;
  tUInt8 DEF_y__h4929;
  tUInt8 DEF_x__h4928;
  tUInt8 DEF_y__h5078;
  tUInt8 DEF_x__h5077;
  tUInt8 DEF_y__h5076;
  tUInt8 DEF_x__h5075;
  tUInt8 DEF_y__h5225;
  tUInt8 DEF_x__h5224;
  tUInt8 DEF_y__h5223;
  tUInt8 DEF_x__h5222;
  tUInt8 DEF_y__h5372;
  tUInt8 DEF_x__h5371;
  tUInt8 DEF_y__h5370;
  tUInt8 DEF_x__h5369;
  tUInt8 DEF_y__h5519;
  tUInt8 DEF_x__h5518;
  tUInt8 DEF_y__h5517;
  tUInt8 DEF_x__h5516;
  tUInt8 DEF_y__h5666;
  tUInt8 DEF_x__h5665;
  tUInt8 DEF_y__h5664;
  tUInt8 DEF_x__h5663;
  tUInt8 DEF_carry_out__h43;
  tUInt8 DEF_c_in__h5647;
  tUInt8 DEF_x__h5741;
  tUInt8 DEF_c_in__h5500;
  tUInt8 DEF_x__h5594;
  tUInt8 DEF_c_in__h5353;
  tUInt8 DEF_x__h5447;
  tUInt8 DEF_c_in__h5206;
  tUInt8 DEF_x__h5300;
  tUInt8 DEF_c_in__h5059;
  tUInt8 DEF_x__h5153;
  tUInt8 DEF_c_in__h4912;
  tUInt8 DEF_x__h5006;
  tUInt8 DEF_c_in__h4765;
  tUInt8 DEF_x__h4859;
  tUInt8 DEF_c_in__h4618;
  tUInt8 DEF_x__h4712;
  tUInt8 DEF_c_in__h4471;
  tUInt8 DEF_x__h4565;
  tUInt8 DEF_c_in__h4324;
  tUInt8 DEF_x__h4418;
  tUInt8 DEF_c_in__h4177;
  tUInt8 DEF_x__h4271;
  tUInt8 DEF_c_in__h4030;
  tUInt8 DEF_x__h4124;
  tUInt8 DEF_c_in__h3883;
  tUInt8 DEF_x__h3977;
  tUInt8 DEF_c_in__h3736;
  tUInt8 DEF_x__h3830;
  tUInt8 DEF_c_in__h3589;
  tUInt8 DEF_x__h3683;
  tUInt8 DEF_c_in__h3442;
  tUInt8 DEF_x__h3536;
  tUInt8 DEF_c_in__h3295;
  tUInt8 DEF_x__h3389;
  tUInt8 DEF_c_in__h3148;
  tUInt8 DEF_x__h3242;
  tUInt8 DEF_c_in__h3001;
  tUInt8 DEF_x__h3095;
  tUInt8 DEF_c_in__h2854;
  tUInt8 DEF_x__h2948;
  tUInt8 DEF_c_in__h2707;
  tUInt8 DEF_x__h2801;
  tUInt8 DEF_c_in__h2560;
  tUInt8 DEF_x__h2654;
  tUInt8 DEF_c_in__h2413;
  tUInt8 DEF_x__h2507;
  tUInt8 DEF_c_in__h2266;
  tUInt8 DEF_x__h2360;
  tUInt8 DEF_c_in__h2119;
  tUInt8 DEF_x__h2213;
  tUInt8 DEF_c_in__h1972;
  tUInt8 DEF_x__h2066;
  tUInt8 DEF_c_in__h1825;
  tUInt8 DEF_x__h1919;
  tUInt8 DEF_c_in__h1678;
  tUInt8 DEF_x__h1772;
  tUInt8 DEF_c_in__h1531;
  tUInt8 DEF_x__h1625;
  tUInt8 DEF_c_in__h1384;
  tUInt8 DEF_x__h1478;
  tUInt8 DEF_x__h1331;
  tUInt8 DEF_x__h1187;
  tUInt8 DEF_x__h1112;
  tUInt8 DEF_x__h1234;
  tUInt8 DEF_x__h1382;
  tUInt8 DEF_x__h1529;
  tUInt8 DEF_x__h1676;
  tUInt8 DEF_x__h1823;
  tUInt8 DEF_x__h1970;
  tUInt8 DEF_x__h2117;
  tUInt8 DEF_x__h2264;
  tUInt8 DEF_x__h2411;
  tUInt8 DEF_x__h2558;
  tUInt8 DEF_x__h2705;
  tUInt8 DEF_x__h2852;
  tUInt8 DEF_x__h2999;
  tUInt8 DEF_x__h3146;
  tUInt8 DEF_x__h3293;
  tUInt8 DEF_x__h3440;
  tUInt8 DEF_x__h3587;
  tUInt8 DEF_x__h3734;
  tUInt8 DEF_x__h3881;
  tUInt8 DEF_x__h4028;
  tUInt8 DEF_x__h4175;
  tUInt8 DEF_x__h4322;
  tUInt8 DEF_x__h4469;
  tUInt8 DEF_x__h4616;
  tUInt8 DEF_x__h4763;
  tUInt8 DEF_x__h4910;
  tUInt8 DEF_x__h5057;
  tUInt8 DEF_x__h5204;
  tUInt8 DEF_x__h5351;
  tUInt8 DEF_x__h5498;
  tUInt8 DEF_x__h5645;
  tUInt8 DEF_y__h1113;
  tUInt8 DEF_y__h1235;
  tUInt8 DEF_y__h1383;
  tUInt8 DEF_y__h1530;
  tUInt8 DEF_y__h1677;
  tUInt8 DEF_y__h1824;
  tUInt8 DEF_y__h1971;
  tUInt8 DEF_y__h2118;
  tUInt8 DEF_y__h2265;
  tUInt8 DEF_y__h2412;
  tUInt8 DEF_y__h2559;
  tUInt8 DEF_y__h2706;
  tUInt8 DEF_y__h2853;
  tUInt8 DEF_y__h3000;
  tUInt8 DEF_y__h3147;
  tUInt8 DEF_y__h3294;
  tUInt8 DEF_y__h3441;
  tUInt8 DEF_y__h3588;
  tUInt8 DEF_y__h3735;
  tUInt8 DEF_y__h3882;
  tUInt8 DEF_y__h4029;
  tUInt8 DEF_y__h4176;
  tUInt8 DEF_y__h4323;
  tUInt8 DEF_y__h4470;
  tUInt8 DEF_y__h4617;
  tUInt8 DEF_y__h4764;
  tUInt8 DEF_y__h4911;
  tUInt8 DEF_y__h5058;
  tUInt8 DEF_y__h5205;
  tUInt8 DEF_y__h5352;
  tUInt8 DEF_y__h5499;
  tUInt32 DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2;
  tUInt8 DEF_y__h5646;
  tUInt8 DEF_c_in__h1236;
  tUInt64 PORT_add;
  DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 = ARG_add_add_or_sub ? ~ARG_add_y : ARG_add_y;
  DEF_y__h5646 = (tUInt8)(DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 31u);
  DEF_y__h5499 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 30u));
  DEF_y__h5352 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 29u));
  DEF_y__h5058 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 27u));
  DEF_y__h5205 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 28u));
  DEF_y__h4911 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 26u));
  DEF_y__h4764 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 25u));
  DEF_y__h4617 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 24u));
  DEF_y__h4470 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 23u));
  DEF_y__h4323 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 22u));
  DEF_y__h4176 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 21u));
  DEF_y__h3882 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 19u));
  DEF_y__h4029 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 20u));
  DEF_y__h3735 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 18u));
  DEF_y__h3588 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 17u));
  DEF_y__h3294 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 15u));
  DEF_y__h3441 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 16u));
  DEF_y__h3147 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 14u));
  DEF_y__h3000 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 13u));
  DEF_y__h2706 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 11u));
  DEF_y__h2853 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 12u));
  DEF_y__h2559 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 10u));
  DEF_y__h2412 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 9u));
  DEF_y__h2265 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 8u));
  DEF_y__h2118 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 7u));
  DEF_y__h1971 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 6u));
  DEF_y__h1824 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 5u));
  DEF_y__h1530 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 3u));
  DEF_y__h1677 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 4u));
  DEF_y__h1383 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 2u));
  DEF_y__h1235 = (tUInt8)((tUInt8)1u & (DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2 >> 1u));
  DEF_y__h1113 = (tUInt8)((tUInt8)1u & DEF_IF_add_add_or_sub_THEN_INV_add_y_ELSE_add_y___d2);
  DEF_x__h5645 = (tUInt8)(ARG_add_x >> 31u);
  DEF_x__h5498 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 30u));
  DEF_x__h5351 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 29u));
  DEF_x__h5057 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 27u));
  DEF_x__h5204 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 28u));
  DEF_x__h4910 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 26u));
  DEF_x__h4763 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 25u));
  DEF_x__h4616 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 24u));
  DEF_x__h4469 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 23u));
  DEF_x__h4322 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 22u));
  DEF_x__h4175 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 21u));
  DEF_x__h3881 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 19u));
  DEF_x__h4028 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 20u));
  DEF_x__h3734 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 18u));
  DEF_x__h3587 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 17u));
  DEF_x__h3293 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 15u));
  DEF_x__h3440 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 16u));
  DEF_x__h3146 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 14u));
  DEF_x__h2999 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 13u));
  DEF_x__h2705 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 11u));
  DEF_x__h2852 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 12u));
  DEF_x__h2558 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 10u));
  DEF_x__h2411 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 9u));
  DEF_x__h2264 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 8u));
  DEF_x__h2117 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 7u));
  DEF_x__h1970 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 6u));
  DEF_x__h1823 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 5u));
  DEF_x__h1529 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 3u));
  DEF_x__h1676 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 4u));
  DEF_x__h1382 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 2u));
  DEF_x__h1234 = (tUInt8)((tUInt8)1u & (ARG_add_x >> 1u));
  DEF_x__h1112 = (tUInt8)((tUInt8)1u & ARG_add_x);
  DEF_x__h1187 = DEF_x__h1112 ^ DEF_y__h1113;
  DEF_x__h1331 = DEF_x__h1234 ^ DEF_y__h1235;
  DEF_x__h1478 = DEF_x__h1382 ^ DEF_y__h1383;
  DEF_x__h1625 = DEF_x__h1529 ^ DEF_y__h1530;
  DEF_x__h1772 = DEF_x__h1676 ^ DEF_y__h1677;
  DEF_x__h1919 = DEF_x__h1823 ^ DEF_y__h1824;
  DEF_x__h2066 = DEF_x__h1970 ^ DEF_y__h1971;
  DEF_x__h2213 = DEF_x__h2117 ^ DEF_y__h2118;
  DEF_x__h2360 = DEF_x__h2264 ^ DEF_y__h2265;
  DEF_x__h2948 = DEF_x__h2852 ^ DEF_y__h2853;
  DEF_x__h2507 = DEF_x__h2411 ^ DEF_y__h2412;
  DEF_x__h2654 = DEF_x__h2558 ^ DEF_y__h2559;
  DEF_x__h2801 = DEF_x__h2705 ^ DEF_y__h2706;
  DEF_x__h3095 = DEF_x__h2999 ^ DEF_y__h3000;
  DEF_x__h3242 = DEF_x__h3146 ^ DEF_y__h3147;
  DEF_x__h3389 = DEF_x__h3293 ^ DEF_y__h3294;
  DEF_x__h3536 = DEF_x__h3440 ^ DEF_y__h3441;
  DEF_x__h3683 = DEF_x__h3587 ^ DEF_y__h3588;
  DEF_x__h3830 = DEF_x__h3734 ^ DEF_y__h3735;
  DEF_x__h3977 = DEF_x__h3881 ^ DEF_y__h3882;
  DEF_x__h4124 = DEF_x__h4028 ^ DEF_y__h4029;
  DEF_x__h4271 = DEF_x__h4175 ^ DEF_y__h4176;
  DEF_x__h4418 = DEF_x__h4322 ^ DEF_y__h4323;
  DEF_x__h4565 = DEF_x__h4469 ^ DEF_y__h4470;
  DEF_x__h4712 = DEF_x__h4616 ^ DEF_y__h4617;
  DEF_x__h4859 = DEF_x__h4763 ^ DEF_y__h4764;
  DEF_x__h5006 = DEF_x__h4910 ^ DEF_y__h4911;
  DEF_x__h5153 = DEF_x__h5057 ^ DEF_y__h5058;
  DEF_x__h5741 = DEF_x__h5645 ^ DEF_y__h5646;
  DEF_x__h5300 = DEF_x__h5204 ^ DEF_y__h5205;
  DEF_x__h5447 = DEF_x__h5351 ^ DEF_y__h5352;
  DEF_x__h5594 = DEF_x__h5498 ^ DEF_y__h5499;
  DEF_y__h5666 = DEF_x__h5645 & DEF_y__h5646;
  DEF_y__h5519 = DEF_x__h5498 & DEF_y__h5499;
  DEF_y__h5372 = DEF_x__h5351 & DEF_y__h5352;
  DEF_y__h5225 = DEF_x__h5204 & DEF_y__h5205;
  DEF_y__h5078 = DEF_x__h5057 & DEF_y__h5058;
  DEF_y__h4931 = DEF_x__h4910 & DEF_y__h4911;
  DEF_y__h4784 = DEF_x__h4763 & DEF_y__h4764;
  DEF_y__h4637 = DEF_x__h4616 & DEF_y__h4617;
  DEF_y__h4490 = DEF_x__h4469 & DEF_y__h4470;
  DEF_y__h4343 = DEF_x__h4322 & DEF_y__h4323;
  DEF_y__h4196 = DEF_x__h4175 & DEF_y__h4176;
  DEF_y__h4049 = DEF_x__h4028 & DEF_y__h4029;
  DEF_y__h3902 = DEF_x__h3881 & DEF_y__h3882;
  DEF_y__h3755 = DEF_x__h3734 & DEF_y__h3735;
  DEF_y__h3608 = DEF_x__h3587 & DEF_y__h3588;
  DEF_y__h3461 = DEF_x__h3440 & DEF_y__h3441;
  DEF_y__h3314 = DEF_x__h3293 & DEF_y__h3294;
  DEF_y__h3167 = DEF_x__h3146 & DEF_y__h3147;
  DEF_y__h3020 = DEF_x__h2999 & DEF_y__h3000;
  DEF_y__h2873 = DEF_x__h2852 & DEF_y__h2853;
  DEF_y__h2726 = DEF_x__h2705 & DEF_y__h2706;
  DEF_y__h2579 = DEF_x__h2558 & DEF_y__h2559;
  DEF_y__h2432 = DEF_x__h2411 & DEF_y__h2412;
  DEF_y__h2285 = DEF_x__h2264 & DEF_y__h2265;
  DEF_y__h2138 = DEF_x__h2117 & DEF_y__h2118;
  DEF_y__h1991 = DEF_x__h1970 & DEF_y__h1971;
  DEF_y__h1844 = DEF_x__h1823 & DEF_y__h1824;
  DEF_y__h1697 = DEF_x__h1676 & DEF_y__h1677;
  DEF_y__h1550 = DEF_x__h1529 & DEF_y__h1530;
  DEF_y__h1403 = DEF_x__h1382 & DEF_y__h1383;
  DEF_y__h1255 = DEF_x__h1234 & DEF_y__h1235;
  DEF_y__h1130 = DEF_x__h1112 & ARG_add_add_or_sub;
  DEF_x__h1131 = DEF_y__h1113 & ARG_add_add_or_sub;
  DEF_y__h1132 = DEF_x__h1112 & DEF_y__h1113;
  DEF_x__h1129 = DEF_x__h1131 | DEF_y__h1132;
  DEF_c_in__h1236 = (tUInt8)((tUInt8)1u & (DEF_x__h1129 | DEF_y__h1130 ? 1u : 0u));
  DEF_y__h1253 = DEF_x__h1234 & DEF_c_in__h1236;
  DEF_x__h1254 = DEF_y__h1235 & DEF_c_in__h1236;
  DEF_x__h1252 = DEF_x__h1254 | DEF_y__h1255;
  DEF_c_in__h1384 = DEF_x__h1252 | DEF_y__h1253;
  DEF_y__h1401 = DEF_x__h1382 & DEF_c_in__h1384;
  DEF_x__h1402 = DEF_y__h1383 & DEF_c_in__h1384;
  DEF_x__h1400 = DEF_x__h1402 | DEF_y__h1403;
  DEF_c_in__h1531 = DEF_x__h1400 | DEF_y__h1401;
  DEF_y__h1548 = DEF_x__h1529 & DEF_c_in__h1531;
  DEF_x__h1549 = DEF_y__h1530 & DEF_c_in__h1531;
  DEF_x__h1547 = DEF_x__h1549 | DEF_y__h1550;
  DEF_c_in__h1678 = DEF_x__h1547 | DEF_y__h1548;
  DEF_y__h1695 = DEF_x__h1676 & DEF_c_in__h1678;
  DEF_x__h1696 = DEF_y__h1677 & DEF_c_in__h1678;
  DEF_x__h1694 = DEF_x__h1696 | DEF_y__h1697;
  DEF_c_in__h1825 = DEF_x__h1694 | DEF_y__h1695;
  DEF_y__h1842 = DEF_x__h1823 & DEF_c_in__h1825;
  DEF_x__h1843 = DEF_y__h1824 & DEF_c_in__h1825;
  DEF_x__h1841 = DEF_x__h1843 | DEF_y__h1844;
  DEF_c_in__h1972 = DEF_x__h1841 | DEF_y__h1842;
  DEF_y__h1989 = DEF_x__h1970 & DEF_c_in__h1972;
  DEF_x__h1990 = DEF_y__h1971 & DEF_c_in__h1972;
  DEF_x__h1988 = DEF_x__h1990 | DEF_y__h1991;
  DEF_c_in__h2119 = DEF_x__h1988 | DEF_y__h1989;
  DEF_y__h2136 = DEF_x__h2117 & DEF_c_in__h2119;
  DEF_x__h2137 = DEF_y__h2118 & DEF_c_in__h2119;
  DEF_x__h2135 = DEF_x__h2137 | DEF_y__h2138;
  DEF_c_in__h2266 = DEF_x__h2135 | DEF_y__h2136;
  DEF_y__h2283 = DEF_x__h2264 & DEF_c_in__h2266;
  DEF_x__h2284 = DEF_y__h2265 & DEF_c_in__h2266;
  DEF_x__h2282 = DEF_x__h2284 | DEF_y__h2285;
  DEF_c_in__h2413 = DEF_x__h2282 | DEF_y__h2283;
  DEF_y__h2430 = DEF_x__h2411 & DEF_c_in__h2413;
  DEF_x__h2431 = DEF_y__h2412 & DEF_c_in__h2413;
  DEF_x__h2429 = DEF_x__h2431 | DEF_y__h2432;
  DEF_c_in__h2560 = DEF_x__h2429 | DEF_y__h2430;
  DEF_y__h2577 = DEF_x__h2558 & DEF_c_in__h2560;
  DEF_x__h2578 = DEF_y__h2559 & DEF_c_in__h2560;
  DEF_x__h2576 = DEF_x__h2578 | DEF_y__h2579;
  DEF_c_in__h2707 = DEF_x__h2576 | DEF_y__h2577;
  DEF_y__h2724 = DEF_x__h2705 & DEF_c_in__h2707;
  DEF_x__h2725 = DEF_y__h2706 & DEF_c_in__h2707;
  DEF_x__h2723 = DEF_x__h2725 | DEF_y__h2726;
  DEF_c_in__h2854 = DEF_x__h2723 | DEF_y__h2724;
  DEF_y__h2871 = DEF_x__h2852 & DEF_c_in__h2854;
  DEF_x__h2872 = DEF_y__h2853 & DEF_c_in__h2854;
  DEF_x__h2870 = DEF_x__h2872 | DEF_y__h2873;
  DEF_c_in__h3001 = DEF_x__h2870 | DEF_y__h2871;
  DEF_y__h3018 = DEF_x__h2999 & DEF_c_in__h3001;
  DEF_x__h3019 = DEF_y__h3000 & DEF_c_in__h3001;
  DEF_x__h3017 = DEF_x__h3019 | DEF_y__h3020;
  DEF_c_in__h3148 = DEF_x__h3017 | DEF_y__h3018;
  DEF_y__h3165 = DEF_x__h3146 & DEF_c_in__h3148;
  DEF_x__h3166 = DEF_y__h3147 & DEF_c_in__h3148;
  DEF_x__h3164 = DEF_x__h3166 | DEF_y__h3167;
  DEF_c_in__h3295 = DEF_x__h3164 | DEF_y__h3165;
  DEF_y__h3312 = DEF_x__h3293 & DEF_c_in__h3295;
  DEF_x__h3313 = DEF_y__h3294 & DEF_c_in__h3295;
  DEF_x__h3311 = DEF_x__h3313 | DEF_y__h3314;
  DEF_c_in__h3442 = DEF_x__h3311 | DEF_y__h3312;
  DEF_y__h3459 = DEF_x__h3440 & DEF_c_in__h3442;
  DEF_x__h3460 = DEF_y__h3441 & DEF_c_in__h3442;
  DEF_x__h3458 = DEF_x__h3460 | DEF_y__h3461;
  DEF_c_in__h3589 = DEF_x__h3458 | DEF_y__h3459;
  DEF_y__h3606 = DEF_x__h3587 & DEF_c_in__h3589;
  DEF_x__h3607 = DEF_y__h3588 & DEF_c_in__h3589;
  DEF_x__h3605 = DEF_x__h3607 | DEF_y__h3608;
  DEF_c_in__h3736 = DEF_x__h3605 | DEF_y__h3606;
  DEF_y__h3753 = DEF_x__h3734 & DEF_c_in__h3736;
  DEF_x__h3754 = DEF_y__h3735 & DEF_c_in__h3736;
  DEF_x__h3752 = DEF_x__h3754 | DEF_y__h3755;
  DEF_c_in__h3883 = DEF_x__h3752 | DEF_y__h3753;
  DEF_y__h3900 = DEF_x__h3881 & DEF_c_in__h3883;
  DEF_x__h3901 = DEF_y__h3882 & DEF_c_in__h3883;
  DEF_x__h3899 = DEF_x__h3901 | DEF_y__h3902;
  DEF_c_in__h4030 = DEF_x__h3899 | DEF_y__h3900;
  DEF_y__h4047 = DEF_x__h4028 & DEF_c_in__h4030;
  DEF_x__h4048 = DEF_y__h4029 & DEF_c_in__h4030;
  DEF_x__h4046 = DEF_x__h4048 | DEF_y__h4049;
  DEF_c_in__h4177 = DEF_x__h4046 | DEF_y__h4047;
  DEF_y__h4194 = DEF_x__h4175 & DEF_c_in__h4177;
  DEF_x__h4195 = DEF_y__h4176 & DEF_c_in__h4177;
  DEF_x__h4193 = DEF_x__h4195 | DEF_y__h4196;
  DEF_c_in__h4324 = DEF_x__h4193 | DEF_y__h4194;
  DEF_y__h4341 = DEF_x__h4322 & DEF_c_in__h4324;
  DEF_x__h4342 = DEF_y__h4323 & DEF_c_in__h4324;
  DEF_x__h4340 = DEF_x__h4342 | DEF_y__h4343;
  DEF_c_in__h4471 = DEF_x__h4340 | DEF_y__h4341;
  DEF_y__h4488 = DEF_x__h4469 & DEF_c_in__h4471;
  DEF_x__h4489 = DEF_y__h4470 & DEF_c_in__h4471;
  DEF_x__h4487 = DEF_x__h4489 | DEF_y__h4490;
  DEF_c_in__h4618 = DEF_x__h4487 | DEF_y__h4488;
  DEF_y__h4635 = DEF_x__h4616 & DEF_c_in__h4618;
  DEF_x__h4636 = DEF_y__h4617 & DEF_c_in__h4618;
  DEF_x__h4634 = DEF_x__h4636 | DEF_y__h4637;
  DEF_c_in__h4765 = DEF_x__h4634 | DEF_y__h4635;
  DEF_y__h4782 = DEF_x__h4763 & DEF_c_in__h4765;
  DEF_x__h4783 = DEF_y__h4764 & DEF_c_in__h4765;
  DEF_x__h4781 = DEF_x__h4783 | DEF_y__h4784;
  DEF_c_in__h4912 = DEF_x__h4781 | DEF_y__h4782;
  DEF_y__h4929 = DEF_x__h4910 & DEF_c_in__h4912;
  DEF_x__h4930 = DEF_y__h4911 & DEF_c_in__h4912;
  DEF_x__h4928 = DEF_x__h4930 | DEF_y__h4931;
  DEF_c_in__h5059 = DEF_x__h4928 | DEF_y__h4929;
  DEF_y__h5076 = DEF_x__h5057 & DEF_c_in__h5059;
  DEF_x__h5077 = DEF_y__h5058 & DEF_c_in__h5059;
  DEF_x__h5075 = DEF_x__h5077 | DEF_y__h5078;
  DEF_c_in__h5206 = DEF_x__h5075 | DEF_y__h5076;
  DEF_y__h5223 = DEF_x__h5204 & DEF_c_in__h5206;
  DEF_x__h5224 = DEF_y__h5205 & DEF_c_in__h5206;
  DEF_x__h5222 = DEF_x__h5224 | DEF_y__h5225;
  DEF_c_in__h5353 = DEF_x__h5222 | DEF_y__h5223;
  DEF_y__h5370 = DEF_x__h5351 & DEF_c_in__h5353;
  DEF_x__h5371 = DEF_y__h5352 & DEF_c_in__h5353;
  DEF_x__h5369 = DEF_x__h5371 | DEF_y__h5372;
  DEF_c_in__h5500 = DEF_x__h5369 | DEF_y__h5370;
  DEF_y__h5517 = DEF_x__h5498 & DEF_c_in__h5500;
  DEF_x__h5518 = DEF_y__h5499 & DEF_c_in__h5500;
  DEF_x__h5516 = DEF_x__h5518 | DEF_y__h5519;
  DEF_c_in__h5647 = DEF_x__h5516 | DEF_y__h5517;
  DEF_y__h5664 = DEF_x__h5645 & DEF_c_in__h5647;
  DEF_x__h5665 = DEF_y__h5646 & DEF_c_in__h5647;
  DEF_x__h5663 = DEF_x__h5665 | DEF_y__h5666;
  DEF_carry_out__h43 = DEF_x__h5663 | DEF_y__h5664;
  DEF_add_x_BIT_31_24_XOR_IF_add_add_or_sub_THEN_INV_ETC___d310 = (((((((((((((((((((((((((((((((((tUInt32)(DEF_x__h5741 ^ DEF_c_in__h5647)) << 31u) | (((tUInt32)(DEF_x__h5594 ^ DEF_c_in__h5500)) << 30u)) | (((tUInt32)(DEF_x__h5447 ^ DEF_c_in__h5353)) << 29u)) | (((tUInt32)(DEF_x__h5300 ^ DEF_c_in__h5206)) << 28u)) | (((tUInt32)(DEF_x__h5153 ^ DEF_c_in__h5059)) << 27u)) | (((tUInt32)(DEF_x__h5006 ^ DEF_c_in__h4912)) << 26u)) | (((tUInt32)(DEF_x__h4859 ^ DEF_c_in__h4765)) << 25u)) | (((tUInt32)(DEF_x__h4712 ^ DEF_c_in__h4618)) << 24u)) | (((tUInt32)(DEF_x__h4565 ^ DEF_c_in__h4471)) << 23u)) | (((tUInt32)(DEF_x__h4418 ^ DEF_c_in__h4324)) << 22u)) | (((tUInt32)(DEF_x__h4271 ^ DEF_c_in__h4177)) << 21u)) | (((tUInt32)(DEF_x__h4124 ^ DEF_c_in__h4030)) << 20u)) | (((tUInt32)(DEF_x__h3977 ^ DEF_c_in__h3883)) << 19u)) | (((tUInt32)(DEF_x__h3830 ^ DEF_c_in__h3736)) << 18u)) | (((tUInt32)(DEF_x__h3683 ^ DEF_c_in__h3589)) << 17u)) | (((tUInt32)(DEF_x__h3536 ^ DEF_c_in__h3442)) << 16u)) | (((tUInt32)(DEF_x__h3389 ^ DEF_c_in__h3295)) << 15u)) | (((tUInt32)(DEF_x__h3242 ^ DEF_c_in__h3148)) << 14u)) | (((tUInt32)(DEF_x__h3095 ^ DEF_c_in__h3001)) << 13u)) | (((tUInt32)(DEF_x__h2948 ^ DEF_c_in__h2854)) << 12u)) | (((tUInt32)(DEF_x__h2801 ^ DEF_c_in__h2707)) << 11u)) | (((tUInt32)(DEF_x__h2654 ^ DEF_c_in__h2560)) << 10u)) | (((tUInt32)(DEF_x__h2507 ^ DEF_c_in__h2413)) << 9u)) | (((tUInt32)(DEF_x__h2360 ^ DEF_c_in__h2266)) << 8u)) | (((tUInt32)(DEF_x__h2213 ^ DEF_c_in__h2119)) << 7u)) | (((tUInt32)(DEF_x__h2066 ^ DEF_c_in__h1972)) << 6u)) | (((tUInt32)(DEF_x__h1919 ^ DEF_c_in__h1825)) << 5u)) | (((tUInt32)(DEF_x__h1772 ^ DEF_c_in__h1678)) << 4u)) | (((tUInt32)(DEF_x__h1625 ^ DEF_c_in__h1531)) << 3u)) | (((tUInt32)(DEF_x__h1478 ^ DEF_c_in__h1384)) << 2u)) | (((tUInt32)(DEF_x__h1331 ^ DEF_c_in__h1236)) << 1u)) | (tUInt32)((tUInt8)((tUInt8)1u & (DEF_x__h1187 ^ ARG_add_add_or_sub ? 1u : 0u)));
  PORT_add = 8589934591llu & ((((tUInt64)(DEF_carry_out__h43)) << 32u) | (tUInt64)(DEF_add_x_BIT_31_24_XOR_IF_add_add_or_sub_THEN_INV_ETC___d310));
  return PORT_add;
}

tUInt8 MOD_mkAdder32Bit::METH_RDY_add()
{
  tUInt8 DEF_CAN_FIRE_add;
  tUInt8 PORT_RDY_add;
  DEF_CAN_FIRE_add = (tUInt8)1u;
  PORT_RDY_add = DEF_CAN_FIRE_add;
  return PORT_RDY_add;
}


/* Reset routines */

void MOD_mkAdder32Bit::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkAdder32Bit::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkAdder32Bit::dump_state(unsigned int indent)
{
}


/* VCD dumping routines */

unsigned int MOD_mkAdder32Bit::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 1u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkAdder32Bit::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkAdder32Bit &backing)
{
  vcd_defs(dt, backing);
}

void MOD_mkAdder32Bit::vcd_defs(tVCDDumpType dt, MOD_mkAdder32Bit &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
    }
}
