/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Tue Oct 22 19:30:12 IST 2024
 * 
 */

/* Generation options: */
#ifndef __mkFpMultiplier_h__
#define __mkFpMultiplier_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkAdder8Bit.h"
#include "mkMultiplier8Bit.h"


/* Class declaration for the mkFpMultiplier module */
class MOD_mkFpMultiplier : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkAdder8Bit INST_ifc_adder8_1;
  MOD_mkAdder8Bit INST_ifc_adder8_2;
  MOD_mkAdder8Bit INST_ifc_adder8_3;
  MOD_mkMultiplier8Bit INST_ifc_multiplier8;
 
 /* Constructor */
 public:
  MOD_mkFpMultiplier(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  tUInt32 METH_fp_mul(tUInt32 ARG_fp_mul_a, tUInt32 ARG_fp_mul_b);
  tUInt8 METH_RDY_fp_mul();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkFpMultiplier &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkFpMultiplier &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkFpMultiplier &backing);
};

#endif /* ifndef __mkFpMultiplier_h__ */
