/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Sun Nov 17 07:27:54 IST 2024
 * 
 */

/* Generation options: */
#ifndef __mkSystolic_h__
#define __mkSystolic_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkMacSystolic.h"


/* Class declaration for the mkSystolic module */
class MOD_mkSystolic : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_counter;
  MOD_mkMacSystolic INST_systolic_array_0_0;
  MOD_mkMacSystolic INST_systolic_array_0_1;
  MOD_mkMacSystolic INST_systolic_array_0_2;
  MOD_mkMacSystolic INST_systolic_array_0_3;
  MOD_mkMacSystolic INST_systolic_array_1_0;
  MOD_mkMacSystolic INST_systolic_array_1_1;
  MOD_mkMacSystolic INST_systolic_array_1_2;
  MOD_mkMacSystolic INST_systolic_array_1_3;
  MOD_mkMacSystolic INST_systolic_array_2_0;
  MOD_mkMacSystolic INST_systolic_array_2_1;
  MOD_mkMacSystolic INST_systolic_array_2_2;
  MOD_mkMacSystolic INST_systolic_array_2_3;
  MOD_mkMacSystolic INST_systolic_array_3_0;
  MOD_mkMacSystolic INST_systolic_array_3_1;
  MOD_mkMacSystolic INST_systolic_array_3_2;
  MOD_mkMacSystolic INST_systolic_array_3_3;
 
 /* Constructor */
 public:
  MOD_mkSystolic(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_initialise_systolic;
  tUWide PORT_get_result;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_initialise_systolic;
  tUInt8 DEF_systolic_array_0_1_RDY_set_a____d177;
  tUInt8 DEF_systolic_array_0_0_RDY_set_s1_or_s2____d260;
  tUInt8 DEF_systolic_array_0_0_RDY_set_c____d254;
  tUInt8 DEF_systolic_array_3_3_RDY_set_s1_or_s2____d145;
  tUInt8 DEF_systolic_array_3_3_RDY_set_c____d141;
  tUInt8 DEF_systolic_array_3_3_RDY_set_a____d218;
  tUInt8 DEF_systolic_array_3_2_RDY_set_s1_or_s2____d144;
  tUInt8 DEF_systolic_array_3_2_RDY_set_c____d140;
  tUInt8 DEF_systolic_array_3_2_RDY_set_a____d199;
  tUInt8 DEF_systolic_array_3_1_RDY_set_s1_or_s2____d143;
  tUInt8 DEF_systolic_array_3_1_RDY_set_c____d139;
  tUInt8 DEF_systolic_array_3_1_RDY_set_a____d180;
  tUInt8 DEF_systolic_array_3_0_RDY_set_s1_or_s2____d142;
  tUInt8 DEF_systolic_array_3_0_RDY_set_c____d138;
  tUInt8 DEF_systolic_array_2_3_RDY_set_s1_or_s2____d106;
  tUInt8 DEF_systolic_array_2_3_RDY_set_c____d102;
  tUInt8 DEF_systolic_array_2_3_RDY_set_a____d217;
  tUInt8 DEF_systolic_array_2_2_RDY_set_s1_or_s2____d105;
  tUInt8 DEF_systolic_array_2_2_RDY_set_c____d101;
  tUInt8 DEF_systolic_array_2_2_RDY_set_a____d198;
  tUInt8 DEF_systolic_array_2_1_RDY_set_s1_or_s2____d104;
  tUInt8 DEF_systolic_array_2_1_RDY_set_c____d100;
  tUInt8 DEF_systolic_array_2_1_RDY_set_a____d179;
  tUInt8 DEF_systolic_array_2_0_RDY_set_s1_or_s2____d103;
  tUInt8 DEF_systolic_array_2_0_RDY_set_c____d99;
  tUInt8 DEF_systolic_array_1_3_RDY_set_s1_or_s2____d67;
  tUInt8 DEF_systolic_array_1_3_RDY_set_c____d63;
  tUInt8 DEF_systolic_array_1_3_RDY_set_a____d216;
  tUInt8 DEF_systolic_array_1_2_RDY_set_s1_or_s2____d66;
  tUInt8 DEF_systolic_array_1_2_RDY_set_c____d62;
  tUInt8 DEF_systolic_array_1_2_RDY_set_a____d197;
  tUInt8 DEF_systolic_array_1_1_RDY_set_s1_or_s2____d65;
  tUInt8 DEF_systolic_array_1_1_RDY_set_c____d61;
  tUInt8 DEF_systolic_array_1_1_RDY_set_a____d178;
  tUInt8 DEF_systolic_array_1_0_RDY_set_s1_or_s2____d64;
  tUInt8 DEF_systolic_array_1_0_RDY_set_c____d60;
  tUInt8 DEF_systolic_array_0_3_RDY_set_s1_or_s2____d263;
  tUInt8 DEF_systolic_array_0_3_RDY_set_c____d257;
  tUInt8 DEF_systolic_array_0_3_RDY_set_a____d215;
  tUInt8 DEF_systolic_array_0_2_RDY_set_s1_or_s2____d262;
  tUInt8 DEF_systolic_array_0_2_RDY_set_c____d256;
  tUInt8 DEF_systolic_array_0_2_RDY_set_a____d196;
  tUInt8 DEF_systolic_array_0_1_RDY_set_s1_or_s2____d261;
  tUInt8 DEF_systolic_array_0_1_RDY_set_c____d255;
 
 /* Local definitions */
 private:
 
 /* Rules */
 public:
  void RL_count_up();
  void RL_shift_b_row1();
  void RL_shift_b_row2();
  void RL_shift_b_row3();
  void RL_shift_c_row1();
  void RL_shift_c_row2();
  void RL_shift_c_row3();
  void RL_shift_a_column1();
  void RL_shift_a_column2();
  void RL_shift_a_column3();
 
 /* Methods */
 public:
  void METH_set_A_matrix(tUInt64 ARG_set_A_matrix_a_matrix);
  tUInt8 METH_RDY_set_A_matrix();
  void METH_set_B_matrix(tUInt64 ARG_set_B_matrix_b_matrix);
  tUInt8 METH_RDY_set_B_matrix();
  void METH_set_C_row1(tUInt32 ARG_set_C_row1_c_val);
  tUInt8 METH_RDY_set_C_row1();
  void METH_set_s1_or_s2_row1(tUInt8 ARG_set_s1_or_s2_row1_s1_or_s2_in);
  tUInt8 METH_RDY_set_s1_or_s2_row1();
  void METH_initialise_systolic(tUInt8 ARG_initialise_systolic_s1_or_s2_in);
  tUInt8 METH_RDY_initialise_systolic();
  void METH_set_state_systolic(tUInt8 ARG_set_state_systolic_state_in);
  tUInt8 METH_RDY_set_state_systolic();
  tUWide METH_get_result();
  tUInt8 METH_RDY_get_result();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkSystolic &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkSystolic &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkSystolic &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkSystolic &backing);
};

#endif /* ifndef __mkSystolic_h__ */
