/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Sun Nov 17 07:27:54 IST 2024
 * 
 */
#include "bluesim_primitives.h"
#include "mkTopSystolic.h"


/* Literal declarations */
static unsigned int const UWide_literal_128_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr[] = { 2863311530u,
											2863311530u,
											2863311530u,
											2863311530u };
static tUWide const UWide_literal_128_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa(128u,
									UWide_literal_128_haaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_arr);


/* Constructor */
MOD_mkTopSystolic::MOD_mkTopSystolic(tSimStateHdl simHdl, char const *name, Module *parent)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    INST_a_matrix_top_0_0(simHdl, "a_matrix_top_0_0", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_0_1(simHdl, "a_matrix_top_0_1", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_0_2(simHdl, "a_matrix_top_0_2", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_0_3(simHdl, "a_matrix_top_0_3", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_1_0(simHdl, "a_matrix_top_1_0", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_1_1(simHdl, "a_matrix_top_1_1", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_1_2(simHdl, "a_matrix_top_1_2", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_1_3(simHdl, "a_matrix_top_1_3", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_2_0(simHdl, "a_matrix_top_2_0", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_2_1(simHdl, "a_matrix_top_2_1", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_2_2(simHdl, "a_matrix_top_2_2", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_2_3(simHdl, "a_matrix_top_2_3", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_3_0(simHdl, "a_matrix_top_3_0", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_3_1(simHdl, "a_matrix_top_3_1", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_3_2(simHdl, "a_matrix_top_3_2", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_3_3(simHdl, "a_matrix_top_3_3", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_4_0(simHdl, "a_matrix_top_4_0", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_4_1(simHdl, "a_matrix_top_4_1", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_4_2(simHdl, "a_matrix_top_4_2", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_4_3(simHdl, "a_matrix_top_4_3", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_5_0(simHdl, "a_matrix_top_5_0", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_5_1(simHdl, "a_matrix_top_5_1", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_5_2(simHdl, "a_matrix_top_5_2", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_5_3(simHdl, "a_matrix_top_5_3", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_6_0(simHdl, "a_matrix_top_6_0", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_6_1(simHdl, "a_matrix_top_6_1", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_6_2(simHdl, "a_matrix_top_6_2", this, 16u, 0u, (tUInt8)0u),
    INST_a_matrix_top_6_3(simHdl, "a_matrix_top_6_3", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_0_0(simHdl, "b_matrix_top_0_0", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_0_1(simHdl, "b_matrix_top_0_1", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_0_2(simHdl, "b_matrix_top_0_2", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_0_3(simHdl, "b_matrix_top_0_3", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_1_0(simHdl, "b_matrix_top_1_0", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_1_1(simHdl, "b_matrix_top_1_1", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_1_2(simHdl, "b_matrix_top_1_2", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_1_3(simHdl, "b_matrix_top_1_3", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_2_0(simHdl, "b_matrix_top_2_0", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_2_1(simHdl, "b_matrix_top_2_1", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_2_2(simHdl, "b_matrix_top_2_2", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_2_3(simHdl, "b_matrix_top_2_3", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_3_0(simHdl, "b_matrix_top_3_0", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_3_1(simHdl, "b_matrix_top_3_1", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_3_2(simHdl, "b_matrix_top_3_2", this, 16u, 0u, (tUInt8)0u),
    INST_b_matrix_top_3_3(simHdl, "b_matrix_top_3_3", this, 16u, 0u, (tUInt8)0u),
    INST_c_matrix_top_0_0(simHdl, "c_matrix_top_0_0", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_0_1(simHdl, "c_matrix_top_0_1", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_0_2(simHdl, "c_matrix_top_0_2", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_0_3(simHdl, "c_matrix_top_0_3", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_1_0(simHdl, "c_matrix_top_1_0", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_1_1(simHdl, "c_matrix_top_1_1", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_1_2(simHdl, "c_matrix_top_1_2", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_1_3(simHdl, "c_matrix_top_1_3", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_2_0(simHdl, "c_matrix_top_2_0", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_2_1(simHdl, "c_matrix_top_2_1", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_2_2(simHdl, "c_matrix_top_2_2", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_2_3(simHdl, "c_matrix_top_2_3", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_3_0(simHdl, "c_matrix_top_3_0", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_3_1(simHdl, "c_matrix_top_3_1", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_3_2(simHdl, "c_matrix_top_3_2", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_3_3(simHdl, "c_matrix_top_3_3", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_4_0(simHdl, "c_matrix_top_4_0", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_4_1(simHdl, "c_matrix_top_4_1", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_4_2(simHdl, "c_matrix_top_4_2", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_4_3(simHdl, "c_matrix_top_4_3", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_5_0(simHdl, "c_matrix_top_5_0", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_5_1(simHdl, "c_matrix_top_5_1", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_5_2(simHdl, "c_matrix_top_5_2", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_5_3(simHdl, "c_matrix_top_5_3", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_6_0(simHdl, "c_matrix_top_6_0", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_6_1(simHdl, "c_matrix_top_6_1", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_6_2(simHdl, "c_matrix_top_6_2", this, 32u, 0u, (tUInt8)0u),
    INST_c_matrix_top_6_3(simHdl, "c_matrix_top_6_3", this, 32u, 0u, (tUInt8)0u),
    INST_counter(simHdl, "counter", this, 32u, 0u, (tUInt8)0u),
    INST_s1_or_s2_systolic(simHdl, "s1_or_s2_systolic", this, 1u, (tUInt8)0u, (tUInt8)0u),
    INST_systolic_unit(simHdl, "systolic_unit", this),
    PORT_RST_N((tUInt8)1u),
    DEF_systolic_unit_get_result___d106(128u),
    DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161(256u),
    DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154(96u),
    DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159(96u),
    DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167(128u),
    DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171(96u)
{
  PORT_set_A_matrix_in_a_matrix_in.setSize(256u);
  PORT_set_A_matrix_in_a_matrix_in.clear();
  PORT_set_B_matrix_in_b_matrix_in.setSize(256u);
  PORT_set_B_matrix_in_b_matrix_in.clear();
  PORT_get_matrix_mul_result.setSize(512u);
  PORT_get_matrix_mul_result.clear();
  symbol_count = 101u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkTopSystolic::init_symbols_0()
{
  init_symbol(&symbols[0u], "a_matrix_top_0_0", SYM_MODULE, &INST_a_matrix_top_0_0);
  init_symbol(&symbols[1u], "a_matrix_top_0_1", SYM_MODULE, &INST_a_matrix_top_0_1);
  init_symbol(&symbols[2u], "a_matrix_top_0_2", SYM_MODULE, &INST_a_matrix_top_0_2);
  init_symbol(&symbols[3u], "a_matrix_top_0_3", SYM_MODULE, &INST_a_matrix_top_0_3);
  init_symbol(&symbols[4u], "a_matrix_top_1_0", SYM_MODULE, &INST_a_matrix_top_1_0);
  init_symbol(&symbols[5u], "a_matrix_top_1_1", SYM_MODULE, &INST_a_matrix_top_1_1);
  init_symbol(&symbols[6u], "a_matrix_top_1_2", SYM_MODULE, &INST_a_matrix_top_1_2);
  init_symbol(&symbols[7u], "a_matrix_top_1_3", SYM_MODULE, &INST_a_matrix_top_1_3);
  init_symbol(&symbols[8u], "a_matrix_top_2_0", SYM_MODULE, &INST_a_matrix_top_2_0);
  init_symbol(&symbols[9u], "a_matrix_top_2_1", SYM_MODULE, &INST_a_matrix_top_2_1);
  init_symbol(&symbols[10u], "a_matrix_top_2_2", SYM_MODULE, &INST_a_matrix_top_2_2);
  init_symbol(&symbols[11u], "a_matrix_top_2_3", SYM_MODULE, &INST_a_matrix_top_2_3);
  init_symbol(&symbols[12u], "a_matrix_top_3_0", SYM_MODULE, &INST_a_matrix_top_3_0);
  init_symbol(&symbols[13u], "a_matrix_top_3_1", SYM_MODULE, &INST_a_matrix_top_3_1);
  init_symbol(&symbols[14u], "a_matrix_top_3_2", SYM_MODULE, &INST_a_matrix_top_3_2);
  init_symbol(&symbols[15u], "a_matrix_top_3_3", SYM_MODULE, &INST_a_matrix_top_3_3);
  init_symbol(&symbols[16u], "a_matrix_top_4_0", SYM_MODULE, &INST_a_matrix_top_4_0);
  init_symbol(&symbols[17u], "a_matrix_top_4_1", SYM_MODULE, &INST_a_matrix_top_4_1);
  init_symbol(&symbols[18u], "a_matrix_top_4_2", SYM_MODULE, &INST_a_matrix_top_4_2);
  init_symbol(&symbols[19u], "a_matrix_top_4_3", SYM_MODULE, &INST_a_matrix_top_4_3);
  init_symbol(&symbols[20u], "a_matrix_top_5_0", SYM_MODULE, &INST_a_matrix_top_5_0);
  init_symbol(&symbols[21u], "a_matrix_top_5_1", SYM_MODULE, &INST_a_matrix_top_5_1);
  init_symbol(&symbols[22u], "a_matrix_top_5_2", SYM_MODULE, &INST_a_matrix_top_5_2);
  init_symbol(&symbols[23u], "a_matrix_top_5_3", SYM_MODULE, &INST_a_matrix_top_5_3);
  init_symbol(&symbols[24u], "a_matrix_top_6_0", SYM_MODULE, &INST_a_matrix_top_6_0);
  init_symbol(&symbols[25u], "a_matrix_top_6_1", SYM_MODULE, &INST_a_matrix_top_6_1);
  init_symbol(&symbols[26u], "a_matrix_top_6_2", SYM_MODULE, &INST_a_matrix_top_6_2);
  init_symbol(&symbols[27u], "a_matrix_top_6_3", SYM_MODULE, &INST_a_matrix_top_6_3);
  init_symbol(&symbols[28u], "b_matrix_top_0_0", SYM_MODULE, &INST_b_matrix_top_0_0);
  init_symbol(&symbols[29u], "b_matrix_top_0_1", SYM_MODULE, &INST_b_matrix_top_0_1);
  init_symbol(&symbols[30u], "b_matrix_top_0_2", SYM_MODULE, &INST_b_matrix_top_0_2);
  init_symbol(&symbols[31u], "b_matrix_top_0_3", SYM_MODULE, &INST_b_matrix_top_0_3);
  init_symbol(&symbols[32u], "b_matrix_top_1_0", SYM_MODULE, &INST_b_matrix_top_1_0);
  init_symbol(&symbols[33u], "b_matrix_top_1_1", SYM_MODULE, &INST_b_matrix_top_1_1);
  init_symbol(&symbols[34u], "b_matrix_top_1_2", SYM_MODULE, &INST_b_matrix_top_1_2);
  init_symbol(&symbols[35u], "b_matrix_top_1_3", SYM_MODULE, &INST_b_matrix_top_1_3);
  init_symbol(&symbols[36u], "b_matrix_top_2_0", SYM_MODULE, &INST_b_matrix_top_2_0);
  init_symbol(&symbols[37u], "b_matrix_top_2_1", SYM_MODULE, &INST_b_matrix_top_2_1);
  init_symbol(&symbols[38u], "b_matrix_top_2_2", SYM_MODULE, &INST_b_matrix_top_2_2);
  init_symbol(&symbols[39u], "b_matrix_top_2_3", SYM_MODULE, &INST_b_matrix_top_2_3);
  init_symbol(&symbols[40u], "b_matrix_top_3_0", SYM_MODULE, &INST_b_matrix_top_3_0);
  init_symbol(&symbols[41u], "b_matrix_top_3_1", SYM_MODULE, &INST_b_matrix_top_3_1);
  init_symbol(&symbols[42u], "b_matrix_top_3_2", SYM_MODULE, &INST_b_matrix_top_3_2);
  init_symbol(&symbols[43u], "b_matrix_top_3_3", SYM_MODULE, &INST_b_matrix_top_3_3);
  init_symbol(&symbols[44u], "c_matrix_top_0_0", SYM_MODULE, &INST_c_matrix_top_0_0);
  init_symbol(&symbols[45u], "c_matrix_top_0_1", SYM_MODULE, &INST_c_matrix_top_0_1);
  init_symbol(&symbols[46u], "c_matrix_top_0_2", SYM_MODULE, &INST_c_matrix_top_0_2);
  init_symbol(&symbols[47u], "c_matrix_top_0_3", SYM_MODULE, &INST_c_matrix_top_0_3);
  init_symbol(&symbols[48u], "c_matrix_top_1_0", SYM_MODULE, &INST_c_matrix_top_1_0);
  init_symbol(&symbols[49u], "c_matrix_top_1_1", SYM_MODULE, &INST_c_matrix_top_1_1);
  init_symbol(&symbols[50u], "c_matrix_top_1_2", SYM_MODULE, &INST_c_matrix_top_1_2);
  init_symbol(&symbols[51u], "c_matrix_top_1_3", SYM_MODULE, &INST_c_matrix_top_1_3);
  init_symbol(&symbols[52u], "c_matrix_top_2_0", SYM_MODULE, &INST_c_matrix_top_2_0);
  init_symbol(&symbols[53u], "c_matrix_top_2_1", SYM_MODULE, &INST_c_matrix_top_2_1);
  init_symbol(&symbols[54u], "c_matrix_top_2_2", SYM_MODULE, &INST_c_matrix_top_2_2);
  init_symbol(&symbols[55u], "c_matrix_top_2_3", SYM_MODULE, &INST_c_matrix_top_2_3);
  init_symbol(&symbols[56u], "c_matrix_top_3_0", SYM_MODULE, &INST_c_matrix_top_3_0);
  init_symbol(&symbols[57u], "c_matrix_top_3_1", SYM_MODULE, &INST_c_matrix_top_3_1);
  init_symbol(&symbols[58u], "c_matrix_top_3_2", SYM_MODULE, &INST_c_matrix_top_3_2);
  init_symbol(&symbols[59u], "c_matrix_top_3_3", SYM_MODULE, &INST_c_matrix_top_3_3);
  init_symbol(&symbols[60u], "c_matrix_top_4_0", SYM_MODULE, &INST_c_matrix_top_4_0);
  init_symbol(&symbols[61u], "c_matrix_top_4_1", SYM_MODULE, &INST_c_matrix_top_4_1);
  init_symbol(&symbols[62u], "c_matrix_top_4_2", SYM_MODULE, &INST_c_matrix_top_4_2);
  init_symbol(&symbols[63u], "c_matrix_top_4_3", SYM_MODULE, &INST_c_matrix_top_4_3);
  init_symbol(&symbols[64u], "c_matrix_top_5_0", SYM_MODULE, &INST_c_matrix_top_5_0);
  init_symbol(&symbols[65u], "c_matrix_top_5_1", SYM_MODULE, &INST_c_matrix_top_5_1);
  init_symbol(&symbols[66u], "c_matrix_top_5_2", SYM_MODULE, &INST_c_matrix_top_5_2);
  init_symbol(&symbols[67u], "c_matrix_top_5_3", SYM_MODULE, &INST_c_matrix_top_5_3);
  init_symbol(&symbols[68u], "c_matrix_top_6_0", SYM_MODULE, &INST_c_matrix_top_6_0);
  init_symbol(&symbols[69u], "c_matrix_top_6_1", SYM_MODULE, &INST_c_matrix_top_6_1);
  init_symbol(&symbols[70u], "c_matrix_top_6_2", SYM_MODULE, &INST_c_matrix_top_6_2);
  init_symbol(&symbols[71u], "c_matrix_top_6_3", SYM_MODULE, &INST_c_matrix_top_6_3);
  init_symbol(&symbols[72u], "counter", SYM_MODULE, &INST_counter);
  init_symbol(&symbols[73u], "get_matrix_mul_result", SYM_PORT, &PORT_get_matrix_mul_result, 512u);
  init_symbol(&symbols[74u], "RL_a_column0", SYM_RULE);
  init_symbol(&symbols[75u], "RL_a_column1", SYM_RULE);
  init_symbol(&symbols[76u], "RL_a_column2", SYM_RULE);
  init_symbol(&symbols[77u], "RL_a_column3", SYM_RULE);
  init_symbol(&symbols[78u], "RL_a_column4", SYM_RULE);
  init_symbol(&symbols[79u], "RL_a_column5", SYM_RULE);
  init_symbol(&symbols[80u], "RL_a_column6", SYM_RULE);
  init_symbol(&symbols[81u], "RL_a_dummy1", SYM_RULE);
  init_symbol(&symbols[82u], "RL_a_dummy2", SYM_RULE);
  init_symbol(&symbols[83u], "RL_a_dummy3", SYM_RULE);
  init_symbol(&symbols[84u], "RL_b_row0", SYM_RULE);
  init_symbol(&symbols[85u], "RL_b_row1", SYM_RULE);
  init_symbol(&symbols[86u], "RL_b_row2", SYM_RULE);
  init_symbol(&symbols[87u], "RL_b_row3", SYM_RULE);
  init_symbol(&symbols[88u], "RL_c_column0", SYM_RULE);
  init_symbol(&symbols[89u], "RL_c_column1", SYM_RULE);
  init_symbol(&symbols[90u], "RL_c_column2", SYM_RULE);
  init_symbol(&symbols[91u], "RL_c_column3", SYM_RULE);
  init_symbol(&symbols[92u], "RL_c_column4", SYM_RULE);
  init_symbol(&symbols[93u], "RL_c_column5", SYM_RULE);
  init_symbol(&symbols[94u], "RL_c_column6", SYM_RULE);
  init_symbol(&symbols[95u], "RL_count_up", SYM_RULE);
  init_symbol(&symbols[96u], "s1_or_s2_systolic", SYM_MODULE, &INST_s1_or_s2_systolic);
  init_symbol(&symbols[97u],
	      "set_A_matrix_in_a_matrix_in",
	      SYM_PORT,
	      &PORT_set_A_matrix_in_a_matrix_in,
	      256u);
  init_symbol(&symbols[98u],
	      "set_B_matrix_in_b_matrix_in",
	      SYM_PORT,
	      &PORT_set_B_matrix_in_b_matrix_in,
	      256u);
  init_symbol(&symbols[99u], "systolic_unit", SYM_MODULE, &INST_systolic_unit);
  init_symbol(&symbols[100u], "x__h18595", SYM_DEF, &DEF_x__h18595, 32u);
}


/* Rule actions */

void MOD_mkTopSystolic::RL_b_row3()
{
  tUInt64 DEF_b_matrix_top_3_3_CONCAT_b_matrix_top_3_2_0_CON_ETC___d13;
  tUInt32 DEF_b_matrix_top_3_0__h4676;
  tUInt32 DEF_b_matrix_top_3_1__h4616;
  tUInt32 DEF_b_matrix_top_3_2__h4556;
  tUInt32 DEF_b_matrix_top_3_3__h4496;
  DEF_b_matrix_top_3_3__h4496 = INST_b_matrix_top_3_3.METH_read();
  DEF_b_matrix_top_3_2__h4556 = INST_b_matrix_top_3_2.METH_read();
  DEF_b_matrix_top_3_1__h4616 = INST_b_matrix_top_3_1.METH_read();
  DEF_b_matrix_top_3_0__h4676 = INST_b_matrix_top_3_0.METH_read();
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  DEF_b_matrix_top_3_3_CONCAT_b_matrix_top_3_2_0_CON_ETC___d13 = (((((tUInt64)(DEF_b_matrix_top_3_3__h4496)) << 48u) | (((tUInt64)(DEF_b_matrix_top_3_2__h4556)) << 32u)) | (((tUInt64)(DEF_b_matrix_top_3_1__h4616)) << 16u)) | (tUInt64)(DEF_b_matrix_top_3_0__h4676);
  INST_systolic_unit.METH_set_state_systolic((tUInt8)1u);
  INST_systolic_unit.METH_initialise_systolic(DEF_s1_or_s2_in__h14273);
  INST_systolic_unit.METH_set_B_matrix(DEF_b_matrix_top_3_3_CONCAT_b_matrix_top_3_2_0_CON_ETC___d13);
}

void MOD_mkTopSystolic::RL_b_row2()
{
  tUInt64 DEF_b_matrix_top_2_3_6_CONCAT_b_matrix_top_2_2_7_8_ETC___d21;
  tUInt32 DEF_b_matrix_top_2_0__h5417;
  tUInt32 DEF_b_matrix_top_2_1__h5357;
  tUInt32 DEF_b_matrix_top_2_2__h5297;
  tUInt32 DEF_b_matrix_top_2_3__h5237;
  DEF_b_matrix_top_2_3__h5237 = INST_b_matrix_top_2_3.METH_read();
  DEF_b_matrix_top_2_2__h5297 = INST_b_matrix_top_2_2.METH_read();
  DEF_b_matrix_top_2_1__h5357 = INST_b_matrix_top_2_1.METH_read();
  DEF_b_matrix_top_2_0__h5417 = INST_b_matrix_top_2_0.METH_read();
  DEF_b_matrix_top_2_3_6_CONCAT_b_matrix_top_2_2_7_8_ETC___d21 = (((((tUInt64)(DEF_b_matrix_top_2_3__h5237)) << 48u) | (((tUInt64)(DEF_b_matrix_top_2_2__h5297)) << 32u)) | (((tUInt64)(DEF_b_matrix_top_2_1__h5357)) << 16u)) | (tUInt64)(DEF_b_matrix_top_2_0__h5417);
  INST_systolic_unit.METH_set_B_matrix(DEF_b_matrix_top_2_3_6_CONCAT_b_matrix_top_2_2_7_8_ETC___d21);
}

void MOD_mkTopSystolic::RL_b_row1()
{
  tUInt64 DEF_b_matrix_top_1_3_4_CONCAT_b_matrix_top_1_2_5_6_ETC___d29;
  tUInt32 DEF_b_matrix_top_1_0__h6157;
  tUInt32 DEF_b_matrix_top_1_1__h6097;
  tUInt32 DEF_b_matrix_top_1_2__h6037;
  tUInt32 DEF_b_matrix_top_1_3__h5977;
  DEF_b_matrix_top_1_3__h5977 = INST_b_matrix_top_1_3.METH_read();
  DEF_b_matrix_top_1_2__h6037 = INST_b_matrix_top_1_2.METH_read();
  DEF_b_matrix_top_1_1__h6097 = INST_b_matrix_top_1_1.METH_read();
  DEF_b_matrix_top_1_0__h6157 = INST_b_matrix_top_1_0.METH_read();
  DEF_b_matrix_top_1_3_4_CONCAT_b_matrix_top_1_2_5_6_ETC___d29 = (((((tUInt64)(DEF_b_matrix_top_1_3__h5977)) << 48u) | (((tUInt64)(DEF_b_matrix_top_1_2__h6037)) << 32u)) | (((tUInt64)(DEF_b_matrix_top_1_1__h6097)) << 16u)) | (tUInt64)(DEF_b_matrix_top_1_0__h6157);
  INST_systolic_unit.METH_set_B_matrix(DEF_b_matrix_top_1_3_4_CONCAT_b_matrix_top_1_2_5_6_ETC___d29);
}

void MOD_mkTopSystolic::RL_b_row0()
{
  tUInt64 DEF_b_matrix_top_0_3_2_CONCAT_b_matrix_top_0_2_3_4_ETC___d37;
  tUInt32 DEF_b_matrix_top_0_0__h6908;
  tUInt32 DEF_b_matrix_top_0_1__h6848;
  tUInt32 DEF_b_matrix_top_0_2__h6788;
  tUInt32 DEF_b_matrix_top_0_3__h6728;
  DEF_b_matrix_top_0_3__h6728 = INST_b_matrix_top_0_3.METH_read();
  DEF_b_matrix_top_0_2__h6788 = INST_b_matrix_top_0_2.METH_read();
  DEF_b_matrix_top_0_1__h6848 = INST_b_matrix_top_0_1.METH_read();
  DEF_b_matrix_top_0_0__h6908 = INST_b_matrix_top_0_0.METH_read();
  DEF_b_matrix_top_0_3_2_CONCAT_b_matrix_top_0_2_3_4_ETC___d37 = (((((tUInt64)(DEF_b_matrix_top_0_3__h6728)) << 48u) | (((tUInt64)(DEF_b_matrix_top_0_2__h6788)) << 32u)) | (((tUInt64)(DEF_b_matrix_top_0_1__h6848)) << 16u)) | (tUInt64)(DEF_b_matrix_top_0_0__h6908);
  INST_systolic_unit.METH_set_B_matrix(DEF_b_matrix_top_0_3_2_CONCAT_b_matrix_top_0_2_3_4_ETC___d37);
  INST_systolic_unit.METH_set_state_systolic((tUInt8)0u);
}

void MOD_mkTopSystolic::RL_a_column0()
{
  tUInt64 DEF_a_matrix_top_6_3_0_CONCAT_a_matrix_top_6_2_1_2_ETC___d45;
  tUInt32 DEF_a_matrix_top_6_0__h7877;
  tUInt32 DEF_a_matrix_top_6_1__h7817;
  tUInt32 DEF_a_matrix_top_6_2__h7757;
  tUInt32 DEF_a_matrix_top_6_3__h7697;
  DEF_a_matrix_top_6_3__h7697 = INST_a_matrix_top_6_3.METH_read();
  DEF_a_matrix_top_6_2__h7757 = INST_a_matrix_top_6_2.METH_read();
  DEF_a_matrix_top_6_1__h7817 = INST_a_matrix_top_6_1.METH_read();
  DEF_a_matrix_top_6_0__h7877 = INST_a_matrix_top_6_0.METH_read();
  DEF_a_matrix_top_6_3_0_CONCAT_a_matrix_top_6_2_1_2_ETC___d45 = (((((tUInt64)(DEF_a_matrix_top_6_3__h7697)) << 48u) | (((tUInt64)(DEF_a_matrix_top_6_2__h7757)) << 32u)) | (((tUInt64)(DEF_a_matrix_top_6_1__h7817)) << 16u)) | (tUInt64)(DEF_a_matrix_top_6_0__h7877);
  INST_systolic_unit.METH_set_A_matrix(DEF_a_matrix_top_6_3_0_CONCAT_a_matrix_top_6_2_1_2_ETC___d45);
}

void MOD_mkTopSystolic::RL_a_column1()
{
  tUInt64 DEF_a_matrix_top_5_3_2_CONCAT_a_matrix_top_5_2_3_4_ETC___d57;
  tUInt32 DEF_a_matrix_top_5_0__h8628;
  tUInt32 DEF_a_matrix_top_5_1__h8568;
  tUInt32 DEF_a_matrix_top_5_2__h8508;
  tUInt32 DEF_a_matrix_top_5_3__h8448;
  DEF_a_matrix_top_5_3__h8448 = INST_a_matrix_top_5_3.METH_read();
  DEF_a_matrix_top_5_2__h8508 = INST_a_matrix_top_5_2.METH_read();
  DEF_a_matrix_top_5_1__h8568 = INST_a_matrix_top_5_1.METH_read();
  DEF_a_matrix_top_5_0__h8628 = INST_a_matrix_top_5_0.METH_read();
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  DEF_a_matrix_top_5_3_2_CONCAT_a_matrix_top_5_2_3_4_ETC___d57 = (((((tUInt64)(DEF_a_matrix_top_5_3__h8448)) << 48u) | (((tUInt64)(DEF_a_matrix_top_5_2__h8508)) << 32u)) | (((tUInt64)(DEF_a_matrix_top_5_1__h8568)) << 16u)) | (tUInt64)(DEF_a_matrix_top_5_0__h8628);
  INST_systolic_unit.METH_set_A_matrix(DEF_a_matrix_top_5_3_2_CONCAT_a_matrix_top_5_2_3_4_ETC___d57);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_a_column2()
{
  tUInt64 DEF_a_matrix_top_4_3_0_CONCAT_a_matrix_top_4_2_1_2_ETC___d65;
  tUInt32 DEF_a_matrix_top_4_0__h9420;
  tUInt32 DEF_a_matrix_top_4_1__h9360;
  tUInt32 DEF_a_matrix_top_4_2__h9300;
  tUInt32 DEF_a_matrix_top_4_3__h9240;
  DEF_a_matrix_top_4_3__h9240 = INST_a_matrix_top_4_3.METH_read();
  DEF_a_matrix_top_4_2__h9300 = INST_a_matrix_top_4_2.METH_read();
  DEF_a_matrix_top_4_1__h9360 = INST_a_matrix_top_4_1.METH_read();
  DEF_a_matrix_top_4_0__h9420 = INST_a_matrix_top_4_0.METH_read();
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  DEF_a_matrix_top_4_3_0_CONCAT_a_matrix_top_4_2_1_2_ETC___d65 = (((((tUInt64)(DEF_a_matrix_top_4_3__h9240)) << 48u) | (((tUInt64)(DEF_a_matrix_top_4_2__h9300)) << 32u)) | (((tUInt64)(DEF_a_matrix_top_4_1__h9360)) << 16u)) | (tUInt64)(DEF_a_matrix_top_4_0__h9420);
  INST_systolic_unit.METH_set_A_matrix(DEF_a_matrix_top_4_3_0_CONCAT_a_matrix_top_4_2_1_2_ETC___d65);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_a_column3()
{
  tUInt64 DEF_a_matrix_top_3_3_8_CONCAT_a_matrix_top_3_2_9_0_ETC___d73;
  tUInt32 DEF_a_matrix_top_3_0__h10201;
  tUInt32 DEF_a_matrix_top_3_1__h10141;
  tUInt32 DEF_a_matrix_top_3_2__h10081;
  tUInt32 DEF_a_matrix_top_3_3__h10021;
  DEF_a_matrix_top_3_3__h10021 = INST_a_matrix_top_3_3.METH_read();
  DEF_a_matrix_top_3_2__h10081 = INST_a_matrix_top_3_2.METH_read();
  DEF_a_matrix_top_3_1__h10141 = INST_a_matrix_top_3_1.METH_read();
  DEF_a_matrix_top_3_0__h10201 = INST_a_matrix_top_3_0.METH_read();
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  DEF_a_matrix_top_3_3_8_CONCAT_a_matrix_top_3_2_9_0_ETC___d73 = (((((tUInt64)(DEF_a_matrix_top_3_3__h10021)) << 48u) | (((tUInt64)(DEF_a_matrix_top_3_2__h10081)) << 32u)) | (((tUInt64)(DEF_a_matrix_top_3_1__h10141)) << 16u)) | (tUInt64)(DEF_a_matrix_top_3_0__h10201);
  INST_systolic_unit.METH_set_A_matrix(DEF_a_matrix_top_3_3_8_CONCAT_a_matrix_top_3_2_9_0_ETC___d73);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_a_column4()
{
  tUInt64 DEF_a_matrix_top_2_3_6_CONCAT_a_matrix_top_2_2_7_8_ETC___d81;
  tUInt32 DEF_a_matrix_top_2_0__h10982;
  tUInt32 DEF_a_matrix_top_2_1__h10922;
  tUInt32 DEF_a_matrix_top_2_2__h10862;
  tUInt32 DEF_a_matrix_top_2_3__h10802;
  DEF_a_matrix_top_2_3__h10802 = INST_a_matrix_top_2_3.METH_read();
  DEF_a_matrix_top_2_2__h10862 = INST_a_matrix_top_2_2.METH_read();
  DEF_a_matrix_top_2_1__h10922 = INST_a_matrix_top_2_1.METH_read();
  DEF_a_matrix_top_2_0__h10982 = INST_a_matrix_top_2_0.METH_read();
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  DEF_a_matrix_top_2_3_6_CONCAT_a_matrix_top_2_2_7_8_ETC___d81 = (((((tUInt64)(DEF_a_matrix_top_2_3__h10802)) << 48u) | (((tUInt64)(DEF_a_matrix_top_2_2__h10862)) << 32u)) | (((tUInt64)(DEF_a_matrix_top_2_1__h10922)) << 16u)) | (tUInt64)(DEF_a_matrix_top_2_0__h10982);
  INST_systolic_unit.METH_set_A_matrix(DEF_a_matrix_top_2_3_6_CONCAT_a_matrix_top_2_2_7_8_ETC___d81);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_a_column5()
{
  tUInt64 DEF_a_matrix_top_1_3_4_CONCAT_a_matrix_top_1_2_5_6_ETC___d89;
  tUInt32 DEF_a_matrix_top_1_0__h11763;
  tUInt32 DEF_a_matrix_top_1_1__h11703;
  tUInt32 DEF_a_matrix_top_1_2__h11643;
  tUInt32 DEF_a_matrix_top_1_3__h11583;
  DEF_a_matrix_top_1_3__h11583 = INST_a_matrix_top_1_3.METH_read();
  DEF_a_matrix_top_1_2__h11643 = INST_a_matrix_top_1_2.METH_read();
  DEF_a_matrix_top_1_1__h11703 = INST_a_matrix_top_1_1.METH_read();
  DEF_a_matrix_top_1_0__h11763 = INST_a_matrix_top_1_0.METH_read();
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  DEF_a_matrix_top_1_3_4_CONCAT_a_matrix_top_1_2_5_6_ETC___d89 = (((((tUInt64)(DEF_a_matrix_top_1_3__h11583)) << 48u) | (((tUInt64)(DEF_a_matrix_top_1_2__h11643)) << 32u)) | (((tUInt64)(DEF_a_matrix_top_1_1__h11703)) << 16u)) | (tUInt64)(DEF_a_matrix_top_1_0__h11763);
  INST_systolic_unit.METH_set_A_matrix(DEF_a_matrix_top_1_3_4_CONCAT_a_matrix_top_1_2_5_6_ETC___d89);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_a_column6()
{
  tUInt64 DEF_a_matrix_top_0_3_2_CONCAT_a_matrix_top_0_2_3_4_ETC___d97;
  tUInt32 DEF_a_matrix_top_0_0__h12544;
  tUInt32 DEF_a_matrix_top_0_1__h12484;
  tUInt32 DEF_a_matrix_top_0_2__h12424;
  tUInt32 DEF_a_matrix_top_0_3__h12364;
  DEF_a_matrix_top_0_3__h12364 = INST_a_matrix_top_0_3.METH_read();
  DEF_a_matrix_top_0_2__h12424 = INST_a_matrix_top_0_2.METH_read();
  DEF_a_matrix_top_0_1__h12484 = INST_a_matrix_top_0_1.METH_read();
  DEF_a_matrix_top_0_0__h12544 = INST_a_matrix_top_0_0.METH_read();
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  DEF_a_matrix_top_0_3_2_CONCAT_a_matrix_top_0_2_3_4_ETC___d97 = (((((tUInt64)(DEF_a_matrix_top_0_3__h12364)) << 48u) | (((tUInt64)(DEF_a_matrix_top_0_2__h12424)) << 32u)) | (((tUInt64)(DEF_a_matrix_top_0_1__h12484)) << 16u)) | (tUInt64)(DEF_a_matrix_top_0_0__h12544);
  INST_systolic_unit.METH_set_A_matrix(DEF_a_matrix_top_0_3_2_CONCAT_a_matrix_top_0_2_3_4_ETC___d97);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_a_dummy1()
{
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  INST_systolic_unit.METH_set_A_matrix(0llu);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_a_dummy2()
{
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  INST_systolic_unit.METH_set_A_matrix(0llu);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_a_dummy3()
{
  DEF_s1_or_s2_in__h14273 = INST_s1_or_s2_systolic.METH_read();
  INST_systolic_unit.METH_set_A_matrix(0llu);
  INST_systolic_unit.METH_set_C_row1(0u);
  INST_systolic_unit.METH_set_s1_or_s2_row1(DEF_s1_or_s2_in__h14273);
}

void MOD_mkTopSystolic::RL_c_column6()
{
  tUWide DEF_AVMeth_systolic_unit_get_result(128u, false);
  DEF_AVMeth_systolic_unit_get_result = INST_systolic_unit.METH_get_result();
  DEF_systolic_unit_get_result___d106 = DEF_AVMeth_systolic_unit_get_result;
  DEF_x__h19196 = DEF_systolic_unit_get_result___d106.get_whole_word(3u);
  DEF_x__h19091 = DEF_systolic_unit_get_result___d106.get_whole_word(2u);
  DEF_x__h18986 = DEF_systolic_unit_get_result___d106.get_whole_word(1u);
  DEF_x__h18784 = DEF_systolic_unit_get_result___d106.get_whole_word(0u);
  INST_c_matrix_top_6_0.METH_write(DEF_x__h18784);
  INST_c_matrix_top_6_1.METH_write(DEF_x__h18986);
  INST_c_matrix_top_6_2.METH_write(DEF_x__h19091);
  INST_c_matrix_top_6_3.METH_write(DEF_x__h19196);
}

void MOD_mkTopSystolic::RL_c_column5()
{
  tUWide DEF_AVMeth_systolic_unit_get_result(128u, false);
  DEF_AVMeth_systolic_unit_get_result = INST_systolic_unit.METH_get_result();
  DEF_systolic_unit_get_result___d106 = DEF_AVMeth_systolic_unit_get_result;
  DEF_x__h19196 = DEF_systolic_unit_get_result___d106.get_whole_word(3u);
  DEF_x__h19091 = DEF_systolic_unit_get_result___d106.get_whole_word(2u);
  DEF_x__h18986 = DEF_systolic_unit_get_result___d106.get_whole_word(1u);
  DEF_x__h18784 = DEF_systolic_unit_get_result___d106.get_whole_word(0u);
  INST_c_matrix_top_5_0.METH_write(DEF_x__h18784);
  INST_c_matrix_top_5_1.METH_write(DEF_x__h18986);
  INST_c_matrix_top_5_2.METH_write(DEF_x__h19091);
  INST_c_matrix_top_5_3.METH_write(DEF_x__h19196);
}

void MOD_mkTopSystolic::RL_c_column4()
{
  tUWide DEF_AVMeth_systolic_unit_get_result(128u, false);
  DEF_AVMeth_systolic_unit_get_result = INST_systolic_unit.METH_get_result();
  DEF_systolic_unit_get_result___d106 = DEF_AVMeth_systolic_unit_get_result;
  DEF_x__h19196 = DEF_systolic_unit_get_result___d106.get_whole_word(3u);
  DEF_x__h19091 = DEF_systolic_unit_get_result___d106.get_whole_word(2u);
  DEF_x__h18986 = DEF_systolic_unit_get_result___d106.get_whole_word(1u);
  DEF_x__h18784 = DEF_systolic_unit_get_result___d106.get_whole_word(0u);
  INST_c_matrix_top_4_0.METH_write(DEF_x__h18784);
  INST_c_matrix_top_4_1.METH_write(DEF_x__h18986);
  INST_c_matrix_top_4_2.METH_write(DEF_x__h19091);
  INST_c_matrix_top_4_3.METH_write(DEF_x__h19196);
}

void MOD_mkTopSystolic::RL_c_column3()
{
  tUWide DEF_AVMeth_systolic_unit_get_result(128u, false);
  DEF_AVMeth_systolic_unit_get_result = INST_systolic_unit.METH_get_result();
  DEF_systolic_unit_get_result___d106 = DEF_AVMeth_systolic_unit_get_result;
  DEF_x__h19196 = DEF_systolic_unit_get_result___d106.get_whole_word(3u);
  DEF_x__h19091 = DEF_systolic_unit_get_result___d106.get_whole_word(2u);
  DEF_x__h18986 = DEF_systolic_unit_get_result___d106.get_whole_word(1u);
  DEF_x__h18784 = DEF_systolic_unit_get_result___d106.get_whole_word(0u);
  INST_c_matrix_top_3_0.METH_write(DEF_x__h18784);
  INST_c_matrix_top_3_1.METH_write(DEF_x__h18986);
  INST_c_matrix_top_3_2.METH_write(DEF_x__h19091);
  INST_c_matrix_top_3_3.METH_write(DEF_x__h19196);
}

void MOD_mkTopSystolic::RL_c_column2()
{
  tUWide DEF_AVMeth_systolic_unit_get_result(128u, false);
  DEF_AVMeth_systolic_unit_get_result = INST_systolic_unit.METH_get_result();
  DEF_systolic_unit_get_result___d106 = DEF_AVMeth_systolic_unit_get_result;
  DEF_x__h19196 = DEF_systolic_unit_get_result___d106.get_whole_word(3u);
  DEF_x__h19091 = DEF_systolic_unit_get_result___d106.get_whole_word(2u);
  DEF_x__h18986 = DEF_systolic_unit_get_result___d106.get_whole_word(1u);
  DEF_x__h18784 = DEF_systolic_unit_get_result___d106.get_whole_word(0u);
  INST_c_matrix_top_2_0.METH_write(DEF_x__h18784);
  INST_c_matrix_top_2_1.METH_write(DEF_x__h18986);
  INST_c_matrix_top_2_2.METH_write(DEF_x__h19091);
  INST_c_matrix_top_2_3.METH_write(DEF_x__h19196);
}

void MOD_mkTopSystolic::RL_c_column1()
{
  tUWide DEF_AVMeth_systolic_unit_get_result(128u, false);
  DEF_AVMeth_systolic_unit_get_result = INST_systolic_unit.METH_get_result();
  DEF_systolic_unit_get_result___d106 = DEF_AVMeth_systolic_unit_get_result;
  DEF_x__h19196 = DEF_systolic_unit_get_result___d106.get_whole_word(3u);
  DEF_x__h19091 = DEF_systolic_unit_get_result___d106.get_whole_word(2u);
  DEF_x__h18986 = DEF_systolic_unit_get_result___d106.get_whole_word(1u);
  DEF_x__h18784 = DEF_systolic_unit_get_result___d106.get_whole_word(0u);
  INST_c_matrix_top_1_0.METH_write(DEF_x__h18784);
  INST_c_matrix_top_1_1.METH_write(DEF_x__h18986);
  INST_c_matrix_top_1_2.METH_write(DEF_x__h19091);
  INST_c_matrix_top_1_3.METH_write(DEF_x__h19196);
}

void MOD_mkTopSystolic::RL_c_column0()
{
  tUWide DEF_AVMeth_systolic_unit_get_result(128u, false);
  DEF_AVMeth_systolic_unit_get_result = INST_systolic_unit.METH_get_result();
  DEF_systolic_unit_get_result___d106 = DEF_AVMeth_systolic_unit_get_result;
  DEF_x__h19196 = DEF_systolic_unit_get_result___d106.get_whole_word(3u);
  DEF_x__h19091 = DEF_systolic_unit_get_result___d106.get_whole_word(2u);
  DEF_x__h18986 = DEF_systolic_unit_get_result___d106.get_whole_word(1u);
  DEF_x__h18784 = DEF_systolic_unit_get_result___d106.get_whole_word(0u);
  INST_c_matrix_top_0_0.METH_write(DEF_x__h18784);
  INST_c_matrix_top_0_1.METH_write(DEF_x__h18986);
  INST_c_matrix_top_0_2.METH_write(DEF_x__h19091);
  INST_c_matrix_top_0_3.METH_write(DEF_x__h19196);
}

void MOD_mkTopSystolic::RL_count_up()
{
  tUInt32 DEF_x__h19276;
  DEF_x__h18595 = INST_counter.METH_read();
  DEF_x__h19276 = DEF_x__h18595 + 1u;
  INST_counter.METH_write(DEF_x__h19276);
}


/* Methods */

void MOD_mkTopSystolic::METH_set_A_matrix_in(tUWide ARG_set_A_matrix_in_a_matrix_in)
{
  tUInt32 DEF_x__h19340;
  tUInt32 DEF_x__h20466;
  tUInt32 DEF_x__h21010;
  tUInt32 DEF_x__h21554;
  tUInt32 DEF_x__h19653;
  tUInt32 DEF_x__h20553;
  tUInt32 DEF_x__h21097;
  tUInt32 DEF_x__h21641;
  tUInt32 DEF_x__h19858;
  tUInt32 DEF_x__h20640;
  tUInt32 DEF_x__h21184;
  tUInt32 DEF_x__h21728;
  tUInt32 DEF_x__h20063;
  tUInt32 DEF_x__h20727;
  tUInt32 DEF_x__h21271;
  tUInt32 DEF_x__h21806;
  PORT_set_A_matrix_in_a_matrix_in = ARG_set_A_matrix_in_a_matrix_in;
  DEF_x__h21806 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(7u, 16u, 16u);
  DEF_x__h21271 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(7u, 0u, 16u);
  DEF_x__h20727 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(6u, 16u, 16u);
  DEF_x__h20063 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(6u, 0u, 16u);
  DEF_x__h21184 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(5u, 0u, 16u);
  DEF_x__h21728 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(5u, 16u, 16u);
  DEF_x__h20640 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(4u, 16u, 16u);
  DEF_x__h19858 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(4u, 0u, 16u);
  DEF_x__h21641 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(3u, 16u, 16u);
  DEF_x__h21097 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(3u, 0u, 16u);
  DEF_x__h20553 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(2u, 16u, 16u);
  DEF_x__h19653 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(2u, 0u, 16u);
  DEF_x__h21010 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(1u, 0u, 16u);
  DEF_x__h21554 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(1u, 16u, 16u);
  DEF_x__h20466 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(0u, 16u, 16u);
  DEF_x__h19340 = ARG_set_A_matrix_in_a_matrix_in.get_bits_in_word32(0u, 0u, 16u);
  INST_a_matrix_top_6_0.METH_write(DEF_x__h19340);
  INST_a_matrix_top_5_0.METH_write(DEF_x__h19653);
  INST_a_matrix_top_4_0.METH_write(DEF_x__h19858);
  INST_a_matrix_top_3_0.METH_write(DEF_x__h20063);
  INST_a_matrix_top_2_0.METH_write(0u);
  INST_a_matrix_top_1_0.METH_write(0u);
  INST_a_matrix_top_0_0.METH_write(0u);
  INST_a_matrix_top_6_1.METH_write(0u);
  INST_a_matrix_top_5_1.METH_write(DEF_x__h20466);
  INST_a_matrix_top_4_1.METH_write(DEF_x__h20553);
  INST_a_matrix_top_2_1.METH_write(DEF_x__h20727);
  INST_a_matrix_top_3_1.METH_write(DEF_x__h20640);
  INST_a_matrix_top_1_1.METH_write(0u);
  INST_a_matrix_top_0_1.METH_write(0u);
  INST_a_matrix_top_6_2.METH_write(0u);
  INST_a_matrix_top_5_2.METH_write(0u);
  INST_a_matrix_top_4_2.METH_write(DEF_x__h21010);
  INST_a_matrix_top_3_2.METH_write(DEF_x__h21097);
  INST_a_matrix_top_1_2.METH_write(DEF_x__h21271);
  INST_a_matrix_top_2_2.METH_write(DEF_x__h21184);
  INST_a_matrix_top_0_2.METH_write(0u);
  INST_a_matrix_top_5_3.METH_write(0u);
  INST_a_matrix_top_6_3.METH_write(0u);
  INST_a_matrix_top_4_3.METH_write(0u);
  INST_a_matrix_top_3_3.METH_write(DEF_x__h21554);
  INST_a_matrix_top_2_3.METH_write(DEF_x__h21641);
  INST_a_matrix_top_1_3.METH_write(DEF_x__h21728);
  INST_a_matrix_top_0_3.METH_write(DEF_x__h21806);
}

tUInt8 MOD_mkTopSystolic::METH_RDY_set_A_matrix_in()
{
  tUInt8 DEF_CAN_FIRE_set_A_matrix_in;
  tUInt8 PORT_RDY_set_A_matrix_in;
  DEF_CAN_FIRE_set_A_matrix_in = (tUInt8)1u;
  PORT_RDY_set_A_matrix_in = DEF_CAN_FIRE_set_A_matrix_in;
  return PORT_RDY_set_A_matrix_in;
}

void MOD_mkTopSystolic::METH_set_B_matrix_in(tUWide ARG_set_B_matrix_in_b_matrix_in)
{
  tUInt32 DEF_x__h21929;
  tUInt32 DEF_x__h22255;
  tUInt32 DEF_x__h22357;
  tUInt32 DEF_x__h22459;
  tUInt32 DEF_x__h22606;
  tUInt32 DEF_x__h22826;
  tUInt32 DEF_x__h22928;
  tUInt32 DEF_x__h23030;
  tUInt32 DEF_x__h23177;
  tUInt32 DEF_x__h23397;
  tUInt32 DEF_x__h23499;
  tUInt32 DEF_x__h23601;
  tUInt32 DEF_x__h23748;
  tUInt32 DEF_x__h23968;
  tUInt32 DEF_x__h24070;
  tUInt32 DEF_x__h24172;
  PORT_set_B_matrix_in_b_matrix_in = ARG_set_B_matrix_in_b_matrix_in;
  DEF_x__h24172 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(7u, 16u, 16u);
  DEF_x__h24070 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(7u, 0u, 16u);
  DEF_x__h23968 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(6u, 16u, 16u);
  DEF_x__h23748 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(6u, 0u, 16u);
  DEF_x__h23601 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(5u, 16u, 16u);
  DEF_x__h23499 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(5u, 0u, 16u);
  DEF_x__h23397 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(4u, 16u, 16u);
  DEF_x__h23177 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(4u, 0u, 16u);
  DEF_x__h23030 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(3u, 16u, 16u);
  DEF_x__h22928 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(3u, 0u, 16u);
  DEF_x__h22826 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(2u, 16u, 16u);
  DEF_x__h22606 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(2u, 0u, 16u);
  DEF_x__h22459 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(1u, 16u, 16u);
  DEF_x__h22357 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(1u, 0u, 16u);
  DEF_x__h22255 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(0u, 16u, 16u);
  DEF_x__h21929 = ARG_set_B_matrix_in_b_matrix_in.get_bits_in_word32(0u, 0u, 16u);
  INST_b_matrix_top_0_0.METH_write(DEF_x__h21929);
  INST_b_matrix_top_0_1.METH_write(DEF_x__h22255);
  INST_b_matrix_top_0_2.METH_write(DEF_x__h22357);
  INST_b_matrix_top_0_3.METH_write(DEF_x__h22459);
  INST_b_matrix_top_1_0.METH_write(DEF_x__h22606);
  INST_b_matrix_top_1_2.METH_write(DEF_x__h22928);
  INST_b_matrix_top_1_1.METH_write(DEF_x__h22826);
  INST_b_matrix_top_1_3.METH_write(DEF_x__h23030);
  INST_b_matrix_top_2_0.METH_write(DEF_x__h23177);
  INST_b_matrix_top_2_1.METH_write(DEF_x__h23397);
  INST_b_matrix_top_2_2.METH_write(DEF_x__h23499);
  INST_b_matrix_top_2_3.METH_write(DEF_x__h23601);
  INST_b_matrix_top_3_0.METH_write(DEF_x__h23748);
  INST_b_matrix_top_3_1.METH_write(DEF_x__h23968);
  INST_b_matrix_top_3_2.METH_write(DEF_x__h24070);
  INST_b_matrix_top_3_3.METH_write(DEF_x__h24172);
}

tUInt8 MOD_mkTopSystolic::METH_RDY_set_B_matrix_in()
{
  tUInt8 DEF_CAN_FIRE_set_B_matrix_in;
  tUInt8 PORT_RDY_set_B_matrix_in;
  DEF_CAN_FIRE_set_B_matrix_in = (tUInt8)1u;
  PORT_RDY_set_B_matrix_in = DEF_CAN_FIRE_set_B_matrix_in;
  return PORT_RDY_set_B_matrix_in;
}

void MOD_mkTopSystolic::METH_set_s1_or_s2_top(tUInt8 ARG_set_s1_or_s2_top_s1_or_s2_in)
{
  INST_s1_or_s2_systolic.METH_write(ARG_set_s1_or_s2_top_s1_or_s2_in);
}

tUInt8 MOD_mkTopSystolic::METH_RDY_set_s1_or_s2_top()
{
  tUInt8 DEF_CAN_FIRE_set_s1_or_s2_top;
  tUInt8 PORT_RDY_set_s1_or_s2_top;
  DEF_CAN_FIRE_set_s1_or_s2_top = (tUInt8)1u;
  PORT_RDY_set_s1_or_s2_top = DEF_CAN_FIRE_set_s1_or_s2_top;
  return PORT_RDY_set_s1_or_s2_top;
}

tUWide MOD_mkTopSystolic::METH_get_matrix_mul_result()
{
  tUInt32 DEF_c_matrix_top_0_3__h25215;
  tUInt32 DEF_c_matrix_top_1_2__h25273;
  tUInt32 DEF_c_matrix_top_1_3__h25742;
  tUInt32 DEF_c_matrix_top_2_1__h25331;
  tUInt32 DEF_c_matrix_top_2_2__h25800;
  tUInt32 DEF_c_matrix_top_2_3__h26269;
  tUInt32 DEF_c_matrix_top_3_0__h25389;
  tUInt32 DEF_c_matrix_top_3_1__h25858;
  tUInt32 DEF_c_matrix_top_3_2__h26327;
  tUInt32 DEF_c_matrix_top_3_3__h26796;
  tUInt32 DEF_c_matrix_top_4_0__h25916;
  tUInt32 DEF_c_matrix_top_4_1__h26385;
  tUInt32 DEF_c_matrix_top_4_2__h26854;
  tUInt32 DEF_c_matrix_top_5_0__h26443;
  tUInt32 DEF_c_matrix_top_5_1__h26912;
  tUInt32 DEF_c_matrix_top_6_0__h26970;
  DEF_c_matrix_top_6_0__h26970 = INST_c_matrix_top_6_0.METH_read();
  DEF_c_matrix_top_5_1__h26912 = INST_c_matrix_top_5_1.METH_read();
  DEF_c_matrix_top_5_0__h26443 = INST_c_matrix_top_5_0.METH_read();
  DEF_c_matrix_top_4_1__h26385 = INST_c_matrix_top_4_1.METH_read();
  DEF_c_matrix_top_4_2__h26854 = INST_c_matrix_top_4_2.METH_read();
  DEF_c_matrix_top_4_0__h25916 = INST_c_matrix_top_4_0.METH_read();
  DEF_c_matrix_top_3_3__h26796 = INST_c_matrix_top_3_3.METH_read();
  DEF_c_matrix_top_3_1__h25858 = INST_c_matrix_top_3_1.METH_read();
  DEF_c_matrix_top_3_2__h26327 = INST_c_matrix_top_3_2.METH_read();
  DEF_c_matrix_top_3_0__h25389 = INST_c_matrix_top_3_0.METH_read();
  DEF_c_matrix_top_2_3__h26269 = INST_c_matrix_top_2_3.METH_read();
  DEF_c_matrix_top_2_1__h25331 = INST_c_matrix_top_2_1.METH_read();
  DEF_c_matrix_top_2_2__h25800 = INST_c_matrix_top_2_2.METH_read();
  DEF_c_matrix_top_1_3__h25742 = INST_c_matrix_top_1_3.METH_read();
  DEF_c_matrix_top_0_3__h25215 = INST_c_matrix_top_0_3.METH_read();
  DEF_c_matrix_top_1_2__h25273 = INST_c_matrix_top_1_2.METH_read();
  DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154.set_whole_word(DEF_c_matrix_top_0_3__h25215,
									       2u).set_whole_word(DEF_c_matrix_top_1_2__h25273,
												  1u).set_whole_word(DEF_c_matrix_top_2_1__h25331,
														     0u);
  DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159.set_whole_word(DEF_c_matrix_top_1_3__h25742,
									       2u).set_whole_word(DEF_c_matrix_top_2_2__h25800,
												  1u).set_whole_word(DEF_c_matrix_top_3_1__h25858,
														     0u);
  DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154.get_whole_word(2u),
									       7u).set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154.get_whole_word(1u),
												  6u).build_concat(bs_wide_tmp(96u).set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154.get_whole_word(0u),
																		   2u).set_whole_word(DEF_c_matrix_top_3_0__h25389,
																				      1u).set_whole_word(DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159.get_whole_word(2u),
																							 0u),
														   96u,
														   96u).set_whole_word(DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159.get_whole_word(1u),
																       2u).build_concat((((tUInt64)(DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159.get_whole_word(0u))) << 32u) | (tUInt64)(DEF_c_matrix_top_4_0__h25916),
																			0u,
																			64u);
  DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167.set_whole_word(DEF_c_matrix_top_2_3__h26269,
									       3u).set_whole_word(DEF_c_matrix_top_3_2__h26327,
												  2u).set_whole_word(DEF_c_matrix_top_4_1__h26385,
														     1u).set_whole_word(DEF_c_matrix_top_5_0__h26443,
																	0u);
  DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171.set_whole_word(DEF_c_matrix_top_3_3__h26796,
									       2u).set_whole_word(DEF_c_matrix_top_4_2__h26854,
												  1u).set_whole_word(DEF_c_matrix_top_5_1__h26912,
														     0u);
  PORT_get_matrix_mul_result.set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.get_whole_word(7u),
					    15u).set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.get_whole_word(6u),
								14u).set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.get_whole_word(5u),
										    13u).set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.get_whole_word(4u),
													12u).set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.get_whole_word(3u),
															    11u).set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.get_whole_word(2u),
																		10u).set_whole_word(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.get_whole_word(1u),
																				    9u).build_concat((((tUInt64)(DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161.get_whole_word(0u))) << 32u) | (tUInt64)(DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167.get_whole_word(3u)),
																						     224u,
																						     64u).set_whole_word(DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167.get_whole_word(2u),
																									 6u).set_whole_word(DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167.get_whole_word(1u),
																											    5u).build_concat((((tUInt64)(DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167.get_whole_word(0u))) << 32u) | (tUInt64)(DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171.get_whole_word(2u)),
																													     96u,
																													     64u).set_whole_word(DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171.get_whole_word(1u),
																																 2u).build_concat((((tUInt64)(DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171.get_whole_word(0u))) << 32u) | (tUInt64)(DEF_c_matrix_top_6_0__h26970),
																																		  0u,
																																		  64u);
  return PORT_get_matrix_mul_result;
}

tUInt8 MOD_mkTopSystolic::METH_RDY_get_matrix_mul_result()
{
  tUInt8 DEF_CAN_FIRE_get_matrix_mul_result;
  tUInt8 PORT_RDY_get_matrix_mul_result;
  DEF_CAN_FIRE_get_matrix_mul_result = (tUInt8)1u;
  PORT_RDY_get_matrix_mul_result = DEF_CAN_FIRE_get_matrix_mul_result;
  return PORT_RDY_get_matrix_mul_result;
}


/* Reset routines */

void MOD_mkTopSystolic::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_systolic_unit.reset_RST_N(ARG_rst_in);
  INST_s1_or_s2_systolic.reset_RST(ARG_rst_in);
  INST_counter.reset_RST(ARG_rst_in);
  INST_c_matrix_top_6_3.reset_RST(ARG_rst_in);
  INST_c_matrix_top_6_2.reset_RST(ARG_rst_in);
  INST_c_matrix_top_6_1.reset_RST(ARG_rst_in);
  INST_c_matrix_top_6_0.reset_RST(ARG_rst_in);
  INST_c_matrix_top_5_3.reset_RST(ARG_rst_in);
  INST_c_matrix_top_5_2.reset_RST(ARG_rst_in);
  INST_c_matrix_top_5_1.reset_RST(ARG_rst_in);
  INST_c_matrix_top_5_0.reset_RST(ARG_rst_in);
  INST_c_matrix_top_4_3.reset_RST(ARG_rst_in);
  INST_c_matrix_top_4_2.reset_RST(ARG_rst_in);
  INST_c_matrix_top_4_1.reset_RST(ARG_rst_in);
  INST_c_matrix_top_4_0.reset_RST(ARG_rst_in);
  INST_c_matrix_top_3_3.reset_RST(ARG_rst_in);
  INST_c_matrix_top_3_2.reset_RST(ARG_rst_in);
  INST_c_matrix_top_3_1.reset_RST(ARG_rst_in);
  INST_c_matrix_top_3_0.reset_RST(ARG_rst_in);
  INST_c_matrix_top_2_3.reset_RST(ARG_rst_in);
  INST_c_matrix_top_2_2.reset_RST(ARG_rst_in);
  INST_c_matrix_top_2_1.reset_RST(ARG_rst_in);
  INST_c_matrix_top_2_0.reset_RST(ARG_rst_in);
  INST_c_matrix_top_1_3.reset_RST(ARG_rst_in);
  INST_c_matrix_top_1_2.reset_RST(ARG_rst_in);
  INST_c_matrix_top_1_1.reset_RST(ARG_rst_in);
  INST_c_matrix_top_1_0.reset_RST(ARG_rst_in);
  INST_c_matrix_top_0_3.reset_RST(ARG_rst_in);
  INST_c_matrix_top_0_2.reset_RST(ARG_rst_in);
  INST_c_matrix_top_0_1.reset_RST(ARG_rst_in);
  INST_c_matrix_top_0_0.reset_RST(ARG_rst_in);
  INST_b_matrix_top_3_3.reset_RST(ARG_rst_in);
  INST_b_matrix_top_3_2.reset_RST(ARG_rst_in);
  INST_b_matrix_top_3_1.reset_RST(ARG_rst_in);
  INST_b_matrix_top_3_0.reset_RST(ARG_rst_in);
  INST_b_matrix_top_2_3.reset_RST(ARG_rst_in);
  INST_b_matrix_top_2_2.reset_RST(ARG_rst_in);
  INST_b_matrix_top_2_1.reset_RST(ARG_rst_in);
  INST_b_matrix_top_2_0.reset_RST(ARG_rst_in);
  INST_b_matrix_top_1_3.reset_RST(ARG_rst_in);
  INST_b_matrix_top_1_2.reset_RST(ARG_rst_in);
  INST_b_matrix_top_1_1.reset_RST(ARG_rst_in);
  INST_b_matrix_top_1_0.reset_RST(ARG_rst_in);
  INST_b_matrix_top_0_3.reset_RST(ARG_rst_in);
  INST_b_matrix_top_0_2.reset_RST(ARG_rst_in);
  INST_b_matrix_top_0_1.reset_RST(ARG_rst_in);
  INST_b_matrix_top_0_0.reset_RST(ARG_rst_in);
  INST_a_matrix_top_6_3.reset_RST(ARG_rst_in);
  INST_a_matrix_top_6_2.reset_RST(ARG_rst_in);
  INST_a_matrix_top_6_1.reset_RST(ARG_rst_in);
  INST_a_matrix_top_6_0.reset_RST(ARG_rst_in);
  INST_a_matrix_top_5_3.reset_RST(ARG_rst_in);
  INST_a_matrix_top_5_2.reset_RST(ARG_rst_in);
  INST_a_matrix_top_5_1.reset_RST(ARG_rst_in);
  INST_a_matrix_top_5_0.reset_RST(ARG_rst_in);
  INST_a_matrix_top_4_3.reset_RST(ARG_rst_in);
  INST_a_matrix_top_4_2.reset_RST(ARG_rst_in);
  INST_a_matrix_top_4_1.reset_RST(ARG_rst_in);
  INST_a_matrix_top_4_0.reset_RST(ARG_rst_in);
  INST_a_matrix_top_3_3.reset_RST(ARG_rst_in);
  INST_a_matrix_top_3_2.reset_RST(ARG_rst_in);
  INST_a_matrix_top_3_1.reset_RST(ARG_rst_in);
  INST_a_matrix_top_3_0.reset_RST(ARG_rst_in);
  INST_a_matrix_top_2_3.reset_RST(ARG_rst_in);
  INST_a_matrix_top_2_2.reset_RST(ARG_rst_in);
  INST_a_matrix_top_2_1.reset_RST(ARG_rst_in);
  INST_a_matrix_top_2_0.reset_RST(ARG_rst_in);
  INST_a_matrix_top_1_3.reset_RST(ARG_rst_in);
  INST_a_matrix_top_1_2.reset_RST(ARG_rst_in);
  INST_a_matrix_top_1_1.reset_RST(ARG_rst_in);
  INST_a_matrix_top_1_0.reset_RST(ARG_rst_in);
  INST_a_matrix_top_0_3.reset_RST(ARG_rst_in);
  INST_a_matrix_top_0_2.reset_RST(ARG_rst_in);
  INST_a_matrix_top_0_1.reset_RST(ARG_rst_in);
  INST_a_matrix_top_0_0.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkTopSystolic::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkTopSystolic::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_a_matrix_top_0_0.dump_state(indent + 2u);
  INST_a_matrix_top_0_1.dump_state(indent + 2u);
  INST_a_matrix_top_0_2.dump_state(indent + 2u);
  INST_a_matrix_top_0_3.dump_state(indent + 2u);
  INST_a_matrix_top_1_0.dump_state(indent + 2u);
  INST_a_matrix_top_1_1.dump_state(indent + 2u);
  INST_a_matrix_top_1_2.dump_state(indent + 2u);
  INST_a_matrix_top_1_3.dump_state(indent + 2u);
  INST_a_matrix_top_2_0.dump_state(indent + 2u);
  INST_a_matrix_top_2_1.dump_state(indent + 2u);
  INST_a_matrix_top_2_2.dump_state(indent + 2u);
  INST_a_matrix_top_2_3.dump_state(indent + 2u);
  INST_a_matrix_top_3_0.dump_state(indent + 2u);
  INST_a_matrix_top_3_1.dump_state(indent + 2u);
  INST_a_matrix_top_3_2.dump_state(indent + 2u);
  INST_a_matrix_top_3_3.dump_state(indent + 2u);
  INST_a_matrix_top_4_0.dump_state(indent + 2u);
  INST_a_matrix_top_4_1.dump_state(indent + 2u);
  INST_a_matrix_top_4_2.dump_state(indent + 2u);
  INST_a_matrix_top_4_3.dump_state(indent + 2u);
  INST_a_matrix_top_5_0.dump_state(indent + 2u);
  INST_a_matrix_top_5_1.dump_state(indent + 2u);
  INST_a_matrix_top_5_2.dump_state(indent + 2u);
  INST_a_matrix_top_5_3.dump_state(indent + 2u);
  INST_a_matrix_top_6_0.dump_state(indent + 2u);
  INST_a_matrix_top_6_1.dump_state(indent + 2u);
  INST_a_matrix_top_6_2.dump_state(indent + 2u);
  INST_a_matrix_top_6_3.dump_state(indent + 2u);
  INST_b_matrix_top_0_0.dump_state(indent + 2u);
  INST_b_matrix_top_0_1.dump_state(indent + 2u);
  INST_b_matrix_top_0_2.dump_state(indent + 2u);
  INST_b_matrix_top_0_3.dump_state(indent + 2u);
  INST_b_matrix_top_1_0.dump_state(indent + 2u);
  INST_b_matrix_top_1_1.dump_state(indent + 2u);
  INST_b_matrix_top_1_2.dump_state(indent + 2u);
  INST_b_matrix_top_1_3.dump_state(indent + 2u);
  INST_b_matrix_top_2_0.dump_state(indent + 2u);
  INST_b_matrix_top_2_1.dump_state(indent + 2u);
  INST_b_matrix_top_2_2.dump_state(indent + 2u);
  INST_b_matrix_top_2_3.dump_state(indent + 2u);
  INST_b_matrix_top_3_0.dump_state(indent + 2u);
  INST_b_matrix_top_3_1.dump_state(indent + 2u);
  INST_b_matrix_top_3_2.dump_state(indent + 2u);
  INST_b_matrix_top_3_3.dump_state(indent + 2u);
  INST_c_matrix_top_0_0.dump_state(indent + 2u);
  INST_c_matrix_top_0_1.dump_state(indent + 2u);
  INST_c_matrix_top_0_2.dump_state(indent + 2u);
  INST_c_matrix_top_0_3.dump_state(indent + 2u);
  INST_c_matrix_top_1_0.dump_state(indent + 2u);
  INST_c_matrix_top_1_1.dump_state(indent + 2u);
  INST_c_matrix_top_1_2.dump_state(indent + 2u);
  INST_c_matrix_top_1_3.dump_state(indent + 2u);
  INST_c_matrix_top_2_0.dump_state(indent + 2u);
  INST_c_matrix_top_2_1.dump_state(indent + 2u);
  INST_c_matrix_top_2_2.dump_state(indent + 2u);
  INST_c_matrix_top_2_3.dump_state(indent + 2u);
  INST_c_matrix_top_3_0.dump_state(indent + 2u);
  INST_c_matrix_top_3_1.dump_state(indent + 2u);
  INST_c_matrix_top_3_2.dump_state(indent + 2u);
  INST_c_matrix_top_3_3.dump_state(indent + 2u);
  INST_c_matrix_top_4_0.dump_state(indent + 2u);
  INST_c_matrix_top_4_1.dump_state(indent + 2u);
  INST_c_matrix_top_4_2.dump_state(indent + 2u);
  INST_c_matrix_top_4_3.dump_state(indent + 2u);
  INST_c_matrix_top_5_0.dump_state(indent + 2u);
  INST_c_matrix_top_5_1.dump_state(indent + 2u);
  INST_c_matrix_top_5_2.dump_state(indent + 2u);
  INST_c_matrix_top_5_3.dump_state(indent + 2u);
  INST_c_matrix_top_6_0.dump_state(indent + 2u);
  INST_c_matrix_top_6_1.dump_state(indent + 2u);
  INST_c_matrix_top_6_2.dump_state(indent + 2u);
  INST_c_matrix_top_6_3.dump_state(indent + 2u);
  INST_counter.dump_state(indent + 2u);
  INST_s1_or_s2_systolic.dump_state(indent + 2u);
  INST_systolic_unit.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkTopSystolic::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 90u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161", 256u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167", 128u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171", 96u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "s1_or_s2_in__h14273", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "systolic_unit_get_result___d106", 128u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h18595", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h18784", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h18986", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h19091", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h19196", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "get_matrix_mul_result", 512u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "set_A_matrix_in_a_matrix_in", 256u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "set_B_matrix_in_b_matrix_in", 256u);
  num = INST_a_matrix_top_0_0.dump_VCD_defs(num);
  num = INST_a_matrix_top_0_1.dump_VCD_defs(num);
  num = INST_a_matrix_top_0_2.dump_VCD_defs(num);
  num = INST_a_matrix_top_0_3.dump_VCD_defs(num);
  num = INST_a_matrix_top_1_0.dump_VCD_defs(num);
  num = INST_a_matrix_top_1_1.dump_VCD_defs(num);
  num = INST_a_matrix_top_1_2.dump_VCD_defs(num);
  num = INST_a_matrix_top_1_3.dump_VCD_defs(num);
  num = INST_a_matrix_top_2_0.dump_VCD_defs(num);
  num = INST_a_matrix_top_2_1.dump_VCD_defs(num);
  num = INST_a_matrix_top_2_2.dump_VCD_defs(num);
  num = INST_a_matrix_top_2_3.dump_VCD_defs(num);
  num = INST_a_matrix_top_3_0.dump_VCD_defs(num);
  num = INST_a_matrix_top_3_1.dump_VCD_defs(num);
  num = INST_a_matrix_top_3_2.dump_VCD_defs(num);
  num = INST_a_matrix_top_3_3.dump_VCD_defs(num);
  num = INST_a_matrix_top_4_0.dump_VCD_defs(num);
  num = INST_a_matrix_top_4_1.dump_VCD_defs(num);
  num = INST_a_matrix_top_4_2.dump_VCD_defs(num);
  num = INST_a_matrix_top_4_3.dump_VCD_defs(num);
  num = INST_a_matrix_top_5_0.dump_VCD_defs(num);
  num = INST_a_matrix_top_5_1.dump_VCD_defs(num);
  num = INST_a_matrix_top_5_2.dump_VCD_defs(num);
  num = INST_a_matrix_top_5_3.dump_VCD_defs(num);
  num = INST_a_matrix_top_6_0.dump_VCD_defs(num);
  num = INST_a_matrix_top_6_1.dump_VCD_defs(num);
  num = INST_a_matrix_top_6_2.dump_VCD_defs(num);
  num = INST_a_matrix_top_6_3.dump_VCD_defs(num);
  num = INST_b_matrix_top_0_0.dump_VCD_defs(num);
  num = INST_b_matrix_top_0_1.dump_VCD_defs(num);
  num = INST_b_matrix_top_0_2.dump_VCD_defs(num);
  num = INST_b_matrix_top_0_3.dump_VCD_defs(num);
  num = INST_b_matrix_top_1_0.dump_VCD_defs(num);
  num = INST_b_matrix_top_1_1.dump_VCD_defs(num);
  num = INST_b_matrix_top_1_2.dump_VCD_defs(num);
  num = INST_b_matrix_top_1_3.dump_VCD_defs(num);
  num = INST_b_matrix_top_2_0.dump_VCD_defs(num);
  num = INST_b_matrix_top_2_1.dump_VCD_defs(num);
  num = INST_b_matrix_top_2_2.dump_VCD_defs(num);
  num = INST_b_matrix_top_2_3.dump_VCD_defs(num);
  num = INST_b_matrix_top_3_0.dump_VCD_defs(num);
  num = INST_b_matrix_top_3_1.dump_VCD_defs(num);
  num = INST_b_matrix_top_3_2.dump_VCD_defs(num);
  num = INST_b_matrix_top_3_3.dump_VCD_defs(num);
  num = INST_c_matrix_top_0_0.dump_VCD_defs(num);
  num = INST_c_matrix_top_0_1.dump_VCD_defs(num);
  num = INST_c_matrix_top_0_2.dump_VCD_defs(num);
  num = INST_c_matrix_top_0_3.dump_VCD_defs(num);
  num = INST_c_matrix_top_1_0.dump_VCD_defs(num);
  num = INST_c_matrix_top_1_1.dump_VCD_defs(num);
  num = INST_c_matrix_top_1_2.dump_VCD_defs(num);
  num = INST_c_matrix_top_1_3.dump_VCD_defs(num);
  num = INST_c_matrix_top_2_0.dump_VCD_defs(num);
  num = INST_c_matrix_top_2_1.dump_VCD_defs(num);
  num = INST_c_matrix_top_2_2.dump_VCD_defs(num);
  num = INST_c_matrix_top_2_3.dump_VCD_defs(num);
  num = INST_c_matrix_top_3_0.dump_VCD_defs(num);
  num = INST_c_matrix_top_3_1.dump_VCD_defs(num);
  num = INST_c_matrix_top_3_2.dump_VCD_defs(num);
  num = INST_c_matrix_top_3_3.dump_VCD_defs(num);
  num = INST_c_matrix_top_4_0.dump_VCD_defs(num);
  num = INST_c_matrix_top_4_1.dump_VCD_defs(num);
  num = INST_c_matrix_top_4_2.dump_VCD_defs(num);
  num = INST_c_matrix_top_4_3.dump_VCD_defs(num);
  num = INST_c_matrix_top_5_0.dump_VCD_defs(num);
  num = INST_c_matrix_top_5_1.dump_VCD_defs(num);
  num = INST_c_matrix_top_5_2.dump_VCD_defs(num);
  num = INST_c_matrix_top_5_3.dump_VCD_defs(num);
  num = INST_c_matrix_top_6_0.dump_VCD_defs(num);
  num = INST_c_matrix_top_6_1.dump_VCD_defs(num);
  num = INST_c_matrix_top_6_2.dump_VCD_defs(num);
  num = INST_c_matrix_top_6_3.dump_VCD_defs(num);
  num = INST_counter.dump_VCD_defs(num);
  num = INST_s1_or_s2_systolic.dump_VCD_defs(num);
  if (levels != 1u)
  {
    unsigned int l = levels == 0u ? 0u : levels - 1u;
    num = INST_systolic_unit.dump_VCD_defs(l);
  }
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkTopSystolic::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTopSystolic &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
  if (levels != 1u)
    vcd_submodules(dt, levels - 1u, backing);
}

void MOD_mkTopSystolic::vcd_defs(tVCDDumpType dt, MOD_mkTopSystolic &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 256u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 96u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 128u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 512u);
    vcd_write_x(sim_hdl, num++, 256u);
    vcd_write_x(sim_hdl, num++, 256u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154) != DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154)
      {
	vcd_write_val(sim_hdl, num, DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154, 96u);
	backing.DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154 = DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154;
      }
      ++num;
      if ((backing.DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161) != DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161)
      {
	vcd_write_val(sim_hdl, num, DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161, 256u);
	backing.DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161 = DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161;
      }
      ++num;
      if ((backing.DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159) != DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159)
      {
	vcd_write_val(sim_hdl, num, DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159, 96u);
	backing.DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159 = DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159;
      }
      ++num;
      if ((backing.DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167) != DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167)
      {
	vcd_write_val(sim_hdl, num, DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167, 128u);
	backing.DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167 = DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167;
      }
      ++num;
      if ((backing.DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171) != DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171)
      {
	vcd_write_val(sim_hdl, num, DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171, 96u);
	backing.DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171 = DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171;
      }
      ++num;
      if ((backing.DEF_s1_or_s2_in__h14273) != DEF_s1_or_s2_in__h14273)
      {
	vcd_write_val(sim_hdl, num, DEF_s1_or_s2_in__h14273, 1u);
	backing.DEF_s1_or_s2_in__h14273 = DEF_s1_or_s2_in__h14273;
      }
      ++num;
      if ((backing.DEF_systolic_unit_get_result___d106) != DEF_systolic_unit_get_result___d106)
      {
	vcd_write_val(sim_hdl, num, DEF_systolic_unit_get_result___d106, 128u);
	backing.DEF_systolic_unit_get_result___d106 = DEF_systolic_unit_get_result___d106;
      }
      ++num;
      if ((backing.DEF_x__h18595) != DEF_x__h18595)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h18595, 32u);
	backing.DEF_x__h18595 = DEF_x__h18595;
      }
      ++num;
      if ((backing.DEF_x__h18784) != DEF_x__h18784)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h18784, 32u);
	backing.DEF_x__h18784 = DEF_x__h18784;
      }
      ++num;
      if ((backing.DEF_x__h18986) != DEF_x__h18986)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h18986, 32u);
	backing.DEF_x__h18986 = DEF_x__h18986;
      }
      ++num;
      if ((backing.DEF_x__h19091) != DEF_x__h19091)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h19091, 32u);
	backing.DEF_x__h19091 = DEF_x__h19091;
      }
      ++num;
      if ((backing.DEF_x__h19196) != DEF_x__h19196)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h19196, 32u);
	backing.DEF_x__h19196 = DEF_x__h19196;
      }
      ++num;
      if ((backing.PORT_get_matrix_mul_result) != PORT_get_matrix_mul_result)
      {
	vcd_write_val(sim_hdl, num, PORT_get_matrix_mul_result, 512u);
	backing.PORT_get_matrix_mul_result = PORT_get_matrix_mul_result;
      }
      ++num;
      if ((backing.PORT_set_A_matrix_in_a_matrix_in) != PORT_set_A_matrix_in_a_matrix_in)
      {
	vcd_write_val(sim_hdl, num, PORT_set_A_matrix_in_a_matrix_in, 256u);
	backing.PORT_set_A_matrix_in_a_matrix_in = PORT_set_A_matrix_in_a_matrix_in;
      }
      ++num;
      if ((backing.PORT_set_B_matrix_in_b_matrix_in) != PORT_set_B_matrix_in_b_matrix_in)
      {
	vcd_write_val(sim_hdl, num, PORT_set_B_matrix_in_b_matrix_in, 256u);
	backing.PORT_set_B_matrix_in_b_matrix_in = PORT_set_B_matrix_in_b_matrix_in;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154, 96u);
      backing.DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154 = DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d154;
      vcd_write_val(sim_hdl, num++, DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161, 256u);
      backing.DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161 = DEF_c_matrix_top_0_3_51_CONCAT_c_matrix_top_1_2_52_ETC___d161;
      vcd_write_val(sim_hdl, num++, DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159, 96u);
      backing.DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159 = DEF_c_matrix_top_1_3_56_CONCAT_c_matrix_top_2_2_57_ETC___d159;
      vcd_write_val(sim_hdl, num++, DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167, 128u);
      backing.DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167 = DEF_c_matrix_top_2_3_62_CONCAT_c_matrix_top_3_2_63_ETC___d167;
      vcd_write_val(sim_hdl, num++, DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171, 96u);
      backing.DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171 = DEF_c_matrix_top_3_3_68_CONCAT_c_matrix_top_4_2_69_ETC___d171;
      vcd_write_val(sim_hdl, num++, DEF_s1_or_s2_in__h14273, 1u);
      backing.DEF_s1_or_s2_in__h14273 = DEF_s1_or_s2_in__h14273;
      vcd_write_val(sim_hdl, num++, DEF_systolic_unit_get_result___d106, 128u);
      backing.DEF_systolic_unit_get_result___d106 = DEF_systolic_unit_get_result___d106;
      vcd_write_val(sim_hdl, num++, DEF_x__h18595, 32u);
      backing.DEF_x__h18595 = DEF_x__h18595;
      vcd_write_val(sim_hdl, num++, DEF_x__h18784, 32u);
      backing.DEF_x__h18784 = DEF_x__h18784;
      vcd_write_val(sim_hdl, num++, DEF_x__h18986, 32u);
      backing.DEF_x__h18986 = DEF_x__h18986;
      vcd_write_val(sim_hdl, num++, DEF_x__h19091, 32u);
      backing.DEF_x__h19091 = DEF_x__h19091;
      vcd_write_val(sim_hdl, num++, DEF_x__h19196, 32u);
      backing.DEF_x__h19196 = DEF_x__h19196;
      vcd_write_val(sim_hdl, num++, PORT_get_matrix_mul_result, 512u);
      backing.PORT_get_matrix_mul_result = PORT_get_matrix_mul_result;
      vcd_write_val(sim_hdl, num++, PORT_set_A_matrix_in_a_matrix_in, 256u);
      backing.PORT_set_A_matrix_in_a_matrix_in = PORT_set_A_matrix_in_a_matrix_in;
      vcd_write_val(sim_hdl, num++, PORT_set_B_matrix_in_b_matrix_in, 256u);
      backing.PORT_set_B_matrix_in_b_matrix_in = PORT_set_B_matrix_in_b_matrix_in;
    }
}

void MOD_mkTopSystolic::vcd_prims(tVCDDumpType dt, MOD_mkTopSystolic &backing)
{
  INST_a_matrix_top_0_0.dump_VCD(dt, backing.INST_a_matrix_top_0_0);
  INST_a_matrix_top_0_1.dump_VCD(dt, backing.INST_a_matrix_top_0_1);
  INST_a_matrix_top_0_2.dump_VCD(dt, backing.INST_a_matrix_top_0_2);
  INST_a_matrix_top_0_3.dump_VCD(dt, backing.INST_a_matrix_top_0_3);
  INST_a_matrix_top_1_0.dump_VCD(dt, backing.INST_a_matrix_top_1_0);
  INST_a_matrix_top_1_1.dump_VCD(dt, backing.INST_a_matrix_top_1_1);
  INST_a_matrix_top_1_2.dump_VCD(dt, backing.INST_a_matrix_top_1_2);
  INST_a_matrix_top_1_3.dump_VCD(dt, backing.INST_a_matrix_top_1_3);
  INST_a_matrix_top_2_0.dump_VCD(dt, backing.INST_a_matrix_top_2_0);
  INST_a_matrix_top_2_1.dump_VCD(dt, backing.INST_a_matrix_top_2_1);
  INST_a_matrix_top_2_2.dump_VCD(dt, backing.INST_a_matrix_top_2_2);
  INST_a_matrix_top_2_3.dump_VCD(dt, backing.INST_a_matrix_top_2_3);
  INST_a_matrix_top_3_0.dump_VCD(dt, backing.INST_a_matrix_top_3_0);
  INST_a_matrix_top_3_1.dump_VCD(dt, backing.INST_a_matrix_top_3_1);
  INST_a_matrix_top_3_2.dump_VCD(dt, backing.INST_a_matrix_top_3_2);
  INST_a_matrix_top_3_3.dump_VCD(dt, backing.INST_a_matrix_top_3_3);
  INST_a_matrix_top_4_0.dump_VCD(dt, backing.INST_a_matrix_top_4_0);
  INST_a_matrix_top_4_1.dump_VCD(dt, backing.INST_a_matrix_top_4_1);
  INST_a_matrix_top_4_2.dump_VCD(dt, backing.INST_a_matrix_top_4_2);
  INST_a_matrix_top_4_3.dump_VCD(dt, backing.INST_a_matrix_top_4_3);
  INST_a_matrix_top_5_0.dump_VCD(dt, backing.INST_a_matrix_top_5_0);
  INST_a_matrix_top_5_1.dump_VCD(dt, backing.INST_a_matrix_top_5_1);
  INST_a_matrix_top_5_2.dump_VCD(dt, backing.INST_a_matrix_top_5_2);
  INST_a_matrix_top_5_3.dump_VCD(dt, backing.INST_a_matrix_top_5_3);
  INST_a_matrix_top_6_0.dump_VCD(dt, backing.INST_a_matrix_top_6_0);
  INST_a_matrix_top_6_1.dump_VCD(dt, backing.INST_a_matrix_top_6_1);
  INST_a_matrix_top_6_2.dump_VCD(dt, backing.INST_a_matrix_top_6_2);
  INST_a_matrix_top_6_3.dump_VCD(dt, backing.INST_a_matrix_top_6_3);
  INST_b_matrix_top_0_0.dump_VCD(dt, backing.INST_b_matrix_top_0_0);
  INST_b_matrix_top_0_1.dump_VCD(dt, backing.INST_b_matrix_top_0_1);
  INST_b_matrix_top_0_2.dump_VCD(dt, backing.INST_b_matrix_top_0_2);
  INST_b_matrix_top_0_3.dump_VCD(dt, backing.INST_b_matrix_top_0_3);
  INST_b_matrix_top_1_0.dump_VCD(dt, backing.INST_b_matrix_top_1_0);
  INST_b_matrix_top_1_1.dump_VCD(dt, backing.INST_b_matrix_top_1_1);
  INST_b_matrix_top_1_2.dump_VCD(dt, backing.INST_b_matrix_top_1_2);
  INST_b_matrix_top_1_3.dump_VCD(dt, backing.INST_b_matrix_top_1_3);
  INST_b_matrix_top_2_0.dump_VCD(dt, backing.INST_b_matrix_top_2_0);
  INST_b_matrix_top_2_1.dump_VCD(dt, backing.INST_b_matrix_top_2_1);
  INST_b_matrix_top_2_2.dump_VCD(dt, backing.INST_b_matrix_top_2_2);
  INST_b_matrix_top_2_3.dump_VCD(dt, backing.INST_b_matrix_top_2_3);
  INST_b_matrix_top_3_0.dump_VCD(dt, backing.INST_b_matrix_top_3_0);
  INST_b_matrix_top_3_1.dump_VCD(dt, backing.INST_b_matrix_top_3_1);
  INST_b_matrix_top_3_2.dump_VCD(dt, backing.INST_b_matrix_top_3_2);
  INST_b_matrix_top_3_3.dump_VCD(dt, backing.INST_b_matrix_top_3_3);
  INST_c_matrix_top_0_0.dump_VCD(dt, backing.INST_c_matrix_top_0_0);
  INST_c_matrix_top_0_1.dump_VCD(dt, backing.INST_c_matrix_top_0_1);
  INST_c_matrix_top_0_2.dump_VCD(dt, backing.INST_c_matrix_top_0_2);
  INST_c_matrix_top_0_3.dump_VCD(dt, backing.INST_c_matrix_top_0_3);
  INST_c_matrix_top_1_0.dump_VCD(dt, backing.INST_c_matrix_top_1_0);
  INST_c_matrix_top_1_1.dump_VCD(dt, backing.INST_c_matrix_top_1_1);
  INST_c_matrix_top_1_2.dump_VCD(dt, backing.INST_c_matrix_top_1_2);
  INST_c_matrix_top_1_3.dump_VCD(dt, backing.INST_c_matrix_top_1_3);
  INST_c_matrix_top_2_0.dump_VCD(dt, backing.INST_c_matrix_top_2_0);
  INST_c_matrix_top_2_1.dump_VCD(dt, backing.INST_c_matrix_top_2_1);
  INST_c_matrix_top_2_2.dump_VCD(dt, backing.INST_c_matrix_top_2_2);
  INST_c_matrix_top_2_3.dump_VCD(dt, backing.INST_c_matrix_top_2_3);
  INST_c_matrix_top_3_0.dump_VCD(dt, backing.INST_c_matrix_top_3_0);
  INST_c_matrix_top_3_1.dump_VCD(dt, backing.INST_c_matrix_top_3_1);
  INST_c_matrix_top_3_2.dump_VCD(dt, backing.INST_c_matrix_top_3_2);
  INST_c_matrix_top_3_3.dump_VCD(dt, backing.INST_c_matrix_top_3_3);
  INST_c_matrix_top_4_0.dump_VCD(dt, backing.INST_c_matrix_top_4_0);
  INST_c_matrix_top_4_1.dump_VCD(dt, backing.INST_c_matrix_top_4_1);
  INST_c_matrix_top_4_2.dump_VCD(dt, backing.INST_c_matrix_top_4_2);
  INST_c_matrix_top_4_3.dump_VCD(dt, backing.INST_c_matrix_top_4_3);
  INST_c_matrix_top_5_0.dump_VCD(dt, backing.INST_c_matrix_top_5_0);
  INST_c_matrix_top_5_1.dump_VCD(dt, backing.INST_c_matrix_top_5_1);
  INST_c_matrix_top_5_2.dump_VCD(dt, backing.INST_c_matrix_top_5_2);
  INST_c_matrix_top_5_3.dump_VCD(dt, backing.INST_c_matrix_top_5_3);
  INST_c_matrix_top_6_0.dump_VCD(dt, backing.INST_c_matrix_top_6_0);
  INST_c_matrix_top_6_1.dump_VCD(dt, backing.INST_c_matrix_top_6_1);
  INST_c_matrix_top_6_2.dump_VCD(dt, backing.INST_c_matrix_top_6_2);
  INST_c_matrix_top_6_3.dump_VCD(dt, backing.INST_c_matrix_top_6_3);
  INST_counter.dump_VCD(dt, backing.INST_counter);
  INST_s1_or_s2_systolic.dump_VCD(dt, backing.INST_s1_or_s2_systolic);
}

void MOD_mkTopSystolic::vcd_submodules(tVCDDumpType dt,
				       unsigned int levels,
				       MOD_mkTopSystolic &backing)
{
  INST_systolic_unit.dump_VCD(dt, levels, backing.INST_systolic_unit);
}
